using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.Dynamics.Framework.UI;
using Microsoft.Dynamics.Nav.Client;
using Microsoft.Dynamics.Nav.Client.WinClient;
using Microsoft.Dynamics.Nav.Types.Metadata;
using Microsoft.Dynamics.Nav.Types;
using Microsoft.Dynamics.Nav.Client.Visualizations;
using Microsoft.Dynamics.Nav.Types.Data;
using System.Text.RegularExpressions;
using Microsoft.Dynamics.Nav.Client.Actions;

using System.Diagnostics; // stopwatch

//using System.IO;
//using System.Collections.Generic; //for dictionary
using System.Runtime.InteropServices; //for P/Invoke DLLImport

//using Microsoft.Win32;


namespace ConsoleAppCreateAdvanseStatements
{
    public static class Encodinggg
    {
        public static string EncodeBase64(this System.Text.Encoding encoding, string text)
        {

            if (text == null)
            {
                return null;
            }

            byte[] textAsBytes = encoding.GetBytes(text);
            return System.Convert.ToBase64String(textAsBytes);
        }

        public static string DecodeBase64(this System.Text.Encoding encoding, string encodedText)
        {
            if (encodedText == null)
            {
                return null;
            }

            byte[] textAsBytes = System.Convert.FromBase64String(encodedText);
            return encoding.GetString(textAsBytes);
        }
    }




    class Program
    {


        static void Main(string[] args)
        {

            //foreach (var i in Enumerable.Range(0, 100)) // why "100"? it is just any number
            //{
            //    SetConsoleTextAttribute(GetStdHandle(-11), (short)i);
            //    Console.WriteLine("Hello = {0}", i);
            //}

            ShowWindow(Process.GetCurrentProcess().MainWindowHandle, 3); //SW_MAXIMIZE = 3



            string iam_1 = "B2RhdGFTZXR/AAAAAQAAAA1QdXJjaGFzZSBMaW5lCQQAAOsAAAABMAoAAAAACGJvb2ttYXJrEwAAAAABMQgAAAAAATIRAAAAAAEzEQAAAAABNAgAAAAAATUIAAAAAAE2EQAAAAABNxEAAAAAATgRAAAAAAIxMA8AAAAAAjExEQAAAAACMTIRAAAAAAIxMxEAAAAAAjE1DgAAAAACMTYOAAAAAAIxNw4AAAAAAjE4DgAAAAACMjIOAAAAAAIyMw4AAAAAAjI1DgAAAAACMjcOAAAAAAIyOA4AAAAAAjI5DgAAAAACMzAOAAAAAAIzMQ4AAAAAAjMyAgAAAAACMzQOAAAAAAIzNQ4AAAAAAjM2DgAAAAACMzcOAAAAAAIzOAgAAAAAAjQwEQAAAAACNDERAAAAAAI0NREAAAAAAjU0DgAAAAACNTYCAAAAAAI1Nw4AAAAAAjU4DgAAAAACNTkOAAAAAAI2MA4AAAAAAjYxDgAAAAACNjMRAAAAAAI2NAgAAAAAAjY3DgAAAAACNjgRAAAAAAI2OQ4AAAAAAjcwEQAAAAACNzERAAAAAAI3MggAAAAAAjczAgAAAAACNzQRAAAAAAI3NREAAAAAAjc3CAAAAAACNzgRAAAAAAI3OREAAAAAAjgwCAAAAAACODERAAAAAAI4MhEAAAAAAjgzEQAAAAACODURAAAAAAI4NgIAAAAAAjg3EQAAAAACODgCAAAAAAI4OREAAAAAAjkwEQAAAAACOTERAAAAAAI5Mg4AAAAAAjkzDgAAAAACOTUOAAAAAAI5NxEAAAAAAjk4CAAAAAACOTkOAAAAAAMxMDAOAAAAAAMxMDECAAAAAAMxMDMOAAAAAAMxMDQOAAAAAAMxMDUOAAAAAAMxMDYRAAAAAAMxMDcIAAAAAAMxMDgRAAAAAAMxMDkOAAAAAAMxMTAOAAAAAAMxMTEOAAAAAAMxMTIOAAAAAAMxMTMOAAAAAAMxMTQOAAAAAAMxMTUOAAAAAAMxMTYIAAAAAAMxMTcRAAAAAAMxMTgRAAAAAAMxMTkCAAAAAAMxMjARAAAAAAMxMjEOAAAAAAMxMjIOAAAAAAMxMjMCAAAAAAMxMjQOAAAAAAMxMjkOAAAAAAMxMzARAAAAAAMxMzIOAAAAAAMxMzUOAAAAAAMxMzYOAAAAAAMxMzcOAAAAAAMxNDAOAAAAAAMxNDEOAAAAAAM0ODAIAAAAAAQxMDAxEQAAAAAEMTAwMggAAAAABDEwMDMOAAAAAAQxMDA0DgAAAAAEMTAwNQ4AAAAABDEwMDYOAAAAAAQxMDA3DgAAAAAEMTAwOA4AAAAABDEwMDkOAAAAAAQxMDEwDgAAAAAEMTAxMQ4AAAAABDEwMTIOAAAAAAQxMDEzEQAAAAAEMTAxOQgAAAAABDEwMzAOAAAAAAQxMDMxDgAAAAAEMTcwMBEAAAAABDE3MDIPAAAAAAQ1NDAxEQAAAAAENTQwMhEAAAAABDU0MDMRAAAAAAQ1NDA0DgAAAAAENTQwNxEAAAAABDU0MTUOAAAAAAQ1NDE2DgAAAAAENTQxNw4AAAAABDU0MTgOAAAAAAQ1NDU4DgAAAAAENTQ2MA4AAAAABDU0NjEOAAAAAAQ1NDk1DgAAAAAENTYwMA8AAAAABDU2MDEIAAAAAAQ1NjAyEQAAAAAENTYwMw4AAAAABDU2MDUCAAAAAAQ1NjA2AgAAAAAENTYwOREAAAAABDU2MTARAAAAAAQ1NjExEQAAAAAENTYxMhEAAAAABDU2MTMCAAAAAAQ1NzAwEQAAAAAENTcwNREAAAAABDU3MDYRAAAAAAQ1NzA3CAAAAAAENTcwOBEAAAAABDU3MDkRAAAAAAQ1NzEwAgAAAAAENTcxMREAAAAABDU3MTIRAAAAAAQ1NzEzAgAAAAAENTcxNBEAAAAABDU3MTUIAAAAAAQ1NzUwDgAAAAAENTc1MgIAAAAABDU3OTAPAAAAAAQ1NzkxDwAAAAAENTc5MhEAAAAABDU3OTMRAAAAAAQ1Nzk0DwAAAAAENTc5NQ8AAAAABDU4MDACAAAAAAQ1ODAxDgAAAAAENTgwMg4AAAAABDU4MDMOAAAAAAQ1ODA0DgAAAAAENTgwNQ4AAAAABDU4MDYOAAAAAAQ1ODA3DgAAAAAENTgwOA4AAAAABDU4MDkOAAAAAAQ1ODEwDgAAAAAENjYwMBEAAAAABDY2MDEIAAAAAAQ2NjA4EQAAAAAENjYwOQgAAAAABDY2MTACAAAAAAUxMjQwMBEAAAAABTEyNDAxCAAAAAAFMTI0MDIPAAAAAAUxMjQwMxEAAAAABTEyNDA0EQAAAAAFMTI0MDURAAAAAAUxMjQzMA4AAAAABTEyNDMxDgAAAAAFMTI0ODUCAAAAAAUxMjQ4NhEAAAAABTEyNDg3AgAAAAAFMTI0OTARAAAAAAUxNzMwMBEAAAAACDk5MDAwNzUwEQAAAAAIOTkwMDA3NTERAAAAAAg5OTAwMDc1MhEAAAAACDk5MDAwNzUzAgAAAAAIOTkwMDA3NTQIAAAAAAg5OTAwMDc1NQ4AAAAACDk5MDAwNzU2AgAAAAAIOTkwMDA3NTcIAAAAAAg5OTAwMDc1OBEAAAAACDk5MDAwNzU5CAAAAAAVQ29udHJvbDEyMTAwMzFfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwMzdfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwMzlfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwNDFfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwNDNfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwNDVfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwNDdfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwNDlfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwNTNfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwNTdfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwNTlfRm9ybWF0EQAAAAAOQ29udHJvbDEyMTAwOTERAAAAAA5Db250cm9sMTIxMDA5MxEAAAAADkNvbnRyb2wxMjEwMDk1EQAAAAAOQ29udHJvbDEyMTAwOTcRAAAAAA5Db250cm9sMTIxMDA5OREAAAAADkNvbnRyb2wxMjEwMTAxEQAAAAAdQ29udHJvbDEyMTAwMDdfRHluYW1pY0NhcHRpb24RAAAAAB1Db250cm9sMTIxMDAzN19EeW5hbWljQ2FwdGlvbhEAAAAAHUNvbnRyb2wxMjEwMDQ1X0R5bmFtaWNDYXB0aW9uEQAAAAAdQ29udHJvbDEyMTAwODdfRHluYW1pY0NhcHRpb24RAAAAAB1Db250cm9sMTIxMDA4OV9EeW5hbWljQ2FwdGlvbhEAAAAAHUNvbnRyb2wxMjEwMDkxX0R5bmFtaWNDYXB0aW9uEQAAAAAdQ29udHJvbDEyMTAwOTNfRHluYW1pY0NhcHRpb24RAAAAAB1Db250cm9sMTIxMDA5NV9EeW5hbWljQ2FwdGlvbhEAAAAAHUNvbnRyb2wxMjEwMDk3X0R5bmFtaWNDYXB0aW9uEQAAAAAdQ29udHJvbDEyMTAwOTlfRHluYW1pY0NhcHRpb24RAAAAAB1Db250cm9sMTIxMDEwMV9EeW5hbWljQ2FwdGlvbhEAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=";
            string iam_2 = "B2RhdGFTZXR/AAAAAQAAAA1QdXJjaGFzZSBMaW5lCQQAAOsAAAABMAoAAAAACGJvb2ttYXJrEwAAAAABMQgAAAAAATIRAAAAAAEzEQAAAAABNAgAAAAAATUIAAAAAAE2EQAAAAABNxEAAAAAATgRAAAAAAIxMA8AAAAAAjExEQAAAAACMTIRAAAAAAIxMxEAAAAAAjE1DgAAAAACMTYOAAAAAAIxNw4AAAAAAjE4DgAAAAACMjIOAAAAAAIyMw4AAAAAAjI1DgAAAAACMjcOAAAAAAIyOA4AAAAAAjI5DgAAAAACMzAOAAAAAAIzMQ4AAAAAAjMyAgAAAAACMzQOAAAAAAIzNQ4AAAAAAjM2DgAAAAACMzcOAAAAAAIzOAgAAAAAAjQwEQAAAAACNDERAAAAAAI0NREAAAAAAjU0DgAAAAACNTYCAAAAAAI1Nw4AAAAAAjU4DgAAAAACNTkOAAAAAAI2MA4AAAAAAjYxDgAAAAACNjMRAAAAAAI2NAgAAAAAAjY3DgAAAAACNjgRAAAAAAI2OQ4AAAAAAjcwEQAAAAACNzERAAAAAAI3MggAAAAAAjczAgAAAAACNzQRAAAAAAI3NREAAAAAAjc3CAAAAAACNzgRAAAAAAI3OREAAAAAAjgwCAAAAAACODERAAAAAAI4MhEAAAAAAjgzEQAAAAACODURAAAAAAI4NgIAAAAAAjg3EQAAAAACODgCAAAAAAI4OREAAAAAAjkwEQAAAAACOTERAAAAAAI5Mg4AAAAAAjkzDgAAAAACOTUOAAAAAAI5NxEAAAAAAjk4CAAAAAACOTkOAAAAAAMxMDAOAAAAAAMxMDECAAAAAAMxMDMOAAAAAAMxMDQOAAAAAAMxMDUOAAAAAAMxMDYRAAAAAAMxMDcIAAAAAAMxMDgRAAAAAAMxMDkOAAAAAAMxMTAOAAAAAAMxMTEOAAAAAAMxMTIOAAAAAAMxMTMOAAAAAAMxMTQOAAAAAAMxMTUOAAAAAAMxMTYIAAAAAAMxMTcRAAAAAAMxMTgRAAAAAAMxMTkCAAAAAAMxMjARAAAAAAMxMjEOAAAAAAMxMjIOAAAAAAMxMjMCAAAAAAMxMjQOAAAAAAMxMjkOAAAAAAMxMzARAAAAAAMxMzIOAAAAAAMxMzUOAAAAAAMxMzYOAAAAAAMxMzcOAAAAAAMxNDAOAAAAAAMxNDEOAAAAAAM0ODAIAAAAAAQxMDAxEQAAAAAEMTAwMggAAAAABDEwMDMOAAAAAAQxMDA0DgAAAAAEMTAwNQ4AAAAABDEwMDYOAAAAAAQxMDA3DgAAAAAEMTAwOA4AAAAABDEwMDkOAAAAAAQxMDEwDgAAAAAEMTAxMQ4AAAAABDEwMTIOAAAAAAQxMDEzEQAAAAAEMTAxOQgAAAAABDEwMzAOAAAAAAQxMDMxDgAAAAAEMTcwMBEAAAAABDE3MDIPAAAAAAQ1NDAxEQAAAAAENTQwMhEAAAAABDU0MDMRAAAAAAQ1NDA0DgAAAAAENTQwNxEAAAAABDU0MTUOAAAAAAQ1NDE2DgAAAAAENTQxNw4AAAAABDU0MTgOAAAAAAQ1NDU4DgAAAAAENTQ2MA4AAAAABDU0NjEOAAAAAAQ1NDk1DgAAAAAENTYwMA8AAAAABDU2MDEIAAAAAAQ1NjAyEQAAAAAENTYwMw4AAAAABDU2MDUCAAAAAAQ1NjA2AgAAAAAENTYwOREAAAAABDU2MTARAAAAAAQ1NjExEQAAAAAENTYxMhEAAAAABDU2MTMCAAAAAAQ1NzAwEQAAAAAENTcwNREAAAAABDU3MDYRAAAAAAQ1NzA3CAAAAAAENTcwOBEAAAAABDU3MDkRAAAAAAQ1NzEwAgAAAAAENTcxMREAAAAABDU3MTIRAAAAAAQ1NzEzAgAAAAAENTcxNBEAAAAABDU3MTUIAAAAAAQ1NzUwDgAAAAAENTc1MgIAAAAABDU3OTAPAAAAAAQ1NzkxDwAAAAAENTc5MhEAAAAABDU3OTMRAAAAAAQ1Nzk0DwAAAAAENTc5NQ8AAAAABDU4MDACAAAAAAQ1ODAxDgAAAAAENTgwMg4AAAAABDU4MDMOAAAAAAQ1ODA0DgAAAAAENTgwNQ4AAAAABDU4MDYOAAAAAAQ1ODA3DgAAAAAENTgwOA4AAAAABDU4MDkOAAAAAAQ1ODEwDgAAAAAENjYwMBEAAAAABDY2MDEIAAAAAAQ2NjA4EQAAAAAENjYwOQgAAAAABDY2MTACAAAAAAUxMjQwMBEAAAAABTEyNDAxCAAAAAAFMTI0MDIPAAAAAAUxMjQwMxEAAAAABTEyNDA0EQAAAAAFMTI0MDURAAAAAAUxMjQzMA4AAAAABTEyNDMxDgAAAAAFMTI0ODUCAAAAAAUxMjQ4NhEAAAAABTEyNDg3AgAAAAAFMTI0OTARAAAAAAUxNzMwMBEAAAAACDk5MDAwNzUwEQAAAAAIOTkwMDA3NTERAAAAAAg5OTAwMDc1MhEAAAAACDk5MDAwNzUzAgAAAAAIOTkwMDA3NTQIAAAAAAg5OTAwMDc1NQ4AAAAACDk5MDAwNzU2AgAAAAAIOTkwMDA3NTcIAAAAAAg5OTAwMDc1OBEAAAAACDk5MDAwNzU5CAAAAAAVQ29udHJvbDEyMTAwMzFfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwMzdfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwMzlfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwNDFfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwNDNfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwNDVfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwNDdfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwNDlfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwNTNfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwNTdfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwNTlfRm9ybWF0EQAAAAAOQ29udHJvbDEyMTAwOTERAAAAAA5Db250cm9sMTIxMDA5MxEAAAAADkNvbnRyb2wxMjEwMDk1EQAAAAAOQ29udHJvbDEyMTAwOTcRAAAAAA5Db250cm9sMTIxMDA5OREAAAAADkNvbnRyb2wxMjEwMTAxEQAAAAAdQ29udHJvbDEyMTAwMDdfRHluYW1pY0NhcHRpb24RAAAAAB1Db250cm9sMTIxMDAzN19EeW5hbWljQ2FwdGlvbhEAAAAAHUNvbnRyb2wxMjEwMDQ1X0R5bmFtaWNDYXB0aW9uEQAAAAAdQ29udHJvbDEyMTAwODdfRHluYW1pY0NhcHRpb24RAAAAAB1Db250cm9sMTIxMDA4OV9EeW5hbWljQ2FwdGlvbhEAAAAAHUNvbnRyb2wxMjEwMDkxX0R5bmFtaWNDYXB0aW9uEQAAAAAdQ29udHJvbDEyMTAwOTNfRHluYW1pY0NhcHRpb24RAAAAAB1Db250cm9sMTIxMDA5NV9EeW5hbWljQ2FwdGlvbhEAAAAAHUNvbnRyb2wxMjEwMDk3X0R5bmFtaWNDYXB0aW9uEQAAAAAdQ29udHJvbDEyMTAwOTlfRHluYW1pY0NhcHRpb24RAAAAAB1Db250cm9sMTIxMDEwMV9EeW5hbWljQ2FwdGlvbhEAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=";
            string iam_3 = "B2RhdGFTZXR/AAAAAQAAAA1QdXJjaGFzZSBMaW5lCQQAAOsAAAABMAoAAAAACGJvb2ttYXJrEwAAAAABMQgAAAAAATIRAAAAAAEzEQAAAAABNAgAAAAAATUIAAAAAAE2EQAAAAABNxEAAAAAATgRAAAAAAIxMA8AAAAAAjExEQAAAAACMTIRAAAAAAIxMxEAAAAAAjE1DgAAAAACMTYOAAAAAAIxNw4AAAAAAjE4DgAAAAACMjIOAAAAAAIyMw4AAAAAAjI1DgAAAAACMjcOAAAAAAIyOA4AAAAAAjI5DgAAAAACMzAOAAAAAAIzMQ4AAAAAAjMyAgAAAAACMzQOAAAAAAIzNQ4AAAAAAjM2DgAAAAACMzcOAAAAAAIzOAgAAAAAAjQwEQAAAAACNDERAAAAAAI0NREAAAAAAjU0DgAAAAACNTYCAAAAAAI1Nw4AAAAAAjU4DgAAAAACNTkOAAAAAAI2MA4AAAAAAjYxDgAAAAACNjMRAAAAAAI2NAgAAAAAAjY3DgAAAAACNjgRAAAAAAI2OQ4AAAAAAjcwEQAAAAACNzERAAAAAAI3MggAAAAAAjczAgAAAAACNzQRAAAAAAI3NREAAAAAAjc3CAAAAAACNzgRAAAAAAI3OREAAAAAAjgwCAAAAAACODERAAAAAAI4MhEAAAAAAjgzEQAAAAACODURAAAAAAI4NgIAAAAAAjg3EQAAAAACODgCAAAAAAI4OREAAAAAAjkwEQAAAAACOTERAAAAAAI5Mg4AAAAAAjkzDgAAAAACOTUOAAAAAAI5NxEAAAAAAjk4CAAAAAACOTkOAAAAAAMxMDAOAAAAAAMxMDECAAAAAAMxMDMOAAAAAAMxMDQOAAAAAAMxMDUOAAAAAAMxMDYRAAAAAAMxMDcIAAAAAAMxMDgRAAAAAAMxMDkOAAAAAAMxMTAOAAAAAAMxMTEOAAAAAAMxMTIOAAAAAAMxMTMOAAAAAAMxMTQOAAAAAAMxMTUOAAAAAAMxMTYIAAAAAAMxMTcRAAAAAAMxMTgRAAAAAAMxMTkCAAAAAAMxMjARAAAAAAMxMjEOAAAAAAMxMjIOAAAAAAMxMjMCAAAAAAMxMjQOAAAAAAMxMjkOAAAAAAMxMzARAAAAAAMxMzIOAAAAAAMxMzUOAAAAAAMxMzYOAAAAAAMxMzcOAAAAAAMxNDAOAAAAAAMxNDEOAAAAAAM0ODAIAAAAAAQxMDAxEQAAAAAEMTAwMggAAAAABDEwMDMOAAAAAAQxMDA0DgAAAAAEMTAwNQ4AAAAABDEwMDYOAAAAAAQxMDA3DgAAAAAEMTAwOA4AAAAABDEwMDkOAAAAAAQxMDEwDgAAAAAEMTAxMQ4AAAAABDEwMTIOAAAAAAQxMDEzEQAAAAAEMTAxOQgAAAAABDEwMzAOAAAAAAQxMDMxDgAAAAAEMTcwMBEAAAAABDE3MDIPAAAAAAQ1NDAxEQAAAAAENTQwMhEAAAAABDU0MDMRAAAAAAQ1NDA0DgAAAAAENTQwNxEAAAAABDU0MTUOAAAAAAQ1NDE2DgAAAAAENTQxNw4AAAAABDU0MTgOAAAAAAQ1NDU4DgAAAAAENTQ2MA4AAAAABDU0NjEOAAAAAAQ1NDk1DgAAAAAENTYwMA8AAAAABDU2MDEIAAAAAAQ1NjAyEQAAAAAENTYwMw4AAAAABDU2MDUCAAAAAAQ1NjA2AgAAAAAENTYwOREAAAAABDU2MTARAAAAAAQ1NjExEQAAAAAENTYxMhEAAAAABDU2MTMCAAAAAAQ1NzAwEQAAAAAENTcwNREAAAAABDU3MDYRAAAAAAQ1NzA3CAAAAAAENTcwOBEAAAAABDU3MDkRAAAAAAQ1NzEwAgAAAAAENTcxMREAAAAABDU3MTIRAAAAAAQ1NzEzAgAAAAAENTcxNBEAAAAABDU3MTUIAAAAAAQ1NzUwDgAAAAAENTc1MgIAAAAABDU3OTAPAAAAAAQ1NzkxDwAAAAAENTc5MhEAAAAABDU3OTMRAAAAAAQ1Nzk0DwAAAAAENTc5NQ8AAAAABDU4MDACAAAAAAQ1ODAxDgAAAAAENTgwMg4AAAAABDU4MDMOAAAAAAQ1ODA0DgAAAAAENTgwNQ4AAAAABDU4MDYOAAAAAAQ1ODA3DgAAAAAENTgwOA4AAAAABDU4MDkOAAAAAAQ1ODEwDgAAAAAENjYwMBEAAAAABDY2MDEIAAAAAAQ2NjA4EQAAAAAENjYwOQgAAAAABDY2MTACAAAAAAUxMjQwMBEAAAAABTEyNDAxCAAAAAAFMTI0MDIPAAAAAAUxMjQwMxEAAAAABTEyNDA0EQAAAAAFMTI0MDURAAAAAAUxMjQzMA4AAAAABTEyNDMxDgAAAAAFMTI0ODUCAAAAAAUxMjQ4NhEAAAAABTEyNDg3AgAAAAAFMTI0OTARAAAAAAUxNzMwMBEAAAAACDk5MDAwNzUwEQAAAAAIOTkwMDA3NTERAAAAAAg5OTAwMDc1MhEAAAAACDk5MDAwNzUzAgAAAAAIOTkwMDA3NTQIAAAAAAg5OTAwMDc1NQ4AAAAACDk5MDAwNzU2AgAAAAAIOTkwMDA3NTcIAAAAAAg5OTAwMDc1OBEAAAAACDk5MDAwNzU5CAAAAAAVQ29udHJvbDEyMTAwMzFfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwMzdfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwMzlfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwNDFfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwNDNfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwNDVfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwNDdfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwNDlfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwNTNfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwNTdfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwNTlfRm9ybWF0EQAAAAAOQ29udHJvbDEyMTAwOTERAAAAAA5Db250cm9sMTIxMDA5MxEAAAAADkNvbnRyb2wxMjEwMDk1EQAAAAAOQ29udHJvbDEyMTAwOTcRAAAAAA5Db250cm9sMTIxMDA5OREAAAAADkNvbnRyb2wxMjEwMTAxEQAAAAAdQ29udHJvbDEyMTAwMDdfRHluYW1pY0NhcHRpb24RAAAAAB1Db250cm9sMTIxMDAzN19EeW5hbWljQ2FwdGlvbhEAAAAAHUNvbnRyb2wxMjEwMDQ1X0R5bmFtaWNDYXB0aW9uEQAAAAAdQ29udHJvbDEyMTAwODdfRHluYW1pY0NhcHRpb24RAAAAAB1Db250cm9sMTIxMDA4OV9EeW5hbWljQ2FwdGlvbhEAAAAAHUNvbnRyb2wxMjEwMDkxX0R5bmFtaWNDYXB0aW9uEQAAAAAdQ29udHJvbDEyMTAwOTNfRHluYW1pY0NhcHRpb24RAAAAAB1Db250cm9sMTIxMDA5NV9EeW5hbWljQ2FwdGlvbhEAAAAAHUNvbnRyb2wxMjEwMDk3X0R5bmFtaWNDYXB0aW9uEQAAAAAdQ29udHJvbDEyMTAwOTlfRHluYW1pY0NhcHRpb24RAAAAAB1Db250cm9sMTIxMDEwMV9EeW5hbWljQ2FwdGlvbhEAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=";
            string cf_1 = "Ck5ld0RhdGFTZXR/AAAAAQAAAAEwCQQAAKsAAAAIYm9va21hcmsTAAAAAAEwCgAAAAABMREAAAAAATIRAAAAAAEzEQAAAAABNBEAAAAAATURAAAAAAE2EQAAAAABNxEAAAAAATgRAAAAAAE5EQAAAAACMTARAAAAAAIxNBEAAAAAAjE1EQAAAAACMTYRAAAAAAIxNxEAAAAAAjE5DgAAAAACMjERAAAAAAIyMhEAAAAAAjI0EQAAAAACMjYIAAAAAAIyNxEAAAAAAjI4EQAAAAACMjkRAAAAAAIzMBEAAAAAAjMxEQAAAAACMzMRAAAAAAIzNREAAAAAAjM5CAAAAAACNDURAAAAAAI0NggAAAAAAjQ3EQAAAAACNTMPAAAAAAI1NA8AAAAAAjgwCAAAAAACODICAAAAAAI4NBEAAAAAAjg1EQAAAAACODYRAAAAAAI4OBEAAAAAAjg5EwAAAAACOTARAAAAAAI5MREAAAAAAjkyEQAAAAADMTAyEQAAAAADMTAzEQAAAAADMTA3EQAAAAADMTA4EQAAAAADMTA5AgAAAAADMTEwEQAAAAADMTE2AgAAAAADMTE5EQAAAAADMTI0DgAAAAADMTMyCAAAAAADMTQwFAAAAAADMTUwAgAAAAADMTYwAgAAAAADMTcwEQAAAAADMjg4EQAAAAADODQwEQAAAAAENTA0OREAAAAABDU3MDARAAAAAAQ1NzAxEQAAAAAENTc5MBEAAAAABDc2MDARAAAAAAQ3NjAxEQAAAAAENzYwMgIAAAAABDgwMDASAAAAAAQ4MDAxEgAAAAAEODAwMhIAAAAABDgwMDMSAAAAAAUxMjQwMBEAAAAABTEyNDAxEQAAAAAFMTI0MDIRAAAAAAUxMjQwMxEAAAAABTEyNDA1EQAAAAAFMTI0MDYRAAAAAAUxMjQwOREAAAAABTEyNDEwAgAAAAAFMTI0MTERAAAAAAUxMjQxMggAAAAABTEyNDEzCAAAAAAFMTI0MTQRAAAAAAUxMjQzMggAAAAABTEyNDgwEQAAAAAFMTI0ODERAAAAAAUxMjQ5MAgAAAAABTEyNDk0EQAAAAACNTUPAAAAAAI1NhEAAAAAAjU3EQAAAAADMTExEQAAAAAFMTI0MjURAAAAAAUxMjQyNg8AAAAABTEyNDkxEQAAAAACMzgCAAAAAAI1OA4AAAAAAjU5DgAAAAACNjAOAAAAAAI2MQ4AAAAAAjYyDgAAAAACNjQOAAAAAAI2NQ4AAAAAAjY2DgAAAAACNjcOAAAAAAI2OQ4AAAAAAjcwDgAAAAACNzEOAAAAAAI3Mg4AAAAAAjc0DgAAAAACNzUOAAAAAAI3Ng4AAAAAAjc3DgAAAAACNzgOAAAAAAI3OQ4AAAAAAjk3DgAAAAACOTgOAAAAAAI5OQ4AAAAAAzEwMA4AAAAAAzEwNA4AAAAAAzEwNQ4AAAAAAzExMw4AAAAAAzExNA4AAAAAAzExNw4AAAAAAzExOA4AAAAAAzEyMA4AAAAAAzEyMQ4AAAAAAzEyMg4AAAAAAzEyMw4AAAAAAzEyNQ4AAAAAAzEyNg4AAAAAAzEzMAgAAAAAAzEzMQgAAAAABDcxNzcIAAAAAAQ3MTc4CAAAAAAENzE3OQgAAAAABDcxODAIAAAAAAQ3MTgxCAAAAAAENzE4MggAAAAABDcxODMIAAAAAAQ3MTg0CAAAAAAENzE4NQgAAAAABDcxODYIAAAAAAQ3MTg3CAAAAAAENzE4OAgAAAAABDcxODkIAAAAAAQ3MTkwCAAAAAAENzE5MQgAAAAABDcxOTIIAAAAAAQ3MTkzCAAAAAAENzE5NAgAAAAABDcxOTUIAAAAAAQ3MTk2CAAAAAAENzE5NwgAAAAABDcxOTgIAAAAAAUxMjQwNBEAAAAABTEyNDI3DgAAAAAFMTI0MjgOAAAAAAUxMjQyOQ4AAAAABTEyNDMwDgAAAAAFMTI0MzEOAAAAABtTb2NpYWxMaXN0ZW5pbmdTZXR1cFZpc2libGUCAAAAABZTb2NpYWxMaXN0ZW5pbmdWaXNpYmxlAgAAAAAYT3BlbkFwcHJvdmFsRW50cmllc0V4aXN0AgAAAAAaQ2FuQ2FuY2VsQXBwcm92YWxGb3JSZWNvcmQCAAAAAA5Qb3dlckJJVmlzaWJsZQIAAAAADVJlc3luY1Zpc2libGUCAAAAABlDYW5SZXF1ZXN0QXBwcm92YWxGb3JGbG93AgAAAAAYQ2FuQ2FuY2VsQXBwcm92YWxGb3JGbG93AgAAAAAQQ29udHJvbDMyX0Zvcm1hdBEAAAAAEENvbnRyb2wzNF9Gb3JtYXQRAAAAAAEAAAACFQAAABcAAAACewU2ADIAMAAwADAAAAAAAAJu6QgAAAAAAAIFNjIwMDACH9CX0JDQniAi0KHQv9C+0YDRgtC80LDRgdGC0LXRgCICH9CX0JDQniAi0KHQn9Ce0KDQotCc0JDQodCi0JXQoCICAAIi0YPQuy4g0JHQvtGC0LDQvdC40YfQtdGB0LrQsNGPLCA0NAIAAgzQnNC+0YHQutCy0LACAAIAAgACAAIAAgACAAIAAAAAAAAAAAAAAAAAAAAAAgc2MC0xMDEwAgACAAIAAAAAAgTQndCfAgACBNCS0JUCEtCh0KIu0Jgg0KTQoNCQ0KXQogIAAgU2MjAwMAIAAgAAAAACAAIDAAAAAgACgCvjUDst1wgBAAAAAgAAQwDdLNcIAgAAAAIAAAAAAgACAAIAAgACDNCR0JjQl9Cd0JXQoQACAAIGMTAzMDU0AgACAAIAAgACAAIAAg7Qn9Ce0JrQo9Cf0JrQkAIAAgACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAgEAAAAAAgACAAIAAgACAAIAAgzQnNCe0KHQmtCS0JACCtCR0JXQm9Cr0JkCAAIAAgACAAJZjbo/4WEPQISpaIdh4YfYAgAAAAAAAAAAAAAAAAAAAAACL87I70jmXk6sfXy+RoMLVQIAAAAAAAAAAAAAAAAAAAAAAgACAAIAAgACAAIAAgACAAIAAgAAAAACAAAAAAIAAgAAAAACAAIAAgAAAAACCdCf0J7Qmi0wMgAAAAAAAAACAAIAAAAAAAAAAAAAAAAAAAAAAjQMWwQAAAAAAAAAAAAAAQACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACNAxbBAAAAAAAAAAAAAABAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAIAAAAAAgAAAAACAAAAAAIAAAAAAgAAAAACAAAAAAIAAAAAAgAAAAACAAAAAAIAAAAAAgAAAAACAAAAAAIAAAAAAgAAAAACAAAAAAIAAAAAAgAAAAACAAAAAAIAAAAAAgAAAAACAAAAAAIAAAAAAgAAAAACAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAIAAgACAAIBAgACAAIAAggjLCMjMC4wMAIIIywjIzAuMDA=";
            string vf_1 = "B2RhdGFTZXR/AAAAAQAAAA9QdXJjaGFzZSBIZWFkZXIJBAAAswAAAAEwCgAAAAAIYm9va21hcmsTAAAAAAExCAAAAAABMhEAAAAAATMRAAAAAAE0EQAAAAABNREAAAAAATYRAAAAAAE3EQAAAAABOBEAAAAAATkRAAAAAAIxMBEAAAAAAjExEQAAAAACMTIRAAAAAAIxMxEAAAAAAjE0EQAAAAACMTURAAAAAAIxNhEAAAAAAjE3EQAAAAACMTgRAAAAAAIxOQ8AAAAAAjIwDwAAAAACMjEPAAAAAAIyMhEAAAAAAjIzEQAAAAACMjQPAAAAAAIyNQ4AAAAAAjI2DwAAAAACMjcRAAAAAAIyOBEAAAAAAjI5EQAAAAACMzARAAAAAAIzMREAAAAAAjMyEQAAAAACMzMOAAAAAAIzNQIAAAAAAjM3EQAAAAACNDERAAAAAAI0MxEAAAAAAjQ1EQAAAAACNDYCAAAAAAI0NwgAAAAAAjUxEQAAAAACNTIIAAAAAAI1MxEAAAAAAjU1EQAAAAACNTYCAAAAAAI1NwIAAAAAAjU4AgAAAAACNTkCAAAAAAI2MA4AAAAAAjYxDgAAAAACNjIRAAAAAAI2MxEAAAAAAjY0EQAAAAACNjURAAAAAAI2NhEAAAAAAjY3EQAAAAACNjgRAAAAAAI2OREAAAAAAjcwEQAAAAACNzIRAAAAAAI3MxEAAAAAAjc0EQAAAAACNzYRAAAAAAI3NxEAAAAAAjc4EQAAAAACNzkRAAAAAAI4MBEAAAAAAjgxEQAAAAACODIRAAAAAAI4MxEAAAAAAjg0EQAAAAACODURAAAAAAI4NhEAAAAAAjg3EQAAAAACODgRAAAAAAI4OREAAAAAAjkwEQAAAAACOTERAAAAAAI5MhEAAAAAAjkzEQAAAAACOTQIAAAAAAI5NREAAAAAAjk3EQAAAAACOTgCAAAAAAI5OQ8AAAAAAzEwMREAAAAAAzEwMhEAAAAAAzEwNBEAAAAAAzEwNxEAAAAAAzEwOBEAAAAAAzEwOREAAAAAAzExNBEAAAAAAzExNQIAAAAAAzExNhEAAAAAAzExOBEAAAAAAzExOQ4AAAAAAzEyMAgAAAAAAzEyMQgAAAAAAzEyMg4AAAAAAzEyMwIAAAAAAzEyNAgAAAAAAzEyNREAAAAAAzEyNhEAAAAAAzEyOQgAAAAAAzEzMBEAAAAAAzEzMREAAAAAAzEzMhEAAAAAAzEzMxEAAAAAAzEzNA4AAAAAAzEzNREAAAAAAzEzNgIAAAAAAzEzNw8AAAAAAzEzOBEAAAAAAzEzOREAAAAAAzE0Mg8AAAAAAzE0MxEAAAAAAzE0NA4AAAAAAzE1MREAAAAAAzE2MAgAAAAAAzE2MRIAAAAAAzE2NQgAAAAAAzE3MBEAAAAAAzE3MREAAAAAAzMwMA4AAAAAAzMwMQ4AAAAAAzQ4MAgAAAAABDEzMDUOAAAAAAQ1MDQzCAAAAAAENTA0OAgAAAAABDUwNTARAAAAAAQ1MDUyEQAAAAAENTA1MxEAAAAABDU3MDARAAAAAAQ1NzUxAgAAAAAENTc1MgIAAAAABDU3NTMIAAAAAAQ1NzkwDwAAAAAENTc5MQ8AAAAABDU3OTIRAAAAAAQ1NzkzEQAAAAAENTgwMBEAAAAABDU4MDERAAAAAAQ1ODAyEQAAAAAENTgwMwIAAAAABDU4MDQRAAAAAAQ4MDAwEgAAAAAEOTAwMBEAAAAABDkwMDEIAAAAAAUxMjQwMAIAAAAABTEyNDAxEQAAAAAFMTI0MDIRAAAAAAUxMjQwMwgAAAAABTEyNDA0AgAAAAAFMTI0MzcIAAAAAAUxMjQzOAgAAAAABTEyNDQwAgAAAAAFMTI0NDEIAAAAAAUxMjQ0MhEAAAAABTEyNDQzCAAAAAAFMTI0NDQRAAAAAAUxMjQ0NREAAAAABTEyNDQ2CAAAAAAFMTI0NDcRAAAAAAUxMjQ3MBEAAAAABTEyNDcxDwAAAAAFMTI0NzIPAAAAAAUxMjQ3Mw8AAAAABTEyNDc0EQAAAAAFMTI0ODAOAAAAAAUxMjQ4NREAAAAABTEyNDg2AgAAAAAFMTI0OTARAAAAAAUxMjQ5MREAAAAABTEyNDk4AgAAAAAFMTI0OTkPAAAAAAQ1NzU0EQAAAAAENTc5NhEAAAAAAgAAAAKpmg0AAAAAAAIrAAAAJgAAAACLAgAAAAJ7/x8EHgQQBBIELQAyADEALQAwADAAMAAzADQAAAAAAAICAAAAAgACEdCf0J7QkNCSLTIxLTAwMDM0AgACAAIAAgACAAIAAgACAAIAAhpDUk9OVVMg0KDQvtGB0YHQuNGPINCX0JDQngIAAgvQoNC40L3QsywgNQIAAgzQnNC+0YHQutCy0LACAAIAQABTjcHYCAIAAAACAEAAU43B2AgCAAAAAgBAAFONwdgIAgAAAAIZSW52b2ljZSDQn9Ce0JDQki0yMS0wMDAzNAIAAgAAAAAAAAAAAgAAAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAgAAAAIAAgACAAIAAgACAAIAAAAAAAAAAAAAAAAAAAAAAgACAAIAAgACAAIAAgAAAAACAAIAAAAAAgACAAIAAgACAAIAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAIR0J/QntCQ0JItMjEtMDAwMzQCEdCf0J7QkNCSLTIxLTAwMDM0AgACAAIAAgACEdCf0J7QkNCSLTIxLTAwMDM0AgACAAIAAgACAAIAAgACAAIFNjIwMDACAAIAAgACAAIAAgACAAIAAgACAAIAAgYxMDMwNTQCAAICUlUCAAAAAAIAAgACAAIAQABTjcHYCAIAAAACAAIAAgACCdCf0J7Qmi0yMAIJ0J/QntCaLTIwAgnQn9Ce0JotMTUCAAIAAgACAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAACAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgACAAAAAAIAAgACAAAAAAIAAgACAAIAAgAAAAAAAAAAAAAAAAAAAAACAAIBAgAAAAAAAAAAAgAAAAIAAgACAAAAAAAAAAACAAAAAgACAAAAAAAAAAAAAAAAAAAAAAIAAgAAAAACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAgACAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAACAQAAAAIAAgACAAIAAgACAAIAAAAAAgAAAAAAAAAAAgAAAAIAAAAAAAAAAAIAAAACAAIAAgACAAIAAgACAAKs0IGOx9pzSZIoLF1gkGW/AgACAAAAAAIBAgACAAIAAAAAAgACAAAAAAIAAAAAAgACAAAAAAIAAgAAAAACAAIAAgAAAAACAAIAAgAAAAAAAAAAAgAAAAIAAAAAAAAAAAIAAAACAAAAAAAAAAACAAAAAgACAAAAAAAAAAAAAAAAAAAAAAIAAgACAAIAAgACAAAAAAAAAAACAAAAAAACqZoNAAAAAAACKwAAACYAAAAAiwIAAAACe/8fBB4EEAQSBC0AMgAxAC0AMAAwADAAMwA0AAAAAAACAgAAAAIAAhHQn9Ce0JDQki0yMS0wMDAzNAIAAgACAAIAAgACAAIAAgACAAIaQ1JPTlVTINCg0L7RgdGB0LjRjyDQl9CQ0J4CAAIL0KDQuNC90LMsIDUCAAIM0JzQvtGB0LrQstCwAgACAEAAU43B2AgCAAAAAgBAAFONwdgIAgAAAAIAQABTjcHYCAIAAAACGUludm9pY2Ug0J/QntCQ0JItMjEtMDAwMzQCAAIAAAAAAAAAAAIAAAACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAIAAAACAAIAAgACAAIAAgACAAAAAAAAAAAAAAAAAAAAAAIAAgACAAIAAgACAAIAAAAAAgACAAAAAAIAAgACAAIAAgACAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACEdCf0J7QkNCSLTIxLTAwMDM0AhHQn9Ce0JDQki0yMS0wMDAzNAIAAgACAAIAAhHQn9Ce0JDQki0yMS0wMDAzNAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACBjEwMzA1NAIAAgJSVQIAAAAAAgACAAIAAgBAAFONwdgIAgAAAAIAAgACAAIJ0J/QntCaLTIwAgnQn9Ce0JotMjACCdCf0J7Qmi0xNQIAAgACAAIAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAIAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAIAAAAAAgACAAIAAAAAAgACAAIAAgACAAAAAAAAAAAAAAAAAAAAAAIAAgECAAAAAAAAAAACAAAAAgACAAIAAAAAAAAAAAIAAAACAAIAAAAAAAAAAAAAAAAAAAAAAgACAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAACAAIAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAIBAAAAAgACAAIAAgACAAIAAgAAAAACAAAAAAAAAAACAAAAAgAAAAAAAAAAAgAAAAIAAgACAAIAAgACAAIAAqzQgY7H2nNJkigsXWCQZb8CAAIAAAAAAgECAAIAAgAAAAACAAIAAAAAAgAAAAACAAIAAAAAAgACAAAAAAIAAgACAAAAAAIAAgACAAAAAAAAAAACAAAAAgAAAAAAAAAAAgAAAAIAAAAAAAAAAAIAAAACAAIAAAAAAAAAAAAAAAAAAAAAAgACAAIAAgACAAIAAAAAAAAAAAIAAAAAAA==";
            string textDecoded1 = System.Text.Encoding.UTF8.DecodeBase64(iam_1);
            string textDecoded2 = System.Text.Encoding.UTF8.DecodeBase64(iam_2);
            string textDecoded3 = System.Text.Encoding.UTF8.DecodeBase64(iam_3);
            string textDecoded4 = System.Text.Encoding.UTF8.DecodeBase64(cf_1);
            string textDecoded5 = System.Text.Encoding.UTF8.DecodeBase64(vf_1);

            string iam_first = "B2RhdGFTZXR/AAAAAQAAAA9QdXJjaGFzZSBIZWFkZXIJBAAAswAAAAEwCgAAAAAIYm9va21hcmsTAAAAAAExCAAAAAABMhEAAAAAATMRAAAAAAE0EQAAAAABNREAAAAAATYRAAAAAAE3EQAAAAABOBEAAAAAATkRAAAAAAIxMBEAAAAAAjExEQAAAAACMTIRAAAAAAIxMxEAAAAAAjE0EQAAAAACMTURAAAAAAIxNhEAAAAAAjE3EQAAAAACMTgRAAAAAAIxOQ8AAAAAAjIwDwAAAAACMjEPAAAAAAIyMhEAAAAAAjIzEQAAAAACMjQPAAAAAAIyNQ4AAAAAAjI2DwAAAAACMjcRAAAAAAIyOBEAAAAAAjI5EQAAAAACMzARAAAAAAIzMREAAAAAAjMyEQAAAAACMzMOAAAAAAIzNQIAAAAAAjM3EQAAAAACNDERAAAAAAI0MxEAAAAAAjQ1EQAAAAACNDYCAAAAAAI0NwgAAAAAAjUxEQAAAAACNTIIAAAAAAI1MxEAAAAAAjU1EQAAAAACNTYCAAAAAAI1NwIAAAAAAjU4AgAAAAACNTkCAAAAAAI2MA4AAAAAAjYxDgAAAAACNjIRAAAAAAI2MxEAAAAAAjY0EQAAAAACNjURAAAAAAI2NhEAAAAAAjY3EQAAAAACNjgRAAAAAAI2OREAAAAAAjcwEQAAAAACNzIRAAAAAAI3MxEAAAAAAjc0EQAAAAACNzYRAAAAAAI3NxEAAAAAAjc4EQAAAAACNzkRAAAAAAI4MBEAAAAAAjgxEQAAAAACODIRAAAAAAI4MxEAAAAAAjg0EQAAAAACODURAAAAAAI4NhEAAAAAAjg3EQAAAAACODgRAAAAAAI4OREAAAAAAjkwEQAAAAACOTERAAAAAAI5MhEAAAAAAjkzEQAAAAACOTQIAAAAAAI5NREAAAAAAjk3EQAAAAACOTgCAAAAAAI5OQ8AAAAAAzEwMREAAAAAAzEwMhEAAAAAAzEwNBEAAAAAAzEwNxEAAAAAAzEwOBEAAAAAAzEwOREAAAAAAzExNBEAAAAAAzExNQIAAAAAAzExNhEAAAAAAzExOBEAAAAAAzExOQ4AAAAAAzEyMAgAAAAAAzEyMQgAAAAAAzEyMg4AAAAAAzEyMwIAAAAAAzEyNAgAAAAAAzEyNREAAAAAAzEyNhEAAAAAAzEyOQgAAAAAAzEzMBEAAAAAAzEzMREAAAAAAzEzMhEAAAAAAzEzMxEAAAAAAzEzNA4AAAAAAzEzNREAAAAAAzEzNgIAAAAAAzEzNw8AAAAAAzEzOBEAAAAAAzEzOREAAAAAAzE0Mg8AAAAAAzE0MxEAAAAAAzE0NA4AAAAAAzE1MREAAAAAAzE2MAgAAAAAAzE2MRIAAAAAAzE2NQgAAAAAAzE3MBEAAAAAAzE3MREAAAAAAzMwMA4AAAAAAzMwMQ4AAAAAAzQ4MAgAAAAABDEzMDUOAAAAAAQ1MDQzCAAAAAAENTA0OAgAAAAABDUwNTARAAAAAAQ1MDUyEQAAAAAENTA1MxEAAAAABDU3MDARAAAAAAQ1NzUxAgAAAAAENTc1MgIAAAAABDU3NTMIAAAAAAQ1NzkwDwAAAAAENTc5MQ8AAAAABDU3OTIRAAAAAAQ1NzkzEQAAAAAENTgwMBEAAAAABDU4MDERAAAAAAQ1ODAyEQAAAAAENTgwMwIAAAAABDU4MDQRAAAAAAQ4MDAwEgAAAAAEOTAwMBEAAAAABDkwMDEIAAAAAAUxMjQwMAIAAAAABTEyNDAxEQAAAAAFMTI0MDIRAAAAAAUxMjQwMwgAAAAABTEyNDA0AgAAAAAFMTI0MzcIAAAAAAUxMjQzOAgAAAAABTEyNDQwAgAAAAAFMTI0NDEIAAAAAAUxMjQ0MhEAAAAABTEyNDQzCAAAAAAFMTI0NDQRAAAAAAUxMjQ0NREAAAAABTEyNDQ2CAAAAAAFMTI0NDcRAAAAAAUxMjQ3MBEAAAAABTEyNDcxDwAAAAAFMTI0NzIPAAAAAAUxMjQ3Mw8AAAAABTEyNDc0EQAAAAAFMTI0ODAOAAAAAAUxMjQ4NREAAAAABTEyNDg2AgAAAAAFMTI0OTARAAAAAAUxMjQ5MREAAAAABTEyNDk4AgAAAAAFMTI0OTkPAAAAAAQ1NzU0EQAAAAAENTc5NhEAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
            string iam_general = "B2RhdGFTZXR/AAAAAQAAAA1QdXJjaGFzZSBMaW5lCQQAAOsAAAABMAoAAAAACGJvb2ttYXJrEwAAAAABMQgAAAAAATIRAAAAAAEzEQAAAAABNAgAAAAAATUIAAAAAAE2EQAAAAABNxEAAAAAATgRAAAAAAIxMA8AAAAAAjExEQAAAAACMTIRAAAAAAIxMxEAAAAAAjE1DgAAAAACMTYOAAAAAAIxNw4AAAAAAjE4DgAAAAACMjIOAAAAAAIyMw4AAAAAAjI1DgAAAAACMjcOAAAAAAIyOA4AAAAAAjI5DgAAAAACMzAOAAAAAAIzMQ4AAAAAAjMyAgAAAAACMzQOAAAAAAIzNQ4AAAAAAjM2DgAAAAACMzcOAAAAAAIzOAgAAAAAAjQwEQAAAAACNDERAAAAAAI0NREAAAAAAjU0DgAAAAACNTYCAAAAAAI1Nw4AAAAAAjU4DgAAAAACNTkOAAAAAAI2MA4AAAAAAjYxDgAAAAACNjMRAAAAAAI2NAgAAAAAAjY3DgAAAAACNjgRAAAAAAI2OQ4AAAAAAjcwEQAAAAACNzERAAAAAAI3MggAAAAAAjczAgAAAAACNzQRAAAAAAI3NREAAAAAAjc3CAAAAAACNzgRAAAAAAI3OREAAAAAAjgwCAAAAAACODERAAAAAAI4MhEAAAAAAjgzEQAAAAACODURAAAAAAI4NgIAAAAAAjg3EQAAAAACODgCAAAAAAI4OREAAAAAAjkwEQAAAAACOTERAAAAAAI5Mg4AAAAAAjkzDgAAAAACOTUOAAAAAAI5NxEAAAAAAjk4CAAAAAACOTkOAAAAAAMxMDAOAAAAAAMxMDECAAAAAAMxMDMOAAAAAAMxMDQOAAAAAAMxMDUOAAAAAAMxMDYRAAAAAAMxMDcIAAAAAAMxMDgRAAAAAAMxMDkOAAAAAAMxMTAOAAAAAAMxMTEOAAAAAAMxMTIOAAAAAAMxMTMOAAAAAAMxMTQOAAAAAAMxMTUOAAAAAAMxMTYIAAAAAAMxMTcRAAAAAAMxMTgRAAAAAAMxMTkCAAAAAAMxMjARAAAAAAMxMjEOAAAAAAMxMjIOAAAAAAMxMjMCAAAAAAMxMjQOAAAAAAMxMjkOAAAAAAMxMzARAAAAAAMxMzIOAAAAAAMxMzUOAAAAAAMxMzYOAAAAAAMxMzcOAAAAAAMxNDAOAAAAAAMxNDEOAAAAAAM0ODAIAAAAAAQxMDAxEQAAAAAEMTAwMggAAAAABDEwMDMOAAAAAAQxMDA0DgAAAAAEMTAwNQ4AAAAABDEwMDYOAAAAAAQxMDA3DgAAAAAEMTAwOA4AAAAABDEwMDkOAAAAAAQxMDEwDgAAAAAEMTAxMQ4AAAAABDEwMTIOAAAAAAQxMDEzEQAAAAAEMTAxOQgAAAAABDEwMzAOAAAAAAQxMDMxDgAAAAAEMTcwMBEAAAAABDE3MDIPAAAAAAQ1NDAxEQAAAAAENTQwMhEAAAAABDU0MDMRAAAAAAQ1NDA0DgAAAAAENTQwNxEAAAAABDU0MTUOAAAAAAQ1NDE2DgAAAAAENTQxNw4AAAAABDU0MTgOAAAAAAQ1NDU4DgAAAAAENTQ2MA4AAAAABDU0NjEOAAAAAAQ1NDk1DgAAAAAENTYwMA8AAAAABDU2MDEIAAAAAAQ1NjAyEQAAAAAENTYwMw4AAAAABDU2MDUCAAAAAAQ1NjA2AgAAAAAENTYwOREAAAAABDU2MTARAAAAAAQ1NjExEQAAAAAENTYxMhEAAAAABDU2MTMCAAAAAAQ1NzAwEQAAAAAENTcwNREAAAAABDU3MDYRAAAAAAQ1NzA3CAAAAAAENTcwOBEAAAAABDU3MDkRAAAAAAQ1NzEwAgAAAAAENTcxMREAAAAABDU3MTIRAAAAAAQ1NzEzAgAAAAAENTcxNBEAAAAABDU3MTUIAAAAAAQ1NzUwDgAAAAAENTc1MgIAAAAABDU3OTAPAAAAAAQ1NzkxDwAAAAAENTc5MhEAAAAABDU3OTMRAAAAAAQ1Nzk0DwAAAAAENTc5NQ8AAAAABDU4MDACAAAAAAQ1ODAxDgAAAAAENTgwMg4AAAAABDU4MDMOAAAAAAQ1ODA0DgAAAAAENTgwNQ4AAAAABDU4MDYOAAAAAAQ1ODA3DgAAAAAENTgwOA4AAAAABDU4MDkOAAAAAAQ1ODEwDgAAAAAENjYwMBEAAAAABDY2MDEIAAAAAAQ2NjA4EQAAAAAENjYwOQgAAAAABDY2MTACAAAAAAUxMjQwMBEAAAAABTEyNDAxCAAAAAAFMTI0MDIPAAAAAAUxMjQwMxEAAAAABTEyNDA0EQAAAAAFMTI0MDURAAAAAAUxMjQzMA4AAAAABTEyNDMxDgAAAAAFMTI0ODUCAAAAAAUxMjQ4NhEAAAAABTEyNDg3AgAAAAAFMTI0OTARAAAAAAUxNzMwMBEAAAAACDk5MDAwNzUwEQAAAAAIOTkwMDA3NTERAAAAAAg5OTAwMDc1MhEAAAAACDk5MDAwNzUzAgAAAAAIOTkwMDA3NTQIAAAAAAg5OTAwMDc1NQ4AAAAACDk5MDAwNzU2AgAAAAAIOTkwMDA3NTcIAAAAAAg5OTAwMDc1OBEAAAAACDk5MDAwNzU5CAAAAAAVQ29udHJvbDEyMTAwMzFfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwMzdfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwMzlfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwNDFfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwNDNfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwNDVfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwNDdfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwNDlfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwNTNfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwNTdfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwNTlfRm9ybWF0EQAAAAAOQ29udHJvbDEyMTAwOTERAAAAAA5Db250cm9sMTIxMDA5MxEAAAAADkNvbnRyb2wxMjEwMDk1EQAAAAAOQ29udHJvbDEyMTAwOTcRAAAAAA5Db250cm9sMTIxMDA5OREAAAAADkNvbnRyb2wxMjEwMTAxEQAAAAAdQ29udHJvbDEyMTAwMDdfRHluYW1pY0NhcHRpb24RAAAAAB1Db250cm9sMTIxMDAzN19EeW5hbWljQ2FwdGlvbhEAAAAAHUNvbnRyb2wxMjEwMDQ1X0R5bmFtaWNDYXB0aW9uEQAAAAAdQ29udHJvbDEyMTAwODdfRHluYW1pY0NhcHRpb24RAAAAAB1Db250cm9sMTIxMDA4OV9EeW5hbWljQ2FwdGlvbhEAAAAAHUNvbnRyb2wxMjEwMDkxX0R5bmFtaWNDYXB0aW9uEQAAAAAdQ29udHJvbDEyMTAwOTNfRHluYW1pY0NhcHRpb24RAAAAAB1Db250cm9sMTIxMDA5NV9EeW5hbWljQ2FwdGlvbhEAAAAAHUNvbnRyb2wxMjEwMDk3X0R5bmFtaWNDYXB0aW9uEQAAAAAdQ29udHJvbDEyMTAwOTlfRHluYW1pY0NhcHRpb24RAAAAAB1Db250cm9sMTIxMDEwMV9EeW5hbWljQ2FwdGlvbhEAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=";

            string textDecoded6 = System.Text.Encoding.UTF8.DecodeBase64(iam_first);
            string textDecoded7 = System.Text.Encoding.UTF8.DecodeBase64(iam_general);

            Stopwatch sw_1 = new Stopwatch();
            Stopwatch sw_2 = new Stopwatch();
            Stopwatch sw_3 = new Stopwatch();
            Stopwatch sw_4 = new Stopwatch();
            Stopwatch sw_5 = new Stopwatch();
            Stopwatch sw_6 = new Stopwatch();
            Stopwatch sw_7 = new Stopwatch();
            Stopwatch sw_8 = new Stopwatch();
            Stopwatch sw_9 = new Stopwatch();
            Stopwatch sw_10 = new Stopwatch();
            Stopwatch sw_11 = new Stopwatch();
            Stopwatch sw_12 = new Stopwatch();
            Stopwatch sw_13 = new Stopwatch();
            Stopwatch sw_14 = new Stopwatch();
            Stopwatch sw_15 = new Stopwatch();
            Stopwatch sw_16 = new Stopwatch();
            Stopwatch sw_17 = new Stopwatch();
            Stopwatch sw_18 = new Stopwatch();
            Stopwatch sw_19 = new Stopwatch();
            Stopwatch sw_20 = new Stopwatch();
            Stopwatch sw_21 = new Stopwatch();
            Stopwatch sw_22 = new Stopwatch();
            Stopwatch sw_23 = new Stopwatch();
            Stopwatch sw_24 = new Stopwatch();
            Stopwatch sw_25 = new Stopwatch();
            Stopwatch sw_26 = new Stopwatch();
            Stopwatch sw_27 = new Stopwatch();
            Stopwatch sw_28 = new Stopwatch();
            Stopwatch sw_29 = new Stopwatch();
            Stopwatch sw_30 = new Stopwatch();
            Stopwatch sw_31 = new Stopwatch();


            Stopwatch sw_50 = new Stopwatch();
            Stopwatch sw_51 = new Stopwatch();
            Stopwatch sw_52 = new Stopwatch();
            Stopwatch sw_53 = new Stopwatch();
            Stopwatch sw_54 = new Stopwatch();
            Stopwatch sw_55 = new Stopwatch();
            Stopwatch sw_56 = new Stopwatch();
            Stopwatch sw_57 = new Stopwatch();
            Stopwatch sw_58 = new Stopwatch();
            Stopwatch sw_59 = new Stopwatch();
            Stopwatch sw_COMPLEATE = new Stopwatch();

            sw_COMPLEATE.Start();

            sw_1.Start();


            //*************************************************
            //  ЛОГИН
            //*************************************************
            SetConsoleTextAttribute(GetStdHandle(-11), (short)62); Console.WriteLine("****** LOGIN ******");


            //==============================================
            //  OpenConnection, SetClientSettings, GetAddInRegistrations
            // Старт клиента            
            IProductNameProvider productNameProvider = new StaticProductNameProvider("Performance Test"); a9("StaticProductNameProvider ", sw_1, sw_2, (short)7);
            NavWinFormsClientSessionPreparation navWinFormsClientSessionPreparation = new NavWinFormsClientSessionPreparation(productNameProvider, false); a9("ClientSessionPreparation  ", sw_2, sw_3, (short)7);
            NavWinFormsClientSession navWinFormsClientSession = new NavWinFormsClientSession(navWinFormsClientSessionPreparation); a9("NavWinFormsClientSession  ", sw_3, sw_4, (short)7);
            navWinFormsClientSession.Init(); a9("*** !!! Init !!! ***      ", sw_4, sw_5, (short)9);

            String personalizationId = navWinFormsClientSession.UISession.SessionPersonalizationId; //a9("SessionPersonalizationId", sw_5, sw_6, (short)7);

            String personalizationId1 = "ec29feaf-58ae-4c7a-8c7f-792d5cfd9aa0";
            String personalizationId2 = "374f138d-58a0-4b24-b6f9-da451371b033";

            IService service = navWinFormsClientSession.BuilderSession.Service; //a9("Service", sw_6, sw_7, (short)7);
            IMetadataService metadataService = navWinFormsClientSession.BuilderSession.MetadataService; //a9("MetadataService", sw_7, sw_8, (short)7);

            //==============================================
            //  GetPage

            //==============================================
            //  GetPage

            //==============================================
            //  GetNavigationFrame
            // Открытие панелей клиента
            MasterNavigation masterNavigation1 = metadataService.GetNavigationFrame(
                applyPersonalization: true,
                getNavigationFrameFromServer: true
                );

            a9("GetNavigationFrame        ", sw_5, sw_9, (short)7);

            //==============================================
            //  GetNavigationFrame
            MasterNavigation masterNavigation2 = metadataService.GetNavigationFrame(
                applyPersonalization: true,
                getNavigationFrameFromServer: true
                );

            // Получение главного окна
            ActionDefinition control_Role_Center = masterNavigation2.NavigationPane.
                    Actions.Single(a => a.ALIdentifier == "Control_Home").
                    Actions.Single(a => a.Name == "Control_Role_Center") as ActionDefinition;

            a9("GetNavigationFrame        ", sw_9, sw_10, (short)7);

            //==============================================
            //  GetMetadataForPageAndAllItsDependencies
            MasterPage masterPage = metadataService.GetMasterPage(
                pageId: control_Role_Center.TargetID, // 9006
                personalizationId: personalizationId1,
                applyPersonalization: true
                );
            //MasterPage myNotes = metadataService.GetSystemPart(
            //    partType: SystemPartTypes.MyNotes
            //    );
            //MetaTable myNotesTable = metadataService.GetTableMetadata(
            //    tableId: myNotes.PageProperties.SourceObject.SourceTable // 2000000068
            //    );

            a9("GetMetadataForPage        ", sw_10, sw_11, (short)10);

            //==============================================
            //  GetWorkDate
            DateTime workDate = service.GetWorkDate();

            a9("GetWorkDate               ", sw_11, sw_12, (short)7);






            //*************************************************
            //  ПОИСК ОКНА ОТЧЕТОВ
            //*************************************************
            SetConsoleTextAttribute(GetStdHandle(-11), (short)62); Console.WriteLine("****** SEARCH REPORT WINDOW ******");

            //==============================================
            //  GetMetadataForPageAndAllItsDependencies

            MasterPage gmfpaaid_1 = metadataService.GetMasterPage(
                pageId: 35610,
                personalizationId: personalizationId2,
                applyPersonalization: true
            );

            //CodeUnitResponse aaaa = service.InvokeApplicationMethod();

            a9("GetMetadataForPage        ", sw_12, sw_13, (short)10);

            //==============================================
            //  lnvokeApplicationMethod
            NavVisualizationHelper.Initialize(service);

            a9("lnvokeApplicationMethod   ", sw_13, sw_14, (short)4);

            //==============================================
            //  OpenForm
            string nofa_1_mf_cr = "JgAAAACLAgAAAAJ7/x8EHgQQBBIELQAyADEALQAwADAAMAAyADYAAAAAAA==";

            NavOpenFormArguments nofa_1_mf = new NavOpenFormArguments()
            {
                State = new NavRecordState()
                {
                    CurrentRecord = Convert.FromBase64String(nofa_1_mf_cr),
                    FormId = 35610, // gmfpaaid_1.ID, 
                    PersonalizationId = personalizationId2,
                    ParentFormId = 0,
                    NavFormEditable = false,
                    RenamingMode = RenamingMode.SingleKeyServerSide,
                    TableView = new NavTableView()
                    {
                        Ascending = true,
                        TableId = 38,//gmfpaaid_1.PageProperties.SourceObject.SourceTable,
                        SearchFilter = new NavFilterGroup()
                        {
                            FilterGroupNo = -1,
                            Filters = new NavFilter[0]
                        }
                    },
                    ValidateFieldsInOnNewRecord = true,
                    ValidateRequired = true
                }
            };
            NavOpenFormArguments[] nofa_1_sf = null;

            service.OpenForm(
                    mainForm: ref nofa_1_mf,
                    subForms: ref nofa_1_sf
                );

            a9("OpenForm                  ", sw_14, sw_15, (short)11);

            //==============================================
            //  GetPage
            NavRecordState gp_mf_1 = nofa_1_mf.State;
            string gp_sb_1 = "JgAAAACLAgAAAAJ7/x8EHgQQBBIELQAyADEALQAwADAAMAAyADYAAAAAAA==";


            service.GetPage(
                pageRequestDefinition: new PageRequestDefinition()
                {
                    IncludeMoreDataInformation = true,
                    IncludeNonRowData = true,
                    PageSize = 50,
                    PageSizeInOppositeDirection = 50,
                    ReadDirection = ReadDirection.Next,
                    StartFromPage = StartingPage.Specific,
                    StartingBookmark = Convert.FromBase64String(gp_sb_1)
                },
                state: ref gp_mf_1
                );

            a9("GetPage                   ", sw_15, sw_16, (short)14);

            //*************************************************
            //  СОЗДАНИЕ ОТЧЕТА
            //*************************************************
            SetConsoleTextAttribute(GetStdHandle(-11), (short)62); Console.WriteLine("****** CREATE REPORT ******");

            //==============================================
            //  GetMetadataForPageAndAllItsDependencies

            MasterPage gmfpaaid_2 = metadataService.GetMasterPage(
                pageId: 12431,
                personalizationId: string.Empty,
                applyPersonalization: true
            );

            a9("GetMetadataForPage        ", sw_16, sw_17, (short)10);

            //==============================================
            //  OpenForm
            NavOpenFormArguments nofa_2_mf = new NavOpenFormArguments()
            {
                ControlId = null,

                State = new NavRecordState()
                {
                    CurrentRecord = null,
                    FormId = 12431, //gmfpaaid_2.ID
                    //PersonalizationId = null,
                    ParentFormId = 0,
                    NavFormEditable = true,
                    RenamingMode = RenamingMode.SingleKeyServerSide,
                    TableView = new NavTableView()
                    {
                        Ascending = true,
                        TableId = 38,
                        CurrentSortingFieldIds = new int[2] { 1, 3 },
                        SearchFilter = new NavFilterGroup()
                        {
                            FilterGroupNo = -1,
                            Filters = new NavFilter[0]
                        },
                        CurrentFilters = new NavFilterGroup[1] {
                            new NavFilterGroup() {
                                FilterGroupNo = 2,
                                Filters = new NavFilter[2]{
                                    new NavFilter(){
                                        FilterField = 1,
                                        FilterValue = "2",
                                        IsExactValue = true,
                                        OptionsAsCaptionsFilterValue = "Invoice",
                                        UserTypedFilterValue = null
                                    },
                                    new NavFilter(){
                                        FilterField = 12400,
                                        FilterValue = "1",
                                        IsExactValue = true,
                                        OptionsAsCaptionsFilterValue = "Yes",
                                        UserTypedFilterValue = null
                                    }
                                }
                            }
                        }
                    },
                    ValidateFieldsInOnNewRecord = true,
                    ValidateRequired = true
                }
            };
            NavOpenFormArguments[] nofa_2_sf = new List<NavOpenFormArguments>().Append(new NavOpenFormArguments()
            {
                ControlId = "1210001",

                State = new NavRecordState()
                {
                    CurrentRecord = null,
                    FormId = 12432,
                    //PersonalizationId = personalizationId2,
                    ParentFormId = 12431,
                    NavFormEditable = true,
                    RenamingMode = RenamingMode.NoKeys,
                    TableView = new NavTableView()
                    {
                        Ascending = true,
                        TableId = 39,
                        SearchFilter = new NavFilterGroup()
                        {
                            FilterGroupNo = -1,
                            Filters = new NavFilter[0]
                        }
                    },
                    ValidateFieldsInOnNewRecord = true,
                    ValidateRequired = true
                }
            }).ToArray();

            service.OpenForm(
                        mainForm: ref nofa_2_mf,
                        subForms: ref nofa_2_sf
                    );

            a9("OpenForm                  ", sw_17, sw_18, (short)11);

            //}
            //==============================================
            //  lnvokeApplicationMethod
            NavRecordState iam_s_1 = nofa_2_mf.State;
            NavDataSet iam_nds_1 = nofa_2_mf.DataSet;
            int iam_s_fid_1 = nofa_2_mf.State.FormId;
            object[] iam_obj_1 = new object[1]; iam_obj_1[0] = true;

            //извлекаем из структуры NAV отражением и проверяем что внурри до перезаписи
            var recdatasetref_1 = iam_nds_1.GetType().GetProperty("DataSet", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public);
            var recdataset_1 = recdatasetref_1.GetValue(iam_nds_1);
            byte[] databyte_1 = (byte[])recdataset_1.GetType().GetProperty("Data").GetValue(recdataset_1);

            string datastr_original_1 = System.Text.Encoding.UTF8.GetString((byte[])databyte_1);

            //************************************
            //       DATA FIELD CORRELATION
            //
            //записываем в структуру NAV отражением
            string DataSet_str_iam_1 = "B2RhdGFTZXR/AAAAAQAAAA9QdXJjaGFzZSBIZWFkZXIJBAAAswAAAAEwCgAAAAAIYm9va21hcmsTAAAAAAExCAAAAAABMhEAAAAAATMRAAAAAAE0EQAAAAABNREAAAAAATYRAAAAAAE3EQAAAAABOBEAAAAAATkRAAAAAAIxMBEAAAAAAjExEQAAAAACMTIRAAAAAAIxMxEAAAAAAjE0EQAAAAACMTURAAAAAAIxNhEAAAAAAjE3EQAAAAACMTgRAAAAAAIxOQ8AAAAAAjIwDwAAAAACMjEPAAAAAAIyMhEAAAAAAjIzEQAAAAACMjQPAAAAAAIyNQ4AAAAAAjI2DwAAAAACMjcRAAAAAAIyOBEAAAAAAjI5EQAAAAACMzARAAAAAAIzMREAAAAAAjMyEQAAAAACMzMOAAAAAAIzNQIAAAAAAjM3EQAAAAACNDERAAAAAAI0MxEAAAAAAjQ1EQAAAAACNDYCAAAAAAI0NwgAAAAAAjUxEQAAAAACNTIIAAAAAAI1MxEAAAAAAjU1EQAAAAACNTYCAAAAAAI1NwIAAAAAAjU4AgAAAAACNTkCAAAAAAI2MA4AAAAAAjYxDgAAAAACNjIRAAAAAAI2MxEAAAAAAjY0EQAAAAACNjURAAAAAAI2NhEAAAAAAjY3EQAAAAACNjgRAAAAAAI2OREAAAAAAjcwEQAAAAACNzIRAAAAAAI3MxEAAAAAAjc0EQAAAAACNzYRAAAAAAI3NxEAAAAAAjc4EQAAAAACNzkRAAAAAAI4MBEAAAAAAjgxEQAAAAACODIRAAAAAAI4MxEAAAAAAjg0EQAAAAACODURAAAAAAI4NhEAAAAAAjg3EQAAAAACODgRAAAAAAI4OREAAAAAAjkwEQAAAAACOTERAAAAAAI5MhEAAAAAAjkzEQAAAAACOTQIAAAAAAI5NREAAAAAAjk3EQAAAAACOTgCAAAAAAI5OQ8AAAAAAzEwMREAAAAAAzEwMhEAAAAAAzEwNBEAAAAAAzEwNxEAAAAAAzEwOBEAAAAAAzEwOREAAAAAAzExNBEAAAAAAzExNQIAAAAAAzExNhEAAAAAAzExOBEAAAAAAzExOQ4AAAAAAzEyMAgAAAAAAzEyMQgAAAAAAzEyMg4AAAAAAzEyMwIAAAAAAzEyNAgAAAAAAzEyNREAAAAAAzEyNhEAAAAAAzEyOQgAAAAAAzEzMBEAAAAAAzEzMREAAAAAAzEzMhEAAAAAAzEzMxEAAAAAAzEzNA4AAAAAAzEzNREAAAAAAzEzNgIAAAAAAzEzNw8AAAAAAzEzOBEAAAAAAzEzOREAAAAAAzE0Mg8AAAAAAzE0MxEAAAAAAzE0NA4AAAAAAzE1MREAAAAAAzE2MAgAAAAAAzE2MRIAAAAAAzE2NQgAAAAAAzE3MBEAAAAAAzE3MREAAAAAAzMwMA4AAAAAAzMwMQ4AAAAAAzQ4MAgAAAAABDEzMDUOAAAAAAQ1MDQzCAAAAAAENTA0OAgAAAAABDUwNTARAAAAAAQ1MDUyEQAAAAAENTA1MxEAAAAABDU3MDARAAAAAAQ1NzUxAgAAAAAENTc1MgIAAAAABDU3NTMIAAAAAAQ1NzkwDwAAAAAENTc5MQ8AAAAABDU3OTIRAAAAAAQ1NzkzEQAAAAAENTgwMBEAAAAABDU4MDERAAAAAAQ1ODAyEQAAAAAENTgwMwIAAAAABDU4MDQRAAAAAAQ4MDAwEgAAAAAEOTAwMBEAAAAABDkwMDEIAAAAAAUxMjQwMAIAAAAABTEyNDAxEQAAAAAFMTI0MDIRAAAAAAUxMjQwMwgAAAAABTEyNDA0AgAAAAAFMTI0MzcIAAAAAAUxMjQzOAgAAAAABTEyNDQwAgAAAAAFMTI0NDEIAAAAAAUxMjQ0MhEAAAAABTEyNDQzCAAAAAAFMTI0NDQRAAAAAAUxMjQ0NREAAAAABTEyNDQ2CAAAAAAFMTI0NDcRAAAAAAUxMjQ3MBEAAAAABTEyNDcxDwAAAAAFMTI0NzIPAAAAAAUxMjQ3Mw8AAAAABTEyNDc0EQAAAAAFMTI0ODAOAAAAAAUxMjQ4NREAAAAABTEyNDg2AgAAAAAFMTI0OTARAAAAAAUxMjQ5MREAAAAABTEyNDk4AgAAAAAFMTI0OTkPAAAAAAQ1NzU0EQAAAAAENTc5NhEAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
            byte[] DataSet_iam_1 = Convert.FromBase64String(DataSet_str_iam_1);

            NavDataSet NavDataSet_0 = new NavDataSet { DataSetName = "NewDataSet" };

            var datasetdata_0 = NavDataSet_0.GetType().GetProperty("DataSet", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public).GetValue(NavDataSet_0);
            datasetdata_0.GetType().GetProperty("Data", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public).SetValue(datasetdata_0, DataSet_iam_1);
            NavDataSet_0.GetType().GetProperty("DataSet", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public).SetValue(NavDataSet_0, datasetdata_0);

            iam_nds_1 = NavDataSet_0;   //запись правильного поля Data, автоматически генерируется неправильно

            //извлекаем из структуры NAV отражением и проверяем что записалось
            var recdatasetref_2 = iam_nds_1.GetType().GetProperty("DataSet", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public);
            var recdataset_2 = recdatasetref_2.GetValue(iam_nds_1);
            byte[] databyte_2 = (byte[])recdataset_2.GetType().GetProperty("Data").GetValue(recdataset_2);

            string datastr_original_2 = System.Text.Encoding.UTF8.GetString((byte[])databyte_2);
            //************************************

            service.InvokeApplicationMethod(objectType: ApplicationCodeType.FormCode, objectId: iam_s_fid_1, methodName: "NewRecord", dataSet: ref iam_nds_1, state: ref iam_s_1, args: ref iam_obj_1);

            a9("lnvokeApplicationMethod   ", sw_18, sw_19, (short)4);

            //==============================================
            //  GetPage
            NavRecordState gp_mf_2 = nofa_2_sf[0].State;
            service.GetPage(
                pageRequestDefinition: new PageRequestDefinition()
                {
                    CalcFields = new int[2] { 5801, 5802 },
                    IncludeMoreDataInformation = true,
                    IncludeNonRowData = true,
                    PageSize = 20,
                    PageSizeInOppositeDirection = 20,
                    ReadDirection = ReadDirection.Next,
                    StartFromPage = StartingPage.Specific,
                },
                state: ref gp_mf_2
                );

            a9("GetPage                   ", sw_19, sw_20, (short)14);

            //==============================================
            //  lnvokeApplicationMethod

            NavRecordState iam_s_2 = nofa_2_sf[0].State;
            NavDataSet iam_nds_2 = nofa_2_sf[0].DataSet;
            int iam_s_fid_2 = nofa_2_sf[0].State.FormId;

            //************************************
            //       DATA FIELD CORRELATION
            //записываем в структуру NAV отражением
            string DataSet_str_iam_2 = "B2RhdGFTZXR/AAAAAQAAAA1QdXJjaGFzZSBMaW5lCQQAAOsAAAABMAoAAAAACGJvb2ttYXJrEwAAAAABMQgAAAAAATIRAAAAAAEzEQAAAAABNAgAAAAAATUIAAAAAAE2EQAAAAABNxEAAAAAATgRAAAAAAIxMA8AAAAAAjExEQAAAAACMTIRAAAAAAIxMxEAAAAAAjE1DgAAAAACMTYOAAAAAAIxNw4AAAAAAjE4DgAAAAACMjIOAAAAAAIyMw4AAAAAAjI1DgAAAAACMjcOAAAAAAIyOA4AAAAAAjI5DgAAAAACMzAOAAAAAAIzMQ4AAAAAAjMyAgAAAAACMzQOAAAAAAIzNQ4AAAAAAjM2DgAAAAACMzcOAAAAAAIzOAgAAAAAAjQwEQAAAAACNDERAAAAAAI0NREAAAAAAjU0DgAAAAACNTYCAAAAAAI1Nw4AAAAAAjU4DgAAAAACNTkOAAAAAAI2MA4AAAAAAjYxDgAAAAACNjMRAAAAAAI2NAgAAAAAAjY3DgAAAAACNjgRAAAAAAI2OQ4AAAAAAjcwEQAAAAACNzERAAAAAAI3MggAAAAAAjczAgAAAAACNzQRAAAAAAI3NREAAAAAAjc3CAAAAAACNzgRAAAAAAI3OREAAAAAAjgwCAAAAAACODERAAAAAAI4MhEAAAAAAjgzEQAAAAACODURAAAAAAI4NgIAAAAAAjg3EQAAAAACODgCAAAAAAI4OREAAAAAAjkwEQAAAAACOTERAAAAAAI5Mg4AAAAAAjkzDgAAAAACOTUOAAAAAAI5NxEAAAAAAjk4CAAAAAACOTkOAAAAAAMxMDAOAAAAAAMxMDECAAAAAAMxMDMOAAAAAAMxMDQOAAAAAAMxMDUOAAAAAAMxMDYRAAAAAAMxMDcIAAAAAAMxMDgRAAAAAAMxMDkOAAAAAAMxMTAOAAAAAAMxMTEOAAAAAAMxMTIOAAAAAAMxMTMOAAAAAAMxMTQOAAAAAAMxMTUOAAAAAAMxMTYIAAAAAAMxMTcRAAAAAAMxMTgRAAAAAAMxMTkCAAAAAAMxMjARAAAAAAMxMjEOAAAAAAMxMjIOAAAAAAMxMjMCAAAAAAMxMjQOAAAAAAMxMjkOAAAAAAMxMzARAAAAAAMxMzIOAAAAAAMxMzUOAAAAAAMxMzYOAAAAAAMxMzcOAAAAAAMxNDAOAAAAAAMxNDEOAAAAAAM0ODAIAAAAAAQxMDAxEQAAAAAEMTAwMggAAAAABDEwMDMOAAAAAAQxMDA0DgAAAAAEMTAwNQ4AAAAABDEwMDYOAAAAAAQxMDA3DgAAAAAEMTAwOA4AAAAABDEwMDkOAAAAAAQxMDEwDgAAAAAEMTAxMQ4AAAAABDEwMTIOAAAAAAQxMDEzEQAAAAAEMTAxOQgAAAAABDEwMzAOAAAAAAQxMDMxDgAAAAAEMTcwMBEAAAAABDE3MDIPAAAAAAQ1NDAxEQAAAAAENTQwMhEAAAAABDU0MDMRAAAAAAQ1NDA0DgAAAAAENTQwNxEAAAAABDU0MTUOAAAAAAQ1NDE2DgAAAAAENTQxNw4AAAAABDU0MTgOAAAAAAQ1NDU4DgAAAAAENTQ2MA4AAAAABDU0NjEOAAAAAAQ1NDk1DgAAAAAENTYwMA8AAAAABDU2MDEIAAAAAAQ1NjAyEQAAAAAENTYwMw4AAAAABDU2MDUCAAAAAAQ1NjA2AgAAAAAENTYwOREAAAAABDU2MTARAAAAAAQ1NjExEQAAAAAENTYxMhEAAAAABDU2MTMCAAAAAAQ1NzAwEQAAAAAENTcwNREAAAAABDU3MDYRAAAAAAQ1NzA3CAAAAAAENTcwOBEAAAAABDU3MDkRAAAAAAQ1NzEwAgAAAAAENTcxMREAAAAABDU3MTIRAAAAAAQ1NzEzAgAAAAAENTcxNBEAAAAABDU3MTUIAAAAAAQ1NzUwDgAAAAAENTc1MgIAAAAABDU3OTAPAAAAAAQ1NzkxDwAAAAAENTc5MhEAAAAABDU3OTMRAAAAAAQ1Nzk0DwAAAAAENTc5NQ8AAAAABDU4MDACAAAAAAQ1ODAxDgAAAAAENTgwMg4AAAAABDU4MDMOAAAAAAQ1ODA0DgAAAAAENTgwNQ4AAAAABDU4MDYOAAAAAAQ1ODA3DgAAAAAENTgwOA4AAAAABDU4MDkOAAAAAAQ1ODEwDgAAAAAENjYwMBEAAAAABDY2MDEIAAAAAAQ2NjA4EQAAAAAENjYwOQgAAAAABDY2MTACAAAAAAUxMjQwMBEAAAAABTEyNDAxCAAAAAAFMTI0MDIPAAAAAAUxMjQwMxEAAAAABTEyNDA0EQAAAAAFMTI0MDURAAAAAAUxMjQzMA4AAAAABTEyNDMxDgAAAAAFMTI0ODUCAAAAAAUxMjQ4NhEAAAAABTEyNDg3AgAAAAAFMTI0OTARAAAAAAUxNzMwMBEAAAAACDk5MDAwNzUwEQAAAAAIOTkwMDA3NTERAAAAAAg5OTAwMDc1MhEAAAAACDk5MDAwNzUzAgAAAAAIOTkwMDA3NTQIAAAAAAg5OTAwMDc1NQ4AAAAACDk5MDAwNzU2AgAAAAAIOTkwMDA3NTcIAAAAAAg5OTAwMDc1OBEAAAAACDk5MDAwNzU5CAAAAAAVQ29udHJvbDEyMTAwMzFfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwMzdfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwMzlfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwNDFfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwNDNfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwNDVfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwNDdfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwNDlfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwNTNfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwNTdfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwNTlfRm9ybWF0EQAAAAAOQ29udHJvbDEyMTAwOTERAAAAAA5Db250cm9sMTIxMDA5MxEAAAAADkNvbnRyb2wxMjEwMDk1EQAAAAAOQ29udHJvbDEyMTAwOTcRAAAAAA5Db250cm9sMTIxMDA5OREAAAAADkNvbnRyb2wxMjEwMTAxEQAAAAAdQ29udHJvbDEyMTAwMDdfRHluYW1pY0NhcHRpb24RAAAAAB1Db250cm9sMTIxMDAzN19EeW5hbWljQ2FwdGlvbhEAAAAAHUNvbnRyb2wxMjEwMDQ1X0R5bmFtaWNDYXB0aW9uEQAAAAAdQ29udHJvbDEyMTAwODdfRHluYW1pY0NhcHRpb24RAAAAAB1Db250cm9sMTIxMDA4OV9EeW5hbWljQ2FwdGlvbhEAAAAAHUNvbnRyb2wxMjEwMDkxX0R5bmFtaWNDYXB0aW9uEQAAAAAdQ29udHJvbDEyMTAwOTNfRHluYW1pY0NhcHRpb24RAAAAAB1Db250cm9sMTIxMDA5NV9EeW5hbWljQ2FwdGlvbhEAAAAAHUNvbnRyb2wxMjEwMDk3X0R5bmFtaWNDYXB0aW9uEQAAAAAdQ29udHJvbDEyMTAwOTlfRHluYW1pY0NhcHRpb24RAAAAAB1Db250cm9sMTIxMDEwMV9EeW5hbWljQ2FwdGlvbhEAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=";
            byte[] DataSet_iam_2 = Convert.FromBase64String(DataSet_str_iam_2);

            NavDataSet NavDataSet_1 = new NavDataSet { DataSetName = "NewDataSet" };

            var datasetdata_1 = NavDataSet_1.GetType().GetProperty("DataSet", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public).GetValue(NavDataSet_1);
            datasetdata_1.GetType().GetProperty("Data", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public).SetValue(datasetdata_1, DataSet_iam_2);
            NavDataSet_1.GetType().GetProperty("DataSet", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public).SetValue(NavDataSet_1, datasetdata_1);

            iam_nds_2 = NavDataSet_1;   //запись правильного поля Data, автоматически генерируется неправильно
            //************************************

            service.InvokeApplicationMethod(objectType: ApplicationCodeType.FormCode, objectId: iam_s_fid_2, methodName: "NewRecord", dataSet: ref iam_nds_2, state: ref iam_s_2, args: ref iam_obj_1);

            a9("lnvokeApplicationMethod   ", sw_20, sw_21, (short)4);

            //*************************************************
            //  ЗАПОЛНЕНИЕ ОТЧЕТА
            //*************************************************
            SetConsoleTextAttribute(GetStdHandle(-11), (short)62); Console.WriteLine("****** FILL REPORT ******");

            //==============================================
            //  Channel/RealAction ---------------- INSERT RECORD (!!!)SLSR(!!!)

            NavDataSet asdasda = service.InsertRecord(state: ref iam_s_1, recDataSet: iam_nds_1, true, false);

            byte[] databyte1 = returnDataByte(asdasda);
            string datastr1 = System.Text.Encoding.UTF8.GetString((byte[])databyte1);
            string poav_filter = Regex.Match(datastr1, "ПОАВ.{9}").ToString();

            a9("INSERT RECORD             ", sw_21, sw_22, (short)9);

            //==============================================
            //  GetMetadataForPageAndAllItsDependencies

            MasterPage gmfpaaid_3 = metadataService.GetMasterPage(
                pageId: 27,
                personalizationId: string.Empty,
                applyPersonalization: true
            );

            a9("GetMetadataForPage        ", sw_22, sw_23, (short)10);

            //==============================================
            //  OpenForm
            NavOpenFormArguments nofa_3_mf = new NavOpenFormArguments()
            {
                ControlId = null,

                State = new NavRecordState()
                {
                    CurrentRecord = null,
                    FormId = 27, //gmfpaaid_3.ID
                    //PersonalizationId = personalizationId2,
                    ParentFormId = 0,
                    NavFormEditable = false,
                    RenamingMode = RenamingMode.NoKeys,
                    TableView = new NavTableView()
                    {
                        Ascending = true,
                        TableId = 23,
                        SearchFilter = new NavFilterGroup()
                        {
                            FilterGroupNo = -1,
                            Filters = new NavFilter[0]
                        }
                    },
                    ValidateFieldsInOnNewRecord = true,
                    ValidateRequired = true
                }
            };
            NavOpenFormArguments[] nofa_3_sf = new List<NavOpenFormArguments>().Append(new NavOpenFormArguments()
            {
                ControlId = "1904651607",

                State = new NavRecordState()
                {
                    CurrentRecord = null,
                    FormId = 9094,
                    //PersonalizationId = personalizationId2,
                    ParentFormId = 27,
                    NavFormEditable = false,
                    RenamingMode = RenamingMode.NoKeys,
                    TableView = new NavTableView()
                    {
                        Ascending = true,
                        TableId = 23,
                        SearchFilter = new NavFilterGroup()
                        {
                            FilterGroupNo = -1,
                            Filters = new NavFilter[0]
                        }
                    },
                    ValidateFieldsInOnNewRecord = true,
                    ValidateRequired = true
                }
            }).Append(new NavOpenFormArguments()
            {
                ControlId = "1903435607",

                State = new NavRecordState()
                {
                    CurrentRecord = null,
                    FormId = 9095,
                    //PersonalizationId = personalizationId2,
                    ParentFormId = 27,
                    NavFormEditable = false,
                    RenamingMode = RenamingMode.NoKeys,
                    TableView = new NavTableView()
                    {
                        Ascending = true,
                        TableId = 23,
                        SearchFilter = new NavFilterGroup()
                        {
                            FilterGroupNo = -1,
                            Filters = new NavFilter[0]
                        }
                    },
                    ValidateFieldsInOnNewRecord = true,
                    ValidateRequired = true
                }
            }).ToArray();

            service.OpenForm(
                        mainForm: ref nofa_3_mf,
                        subForms: ref nofa_3_sf
                    );

            a9("OpenForm                  ", sw_23, sw_24, (short)11);

            //==============================================
            //  GetPage
            NavRecordState gp_mf_3 = nofa_3_mf.State;
            service.GetPage(
                pageRequestDefinition: new PageRequestDefinition()
                {
                    CalcFields = new int[2] { 59, 67 },
                    IncludeMoreDataInformation = true,
                    IncludeNonRowData = true,
                    PageSize = 20,
                    PageSizeInOppositeDirection = 20,
                    ReadDirection = ReadDirection.Next,
                    StartFromPage = StartingPage.Specific,
                },
                state: ref gp_mf_3
                );

            a9("GetPage                   ", sw_24, sw_25, (short)14);

            //==============================================
            //  GetPage
            string gp_mf_4sb = "JgAAAACLAgAAAAJ7/x8EHgQQBBIELQAyADEALQAwADAAMAAzADQAAAAAAA==";

            NavRecordState gp_mf_4 = nofa_1_mf.State;
            service.GetPage(
                pageRequestDefinition: new PageRequestDefinition()
                {
                    IncludeMoreDataInformation = false,
                    IncludeNonRowData = true,
                    PageSize = 1,
                    PageSizeInOppositeDirection = 0,
                    ReadDirection = ReadDirection.Next,
                    StartFromPage = StartingPage.Specific,
                    StartingBookmark = Convert.FromBase64String(gp_mf_4sb)
                },
                state: ref gp_mf_4
                );

            a9("GetPage                   ", sw_25, sw_26, (short)14);

            //==============================================
            //  GetPage
            NavRecordState gp_mf_5 = nofa_2_sf[0].State;
            service.GetPage(
                pageRequestDefinition: new PageRequestDefinition()
                {
                    CalcFields = new int[2] { 5801, 5802 },
                    IncludeMoreDataInformation = true,
                    IncludeNonRowData = true,
                    PageSize = 20,
                    PageSizeInOppositeDirection = 20,
                    ReadDirection = ReadDirection.Next,
                    StartFromPage = StartingPage.Specific,
                },
                state: ref gp_mf_5
                );

            a9("GetPage                   ", sw_26, sw_27, (short)14);

            //==============================================
            //  lnvokeApplicationMethod
            service.InvokeApplicationMethod(objectType: ApplicationCodeType.FormCode, objectId: iam_s_fid_2, methodName: "NewRecord", dataSet: ref iam_nds_2, state: ref iam_s_2, args: ref iam_obj_1);

            a9("lnvokeApplicationMethod   ", sw_27, sw_28, (short)4);

            //==============================================
            //  lnvokeApplicationMethod
            service.InvokeApplicationMethod(objectType: ApplicationCodeType.FormCode, objectId: iam_s_fid_2, methodName: "NewRecord", dataSet: ref iam_nds_2, state: ref iam_s_2, args: ref iam_obj_1);

            a9("lnvokeApplicationMethod   ", sw_28, sw_29, (short)4);

            //==============================================
            //  lnvokeApplicationMethod
            service.InvokeApplicationMethod(objectType: ApplicationCodeType.FormCode, objectId: iam_s_fid_2, methodName: "NewRecord", dataSet: ref iam_nds_2, state: ref iam_s_2, args: ref iam_obj_1);

            a9("lnvokeApplicationMethod   ", sw_29, sw_30, (short)4);

            //==============================================
            //  CloseForm
            {
                NavCloseFormArguments ncfa_3_mf = new NavCloseFormArguments()
                {
                    ExitAction = FormResult.LookupOK,
                    DataSet = nofa_3_mf.DataSet,
                    State = nofa_3_mf.State
                };

                NavCloseFormArguments[] ncfa_3_sf = nofa_3_sf
                    .Select(sf => new NavCloseFormArguments() { DataSet = sf.DataSet, State = sf.State, ExitAction = FormResult.None })
                    .ToArray();

                //************************************
                //       DATA FIELD CORRELATION
                string DataSet_str_cf_1 = "Ck5ld0RhdGFTZXR/AAAAAQAAAAEwCQQAAKsAAAAIYm9va21hcmsTAAAAAAEwCgAAAAABMREAAAAAATIRAAAAAAEzEQAAAAABNBEAAAAAATURAAAAAAE2EQAAAAABNxEAAAAAATgRAAAAAAE5EQAAAAACMTARAAAAAAIxNBEAAAAAAjE1EQAAAAACMTYRAAAAAAIxNxEAAAAAAjE5DgAAAAACMjERAAAAAAIyMhEAAAAAAjI0EQAAAAACMjYIAAAAAAIyNxEAAAAAAjI4EQAAAAACMjkRAAAAAAIzMBEAAAAAAjMxEQAAAAACMzMRAAAAAAIzNREAAAAAAjM5CAAAAAACNDURAAAAAAI0NggAAAAAAjQ3EQAAAAACNTMPAAAAAAI1NA8AAAAAAjgwCAAAAAACODICAAAAAAI4NBEAAAAAAjg1EQAAAAACODYRAAAAAAI4OBEAAAAAAjg5EwAAAAACOTARAAAAAAI5MREAAAAAAjkyEQAAAAADMTAyEQAAAAADMTAzEQAAAAADMTA3EQAAAAADMTA4EQAAAAADMTA5AgAAAAADMTEwEQAAAAADMTE2AgAAAAADMTE5EQAAAAADMTI0DgAAAAADMTMyCAAAAAADMTQwFAAAAAADMTUwAgAAAAADMTYwAgAAAAADMTcwEQAAAAADMjg4EQAAAAADODQwEQAAAAAENTA0OREAAAAABDU3MDARAAAAAAQ1NzAxEQAAAAAENTc5MBEAAAAABDc2MDARAAAAAAQ3NjAxEQAAAAAENzYwMgIAAAAABDgwMDASAAAAAAQ4MDAxEgAAAAAEODAwMhIAAAAABDgwMDMSAAAAAAUxMjQwMBEAAAAABTEyNDAxEQAAAAAFMTI0MDIRAAAAAAUxMjQwMxEAAAAABTEyNDA1EQAAAAAFMTI0MDYRAAAAAAUxMjQwOREAAAAABTEyNDEwAgAAAAAFMTI0MTERAAAAAAUxMjQxMggAAAAABTEyNDEzCAAAAAAFMTI0MTQRAAAAAAUxMjQzMggAAAAABTEyNDgwEQAAAAAFMTI0ODERAAAAAAUxMjQ5MAgAAAAABTEyNDk0EQAAAAACNTUPAAAAAAI1NhEAAAAAAjU3EQAAAAADMTExEQAAAAAFMTI0MjURAAAAAAUxMjQyNg8AAAAABTEyNDkxEQAAAAACMzgCAAAAAAI1OA4AAAAAAjU5DgAAAAACNjAOAAAAAAI2MQ4AAAAAAjYyDgAAAAACNjQOAAAAAAI2NQ4AAAAAAjY2DgAAAAACNjcOAAAAAAI2OQ4AAAAAAjcwDgAAAAACNzEOAAAAAAI3Mg4AAAAAAjc0DgAAAAACNzUOAAAAAAI3Ng4AAAAAAjc3DgAAAAACNzgOAAAAAAI3OQ4AAAAAAjk3DgAAAAACOTgOAAAAAAI5OQ4AAAAAAzEwMA4AAAAAAzEwNA4AAAAAAzEwNQ4AAAAAAzExMw4AAAAAAzExNA4AAAAAAzExNw4AAAAAAzExOA4AAAAAAzEyMA4AAAAAAzEyMQ4AAAAAAzEyMg4AAAAAAzEyMw4AAAAAAzEyNQ4AAAAAAzEyNg4AAAAAAzEzMAgAAAAAAzEzMQgAAAAABDcxNzcIAAAAAAQ3MTc4CAAAAAAENzE3OQgAAAAABDcxODAIAAAAAAQ3MTgxCAAAAAAENzE4MggAAAAABDcxODMIAAAAAAQ3MTg0CAAAAAAENzE4NQgAAAAABDcxODYIAAAAAAQ3MTg3CAAAAAAENzE4OAgAAAAABDcxODkIAAAAAAQ3MTkwCAAAAAAENzE5MQgAAAAABDcxOTIIAAAAAAQ3MTkzCAAAAAAENzE5NAgAAAAABDcxOTUIAAAAAAQ3MTk2CAAAAAAENzE5NwgAAAAABDcxOTgIAAAAAAUxMjQwNBEAAAAABTEyNDI3DgAAAAAFMTI0MjgOAAAAAAUxMjQyOQ4AAAAABTEyNDMwDgAAAAAFMTI0MzEOAAAAABtTb2NpYWxMaXN0ZW5pbmdTZXR1cFZpc2libGUCAAAAABZTb2NpYWxMaXN0ZW5pbmdWaXNpYmxlAgAAAAAYT3BlbkFwcHJvdmFsRW50cmllc0V4aXN0AgAAAAAaQ2FuQ2FuY2VsQXBwcm92YWxGb3JSZWNvcmQCAAAAAA5Qb3dlckJJVmlzaWJsZQIAAAAADVJlc3luY1Zpc2libGUCAAAAABlDYW5SZXF1ZXN0QXBwcm92YWxGb3JGbG93AgAAAAAYQ2FuQ2FuY2VsQXBwcm92YWxGb3JGbG93AgAAAAAQQ29udHJvbDMyX0Zvcm1hdBEAAAAAEENvbnRyb2wzNF9Gb3JtYXQRAAAAAAEAAAACFQAAABcAAAACewU2ADIAMAAwADAAAAAAAAJu6QgAAAAAAAIFNjIwMDACH9CX0JDQniAi0KHQv9C+0YDRgtC80LDRgdGC0LXRgCICH9CX0JDQniAi0KHQn9Ce0KDQotCc0JDQodCi0JXQoCICAAIi0YPQuy4g0JHQvtGC0LDQvdC40YfQtdGB0LrQsNGPLCA0NAIAAgzQnNC+0YHQutCy0LACAAIAAgACAAIAAgACAAIAAAAAAAAAAAAAAAAAAAAAAgc2MC0xMDEwAgACAAIAAAAAAgTQndCfAgACBNCS0JUCEtCh0KIu0Jgg0KTQoNCQ0KXQogIAAgU2MjAwMAIAAgAAAAACAAIDAAAAAgACgCvjUDst1wgBAAAAAgAAQwDdLNcIAgAAAAIAAAAAAgACAAIAAgACDNCR0JjQl9Cd0JXQoQACAAIGMTAzMDU0AgACAAIAAgACAAIAAg7Qn9Ce0JrQo9Cf0JrQkAIAAgACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAgEAAAAAAgACAAIAAgACAAIAAgzQnNCe0KHQmtCS0JACCtCR0JXQm9Cr0JkCAAIAAgACAAJZjbo/4WEPQISpaIdh4YfYAgAAAAAAAAAAAAAAAAAAAAACL87I70jmXk6sfXy+RoMLVQIAAAAAAAAAAAAAAAAAAAAAAgACAAIAAgACAAIAAgACAAIAAgAAAAACAAAAAAIAAgAAAAACAAIAAgAAAAACCdCf0J7Qmi0wMgAAAAAAAAACAAIAAAAAAAAAAAAAAAAAAAAAAjQMWwQAAAAAAAAAAAAAAQACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACNAxbBAAAAAAAAAAAAAABAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAIAAAAAAgAAAAACAAAAAAIAAAAAAgAAAAACAAAAAAIAAAAAAgAAAAACAAAAAAIAAAAAAgAAAAACAAAAAAIAAAAAAgAAAAACAAAAAAIAAAAAAgAAAAACAAAAAAIAAAAAAgAAAAACAAAAAAIAAAAAAgAAAAACAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAIAAgACAAIBAgACAAIAAggjLCMjMC4wMAIIIywjIzAuMDA=";
                byte[] DataSet_cf_1 = Convert.FromBase64String(DataSet_str_cf_1);

                NavDataSet NavDataSet_cf_1 = new NavDataSet { DataSetName = "NewDataSet" };

                var datasetdata_cf_1 = NavDataSet_cf_1.GetType().GetProperty("DataSet", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public).GetValue(NavDataSet_cf_1);
                datasetdata_cf_1.GetType().GetProperty("Data", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public).SetValue(datasetdata_cf_1, DataSet_cf_1);
                NavDataSet_cf_1.GetType().GetProperty("DataSet", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public).SetValue(NavDataSet_cf_1, datasetdata_cf_1);

                ncfa_3_mf.DataSet = NavDataSet_cf_1;
                //************************************

                service.CloseForm(
                    ref ncfa_3_mf,
                    ref ncfa_3_sf,
                    force: false);
            }

            a9("CloseForm                 ", sw_30, sw_31, (short)11); sw_31.Stop();
            //==============================================
            //  ValidateField
            //NavRecordState iam_s_2 = nofa_3_mf.State;
            //NavDataSet iam_nds_2 = nofa_3_mf.DataSet;

            //NavRecordState iam_s_3 = nofa_3_sf[0].State;
            //NavDataSet iam_nds_3 = nofa_3_sf[0].DataSet;

            //NavRecordState iam_s_4 = nofa_3_sf[1].State;
            //NavDataSet iam_nds_4 = nofa_3_sf[1].DataSet;

            ////************************************
            ////       DATA FIELD CORRELATION
            //string DataSet_str_vf_1 = "B2RhdGFTZXR/AAAAAQAAAA9QdXJjaGFzZSBIZWFkZXIJBAAAswAAAAEwCgAAAAAIYm9va21hcmsTAAAAAAExCAAAAAABMhEAAAAAATMRAAAAAAE0EQAAAAABNREAAAAAATYRAAAAAAE3EQAAAAABOBEAAAAAATkRAAAAAAIxMBEAAAAAAjExEQAAAAACMTIRAAAAAAIxMxEAAAAAAjE0EQAAAAACMTURAAAAAAIxNhEAAAAAAjE3EQAAAAACMTgRAAAAAAIxOQ8AAAAAAjIwDwAAAAACMjEPAAAAAAIyMhEAAAAAAjIzEQAAAAACMjQPAAAAAAIyNQ4AAAAAAjI2DwAAAAACMjcRAAAAAAIyOBEAAAAAAjI5EQAAAAACMzARAAAAAAIzMREAAAAAAjMyEQAAAAACMzMOAAAAAAIzNQIAAAAAAjM3EQAAAAACNDERAAAAAAI0MxEAAAAAAjQ1EQAAAAACNDYCAAAAAAI0NwgAAAAAAjUxEQAAAAACNTIIAAAAAAI1MxEAAAAAAjU1EQAAAAACNTYCAAAAAAI1NwIAAAAAAjU4AgAAAAACNTkCAAAAAAI2MA4AAAAAAjYxDgAAAAACNjIRAAAAAAI2MxEAAAAAAjY0EQAAAAACNjURAAAAAAI2NhEAAAAAAjY3EQAAAAACNjgRAAAAAAI2OREAAAAAAjcwEQAAAAACNzIRAAAAAAI3MxEAAAAAAjc0EQAAAAACNzYRAAAAAAI3NxEAAAAAAjc4EQAAAAACNzkRAAAAAAI4MBEAAAAAAjgxEQAAAAACODIRAAAAAAI4MxEAAAAAAjg0EQAAAAACODURAAAAAAI4NhEAAAAAAjg3EQAAAAACODgRAAAAAAI4OREAAAAAAjkwEQAAAAACOTERAAAAAAI5MhEAAAAAAjkzEQAAAAACOTQIAAAAAAI5NREAAAAAAjk3EQAAAAACOTgCAAAAAAI5OQ8AAAAAAzEwMREAAAAAAzEwMhEAAAAAAzEwNBEAAAAAAzEwNxEAAAAAAzEwOBEAAAAAAzEwOREAAAAAAzExNBEAAAAAAzExNQIAAAAAAzExNhEAAAAAAzExOBEAAAAAAzExOQ4AAAAAAzEyMAgAAAAAAzEyMQgAAAAAAzEyMg4AAAAAAzEyMwIAAAAAAzEyNAgAAAAAAzEyNREAAAAAAzEyNhEAAAAAAzEyOQgAAAAAAzEzMBEAAAAAAzEzMREAAAAAAzEzMhEAAAAAAzEzMxEAAAAAAzEzNA4AAAAAAzEzNREAAAAAAzEzNgIAAAAAAzEzNw8AAAAAAzEzOBEAAAAAAzEzOREAAAAAAzE0Mg8AAAAAAzE0MxEAAAAAAzE0NA4AAAAAAzE1MREAAAAAAzE2MAgAAAAAAzE2MRIAAAAAAzE2NQgAAAAAAzE3MBEAAAAAAzE3MREAAAAAAzMwMA4AAAAAAzMwMQ4AAAAAAzQ4MAgAAAAABDEzMDUOAAAAAAQ1MDQzCAAAAAAENTA0OAgAAAAABDUwNTARAAAAAAQ1MDUyEQAAAAAENTA1MxEAAAAABDU3MDARAAAAAAQ1NzUxAgAAAAAENTc1MgIAAAAABDU3NTMIAAAAAAQ1NzkwDwAAAAAENTc5MQ8AAAAABDU3OTIRAAAAAAQ1NzkzEQAAAAAENTgwMBEAAAAABDU4MDERAAAAAAQ1ODAyEQAAAAAENTgwMwIAAAAABDU4MDQRAAAAAAQ4MDAwEgAAAAAEOTAwMBEAAAAABDkwMDEIAAAAAAUxMjQwMAIAAAAABTEyNDAxEQAAAAAFMTI0MDIRAAAAAAUxMjQwMwgAAAAABTEyNDA0AgAAAAAFMTI0MzcIAAAAAAUxMjQzOAgAAAAABTEyNDQwAgAAAAAFMTI0NDEIAAAAAAUxMjQ0MhEAAAAABTEyNDQzCAAAAAAFMTI0NDQRAAAAAAUxMjQ0NREAAAAABTEyNDQ2CAAAAAAFMTI0NDcRAAAAAAUxMjQ3MBEAAAAABTEyNDcxDwAAAAAFMTI0NzIPAAAAAAUxMjQ3Mw8AAAAABTEyNDc0EQAAAAAFMTI0ODAOAAAAAAUxMjQ4NREAAAAABTEyNDg2AgAAAAAFMTI0OTARAAAAAAUxMjQ5MREAAAAABTEyNDk4AgAAAAAFMTI0OTkPAAAAAAQ1NzU0EQAAAAAENTc5NhEAAAAAAgAAAAKpmg0AAAAAAAIrAAAAJgAAAACLAgAAAAJ7/x8EHgQQBBIELQAyADEALQAwADAAMAAzADQAAAAAAAICAAAAAgACEdCf0J7QkNCSLTIxLTAwMDM0AgACAAIAAgACAAIAAgACAAIAAhpDUk9OVVMg0KDQvtGB0YHQuNGPINCX0JDQngIAAgvQoNC40L3QsywgNQIAAgzQnNC+0YHQutCy0LACAAIAQABTjcHYCAIAAAACAEAAU43B2AgCAAAAAgBAAFONwdgIAgAAAAIZSW52b2ljZSDQn9Ce0JDQki0yMS0wMDAzNAIAAgAAAAAAAAAAAgAAAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAgAAAAIAAgACAAIAAgACAAIAAAAAAAAAAAAAAAAAAAAAAgACAAIAAgACAAIAAgAAAAACAAIAAAAAAgACAAIAAgACAAIAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAIR0J/QntCQ0JItMjEtMDAwMzQCEdCf0J7QkNCSLTIxLTAwMDM0AgACAAIAAgACEdCf0J7QkNCSLTIxLTAwMDM0AgACAAIAAgACAAIAAgACAAIFNjIwMDACAAIAAgACAAIAAgACAAIAAgACAAIAAgYxMDMwNTQCAAICUlUCAAAAAAIAAgACAAIAQABTjcHYCAIAAAACAAIAAgACCdCf0J7Qmi0yMAIJ0J/QntCaLTIwAgnQn9Ce0JotMTUCAAIAAgACAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAACAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgACAAAAAAIAAgACAAAAAAIAAgACAAIAAgAAAAAAAAAAAAAAAAAAAAACAAIBAgAAAAAAAAAAAgAAAAIAAgACAAAAAAAAAAACAAAAAgACAAAAAAAAAAAAAAAAAAAAAAIAAgAAAAACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAgACAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAACAQAAAAIAAgACAAIAAgACAAIAAAAAAgAAAAAAAAAAAgAAAAIAAAAAAAAAAAIAAAACAAIAAgACAAIAAgACAAKs0IGOx9pzSZIoLF1gkGW/AgACAAAAAAIBAgACAAIAAAAAAgACAAAAAAIAAAAAAgACAAAAAAIAAgAAAAACAAIAAgAAAAACAAIAAgAAAAAAAAAAAgAAAAIAAAAAAAAAAAIAAAACAAAAAAAAAAACAAAAAgACAAAAAAAAAAAAAAAAAAAAAAIAAgACAAIAAgACAAAAAAAAAAACAAAAAAACqZoNAAAAAAACKwAAACYAAAAAiwIAAAACe/8fBB4EEAQSBC0AMgAxAC0AMAAwADAAMwA0AAAAAAACAgAAAAIAAhHQn9Ce0JDQki0yMS0wMDAzNAIAAgACAAIAAgACAAIAAgACAAIaQ1JPTlVTINCg0L7RgdGB0LjRjyDQl9CQ0J4CAAIL0KDQuNC90LMsIDUCAAIM0JzQvtGB0LrQstCwAgACAEAAU43B2AgCAAAAAgBAAFONwdgIAgAAAAIAQABTjcHYCAIAAAACGUludm9pY2Ug0J/QntCQ0JItMjEtMDAwMzQCAAIAAAAAAAAAAAIAAAACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAIAAAACAAIAAgACAAIAAgACAAAAAAAAAAAAAAAAAAAAAAIAAgACAAIAAgACAAIAAAAAAgACAAAAAAIAAgACAAIAAgACAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACEdCf0J7QkNCSLTIxLTAwMDM0AhHQn9Ce0JDQki0yMS0wMDAzNAIAAgACAAIAAhHQn9Ce0JDQki0yMS0wMDAzNAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACBjEwMzA1NAIAAgJSVQIAAAAAAgACAAIAAgBAAFONwdgIAgAAAAIAAgACAAIJ0J/QntCaLTIwAgnQn9Ce0JotMjACCdCf0J7Qmi0xNQIAAgACAAIAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAIAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAIAAAAAAgACAAIAAAAAAgACAAIAAgACAAAAAAAAAAAAAAAAAAAAAAIAAgECAAAAAAAAAAACAAAAAgACAAIAAAAAAAAAAAIAAAACAAIAAAAAAAAAAAAAAAAAAAAAAgACAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAACAAIAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAIBAAAAAgACAAIAAgACAAIAAgAAAAACAAAAAAAAAAACAAAAAgAAAAAAAAAAAgAAAAIAAgACAAIAAgACAAIAAqzQgY7H2nNJkigsXWCQZb8CAAIAAAAAAgECAAIAAgAAAAACAAIAAAAAAgAAAAACAAIAAAAAAgACAAAAAAIAAgACAAAAAAIAAgACAAAAAAAAAAACAAAAAgAAAAAAAAAAAgAAAAIAAAAAAAAAAAIAAAACAAIAAAAAAAAAAAAAAAAAAAAAAgACAAIAAgACAAIAAAAAAAAAAAIAAAAAAA==";
            //byte[] DataSet_vf_1 = Convert.FromBase64String(DataSet_str_vf_1);

            //NavDataSet NavDataSet_2 = new NavDataSet { DataSetName = "NewDataSet" };

            //var datasetdata_2 = NavDataSet_2.GetType().GetProperty("DataSet", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public).GetValue(NavDataSet_2);
            //datasetdata_2.GetType().GetProperty("Data", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public).SetValue(datasetdata_2, DataSet_vf_1);
            //NavDataSet_2.GetType().GetProperty("DataSet", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public).SetValue(NavDataSet_2, datasetdata_2);

            //iam_nds_2 = NavDataSet_2;

            ////************************************

            //service.ValidateField(state: ref iam_s_2, recDataSet: iam_nds_2, 1210014); 

            //a9("ValidateField", sw_1, sw_2);

            //==============================================
            //  MODIFY RECORD
            //service.ModifyRecord(state: ref iam_s_2, recDataSet: iam_nds_2);    

            //a9("ModifyRecord", sw_1, sw_2);


            //==============================================
            //  GetPage

            //==============================================
            //  GetPage

            //==============================================
            //  lnvokeApplicationMethod
            //NavVisualizationHelper.Initialize(service);
            //service.InvokeApplicationMethod(objectType: ApplicationCodeType.FormCode, objectId: iam_s_fid_2, methodName: "NewRecord", dataSet: ref iam_nds_2, state: ref iam_s_2, args: ref iam_obj_1);


            //==============================================
            //  lnvokeApplicationMethod
            //NavVisualizationHelper.Initialize(service);
            //service.InvokeApplicationMethod(objectType: ApplicationCodeType.FormCode, objectId: iam_s_fid_2, methodName: "NewRecord", dataSet: ref iam_nds_2, state: ref iam_s_2, args: ref iam_obj_1);


            //==============================================
            //  lnvokeApplicationMethod
            //NavVisualizationHelper.Initialize(service);
            //service.InvokeApplicationMethod(objectType: ApplicationCodeType.FormCode, objectId: iam_s_fid_2, methodName: "NewRecord", dataSet: ref iam_nds_2, state: ref iam_s_2, args: ref iam_obj_1);



            //==============================================
            //  GetPage

            //==============================================
            //  ValidateField

            //==============================================
            //  INSERT RECORD

            //==============================================
            //  GetTableMetadata

            //==============================================
            //  GetMetadataForPageAndAllItsDependencies

            //==============================================
            //  OpenForm

            //==============================================
            //  GetPage

            //==============================================
            //  GetPage

            //==============================================
            //  CloseForm

            //==============================================
            //  Evaluate

            //==============================================
            //  ValidateField

            //==============================================
            //  Evaluate

            //==============================================
            //  ValidateField

            //==============================================
            //  MODIFY RECORD

            //==============================================
            //  CloseForm
            sw_50.Start();

            {
                NavCloseFormArguments ncfa_2_mf = new NavCloseFormArguments()
                {
                    ExitAction = FormResult.OK,
                    DataSet = nofa_2_mf.DataSet,
                    State = nofa_2_mf.State
                };

                NavCloseFormArguments[] ncfa_2_sf = nofa_2_sf
                    .Select(sf => new NavCloseFormArguments() { DataSet = sf.DataSet, State = sf.State, ExitAction = FormResult.None })
                    .ToArray();

                //************************************
                //       DATA FIELD CORRELATION
                string DataSet_str_cf_2 = "Ck5ld0RhdGFTZXR/AAAAAgAAAAEwCQQAALMAAAABMAoAAAAACGJvb2ttYXJrEwAAAAABMQgAAAAAATIRAAAAAAEzEQAAAAABNBEAAAAAATURAAAAAAE2EQAAAAABNxEAAAAAATgRAAAAAAE5EQAAAAACMTARAAAAAAIxMREAAAAAAjEyEQAAAAACMTMRAAAAAAIxNBEAAAAAAjE1EQAAAAACMTYRAAAAAAIxNxEAAAAAAjE4EQAAAAACMTkPAAAAAAIyMA8AAAAAAjIxDwAAAAACMjIRAAAAAAIyMxEAAAAAAjI0DwAAAAACMjUOAAAAAAIyNg8AAAAAAjI3EQAAAAACMjgRAAAAAAIyOREAAAAAAjMwEQAAAAACMzERAAAAAAIzMhEAAAAAAjMzDgAAAAACMzUCAAAAAAIzNxEAAAAAAjQxEQAAAAACNDMRAAAAAAI0NREAAAAAAjQ2AgAAAAACNDcIAAAAAAI1MREAAAAAAjUyCAAAAAACNTMRAAAAAAI1NREAAAAAAjU2AgAAAAACNTcCAAAAAAI1OAIAAAAAAjU5AgAAAAACNjAOAAAAAAI2MQ4AAAAAAjYyEQAAAAACNjMRAAAAAAI2NBEAAAAAAjY1EQAAAAACNjYRAAAAAAI2NxEAAAAAAjY4EQAAAAACNjkRAAAAAAI3MBEAAAAAAjcyEQAAAAACNzMRAAAAAAI3NBEAAAAAAjc2EQAAAAACNzcRAAAAAAI3OBEAAAAAAjc5EQAAAAACODARAAAAAAI4MREAAAAAAjgyEQAAAAACODMRAAAAAAI4NBEAAAAAAjg1EQAAAAACODYRAAAAAAI4NxEAAAAAAjg4EQAAAAACODkRAAAAAAI5MBEAAAAAAjkxEQAAAAACOTIRAAAAAAI5MxEAAAAAAjk0CAAAAAACOTURAAAAAAI5NxEAAAAAAjk4AgAAAAACOTkPAAAAAAMxMDERAAAAAAMxMDIRAAAAAAMxMDQRAAAAAAMxMDcRAAAAAAMxMDgRAAAAAAMxMDkRAAAAAAMxMTQRAAAAAAMxMTUCAAAAAAMxMTYRAAAAAAMxMTgRAAAAAAMxMTkOAAAAAAMxMjAIAAAAAAMxMjEIAAAAAAMxMjIOAAAAAAMxMjMCAAAAAAMxMjQIAAAAAAMxMjURAAAAAAMxMjYRAAAAAAMxMjkIAAAAAAMxMzARAAAAAAMxMzERAAAAAAMxMzIRAAAAAAMxMzMRAAAAAAMxMzQOAAAAAAMxMzURAAAAAAMxMzYCAAAAAAMxMzcPAAAAAAMxMzgRAAAAAAMxMzkRAAAAAAMxNDIPAAAAAAMxNDMRAAAAAAMxNDQOAAAAAAMxNTERAAAAAAMxNjAIAAAAAAMxNjESAAAAAAMxNjUIAAAAAAMxNzARAAAAAAMxNzERAAAAAAMzMDAOAAAAAAMzMDEOAAAAAAM0ODAIAAAAAAQxMzA1DgAAAAAENTA0MwgAAAAABDUwNDgIAAAAAAQ1MDUwEQAAAAAENTA1MhEAAAAABDUwNTMRAAAAAAQ1NzAwEQAAAAAENTc1MQIAAAAABDU3NTICAAAAAAQ1NzUzCAAAAAAENTc5MA8AAAAABDU3OTEPAAAAAAQ1NzkyEQAAAAAENTc5MxEAAAAABDU4MDARAAAAAAQ1ODAxEQAAAAAENTgwMhEAAAAABDU4MDMCAAAAAAQ1ODA0EQAAAAAEODAwMBIAAAAABDkwMDARAAAAAAQ5MDAxCAAAAAAFMTI0MDACAAAAAAUxMjQwMREAAAAABTEyNDAyEQAAAAAFMTI0MDMIAAAAAAUxMjQwNAIAAAAABTEyNDM3CAAAAAAFMTI0MzgIAAAAAAUxMjQ0MAIAAAAABTEyNDQxCAAAAAAFMTI0NDIRAAAAAAUxMjQ0MwgAAAAABTEyNDQ0EQAAAAAFMTI0NDURAAAAAAUxMjQ0NggAAAAABTEyNDQ3EQAAAAAFMTI0NzARAAAAAAUxMjQ3MQ8AAAAABTEyNDcyDwAAAAAFMTI0NzMPAAAAAAUxMjQ3NBEAAAAABTEyNDgwDgAAAAAFMTI0ODURAAAAAAUxMjQ4NgIAAAAABTEyNDkwEQAAAAAFMTI0OTERAAAAAAUxMjQ5OAIAAAAABTEyNDk5DwAAAAAENTc1NBEAAAAABDU3OTYRAAAAAAExCQQAAOsAAAABMAoAAAAACGJvb2ttYXJrEwAAAAABMQgAAAAAATIRAAAAAAEzEQAAAAABNAgAAAAAATUIAAAAAAE2EQAAAAABNxEAAAAAATgRAAAAAAIxMA8AAAAAAjExEQAAAAACMTIRAAAAAAIxMxEAAAAAAjE1DgAAAAACMTYOAAAAAAIxNw4AAAAAAjE4DgAAAAACMjIOAAAAAAIyMw4AAAAAAjI1DgAAAAACMjcOAAAAAAIyOA4AAAAAAjI5DgAAAAACMzAOAAAAAAIzMQ4AAAAAAjMyAgAAAAACMzQOAAAAAAIzNQ4AAAAAAjM2DgAAAAACMzcOAAAAAAIzOAgAAAAAAjQwEQAAAAACNDERAAAAAAI0NREAAAAAAjU0DgAAAAACNTYCAAAAAAI1Nw4AAAAAAjU4DgAAAAACNTkOAAAAAAI2MA4AAAAAAjYxDgAAAAACNjMRAAAAAAI2NAgAAAAAAjY3DgAAAAACNjgRAAAAAAI2OQ4AAAAAAjcwEQAAAAACNzERAAAAAAI3MggAAAAAAjczAgAAAAACNzQRAAAAAAI3NREAAAAAAjc3CAAAAAACNzgRAAAAAAI3OREAAAAAAjgwCAAAAAACODERAAAAAAI4MhEAAAAAAjgzEQAAAAACODURAAAAAAI4NgIAAAAAAjg3EQAAAAACODgCAAAAAAI4OREAAAAAAjkwEQAAAAACOTERAAAAAAI5Mg4AAAAAAjkzDgAAAAACOTUOAAAAAAI5NxEAAAAAAjk4CAAAAAACOTkOAAAAAAMxMDAOAAAAAAMxMDECAAAAAAMxMDMOAAAAAAMxMDQOAAAAAAMxMDUOAAAAAAMxMDYRAAAAAAMxMDcIAAAAAAMxMDgRAAAAAAMxMDkOAAAAAAMxMTAOAAAAAAMxMTEOAAAAAAMxMTIOAAAAAAMxMTMOAAAAAAMxMTQOAAAAAAMxMTUOAAAAAAMxMTYIAAAAAAMxMTcRAAAAAAMxMTgRAAAAAAMxMTkCAAAAAAMxMjARAAAAAAMxMjEOAAAAAAMxMjIOAAAAAAMxMjMCAAAAAAMxMjQOAAAAAAMxMjkOAAAAAAMxMzARAAAAAAMxMzIOAAAAAAMxMzUOAAAAAAMxMzYOAAAAAAMxMzcOAAAAAAMxNDAOAAAAAAMxNDEOAAAAAAM0ODAIAAAAAAQxMDAxEQAAAAAEMTAwMggAAAAABDEwMDMOAAAAAAQxMDA0DgAAAAAEMTAwNQ4AAAAABDEwMDYOAAAAAAQxMDA3DgAAAAAEMTAwOA4AAAAABDEwMDkOAAAAAAQxMDEwDgAAAAAEMTAxMQ4AAAAABDEwMTIOAAAAAAQxMDEzEQAAAAAEMTAxOQgAAAAABDEwMzAOAAAAAAQxMDMxDgAAAAAEMTcwMBEAAAAABDE3MDIPAAAAAAQ1NDAxEQAAAAAENTQwMhEAAAAABDU0MDMRAAAAAAQ1NDA0DgAAAAAENTQwNxEAAAAABDU0MTUOAAAAAAQ1NDE2DgAAAAAENTQxNw4AAAAABDU0MTgOAAAAAAQ1NDU4DgAAAAAENTQ2MA4AAAAABDU0NjEOAAAAAAQ1NDk1DgAAAAAENTYwMA8AAAAABDU2MDEIAAAAAAQ1NjAyEQAAAAAENTYwMw4AAAAABDU2MDUCAAAAAAQ1NjA2AgAAAAAENTYwOREAAAAABDU2MTARAAAAAAQ1NjExEQAAAAAENTYxMhEAAAAABDU2MTMCAAAAAAQ1NzAwEQAAAAAENTcwNREAAAAABDU3MDYRAAAAAAQ1NzA3CAAAAAAENTcwOBEAAAAABDU3MDkRAAAAAAQ1NzEwAgAAAAAENTcxMREAAAAABDU3MTIRAAAAAAQ1NzEzAgAAAAAENTcxNBEAAAAABDU3MTUIAAAAAAQ1NzUwDgAAAAAENTc1MgIAAAAABDU3OTAPAAAAAAQ1NzkxDwAAAAAENTc5MhEAAAAABDU3OTMRAAAAAAQ1Nzk0DwAAAAAENTc5NQ8AAAAABDU4MDACAAAAAAQ1ODAxDgAAAAAENTgwMg4AAAAABDU4MDMOAAAAAAQ1ODA0DgAAAAAENTgwNQ4AAAAABDU4MDYOAAAAAAQ1ODA3DgAAAAAENTgwOA4AAAAABDU4MDkOAAAAAAQ1ODEwDgAAAAAENjYwMBEAAAAABDY2MDEIAAAAAAQ2NjA4EQAAAAAENjYwOQgAAAAABDY2MTACAAAAAAUxMjQwMBEAAAAABTEyNDAxCAAAAAAFMTI0MDIPAAAAAAUxMjQwMxEAAAAABTEyNDA0EQAAAAAFMTI0MDURAAAAAAUxMjQzMA4AAAAABTEyNDMxDgAAAAAFMTI0ODUCAAAAAAUxMjQ4NhEAAAAABTEyNDg3AgAAAAAFMTI0OTARAAAAAAUxNzMwMBEAAAAACDk5MDAwNzUwEQAAAAAIOTkwMDA3NTERAAAAAAg5OTAwMDc1MhEAAAAACDk5MDAwNzUzAgAAAAAIOTkwMDA3NTQIAAAAAAg5OTAwMDc1NQ4AAAAACDk5MDAwNzU2AgAAAAAIOTkwMDA3NTcIAAAAAAg5OTAwMDc1OBEAAAAACDk5MDAwNzU5CAAAAAAVQ29udHJvbDEyMTAwMzFfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwMzdfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwMzlfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwNDFfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwNDNfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwNDVfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwNDdfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwNDlfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwNTNfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwNTdfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwNTlfRm9ybWF0EQAAAAAOQ29udHJvbDEyMTAwOTERAAAAAA5Db250cm9sMTIxMDA5MxEAAAAADkNvbnRyb2wxMjEwMDk1EQAAAAAOQ29udHJvbDEyMTAwOTcRAAAAAA5Db250cm9sMTIxMDA5OREAAAAADkNvbnRyb2wxMjEwMTAxEQAAAAAdQ29udHJvbDEyMTAwMDdfRHluYW1pY0NhcHRpb24RAAAAAB1Db250cm9sMTIxMDAzN19EeW5hbWljQ2FwdGlvbhEAAAAAHUNvbnRyb2wxMjEwMDQ1X0R5bmFtaWNDYXB0aW9uEQAAAAAdQ29udHJvbDEyMTAwODdfRHluYW1pY0NhcHRpb24RAAAAAB1Db250cm9sMTIxMDA4OV9EeW5hbWljQ2FwdGlvbhEAAAAAHUNvbnRyb2wxMjEwMDkxX0R5bmFtaWNDYXB0aW9uEQAAAAAdQ29udHJvbDEyMTAwOTNfRHluYW1pY0NhcHRpb24RAAAAAB1Db250cm9sMTIxMDA5NV9EeW5hbWljQ2FwdGlvbhEAAAAAHUNvbnRyb2wxMjEwMDk3X0R5bmFtaWNDYXB0aW9uEQAAAAAdQ29udHJvbDEyMTAwOTlfRHluYW1pY0NhcHRpb24RAAAAAB1Db250cm9sMTIxMDEwMV9EeW5hbWljQ2FwdGlvbhEAAAAAAQAAAAKvmg0AAAAAAAIrAAAAJgAAAACLAgAAAAJ7/x8EHgQQBBIELQAyADEALQAwADAAMAAzADQAAAAAAAICAAAAAgU2MjAwMAIR0J/QntCQ0JItMjEtMDAwMzQCBTYyMDAwAh/Ql9CQ0J4gItCh0L/QvtGA0YLQvNCw0YHRgtC10YAiAgACItGD0LsuINCR0L7RgtCw0L3QuNGH0LXRgdC60LDRjywgNDQCAAIM0JzQvtGB0LrQstCwAgACAAIAAhXQkdC10LvRi9C5INGB0LrQu9Cw0LQCAAIW0YPQuy4g0JvQtdC90LjQvdCwLCAzNAIAAh3QndC40LbQvdC40Lkg0J3QvtCy0LPQvtGA0L7QtAIAAgBAAFONwdgIAgAAAAIAQABTjcHYCAIAAAACAEAAU43B2AgCAAAAAhlJbnZvaWNlINCf0J7QkNCSLTIxLTAwMDM0AgTQndCfAgBAAFONwdgIAgAAAAIAAAAAAAAAAAAAAAAAAAAAAgBAAFONwdgIAgAAAAIS0KHQoi7QmCDQpNCg0JDQpdCiAgrQkdCV0JvQq9CZAgACAAIHNjAtMTAxMAIAAgAAAAAAAAAAAAAAAAAAAAACAAIFNjIwMDACAAIE0JLQlQIAAgACAAAAAAIAAgAAAAACAAIAAgACAAIAAgACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAhHQn9Ce0JDQki0yMS0wMDAzNAIR0J/QntCQ0JItMjEtMDAwMzQCAAIAAgACAAIR0J/QntCQ0JItMjEtMDAwMzQCAAIAAgACAAIM0JHQmNCX0J3QldChAgACAAIAAh/Ql9CQ0J4gItCh0L/QvtGA0YLQvNCw0YHRgtC10YAiAgACItGD0LsuINCR0L7RgtCw0L3QuNGH0LXRgdC60LDRjywgNDQCAAIM0JzQvtGB0LrQstCwAgACBjEwMzA1NAIAAgACBjEwMzA1NAIAAgACBjYwMzA2MQIAAgJSVQIAAAAAAgACAAIAAgBAAFONwdgIAgAAAAIAAgACAAIJ0J/QntCaLTIwAgnQn9Ce0JotMjACCdCf0J7Qmi0xNQIAAgACDtCf0J7QmtCj0J/QmtCQAgACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAgAAAAACAAAAAAAAAAAAAAAAAAAAAAIAAgAAAAACAAIAAgAAAAACAAIAAgACAAIAAAAAAAAAAAAAAAAAAAAAAgACAQIAQABTjcHYCAIAAAACAAIAAgBAAFONwdgIAgAAAAIE0J3QnwIAAAAAAAAAAAAAAAAAAAAAAgACAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAACAAIAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAIkAAAAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAIBAAAAAgACCENUMDAwMzQ3AghDVDAwMDM0NwIM0JzQntCh0JrQktCQAgACAAIAAAAAAgAAAAAAAAAAAgAAAAIAAAAAAAAAAAIAAAACAAIAAgACAAIAAgACAAKs0IGOx9pzSZIoLF1gkGW/AgACAAAAAAIBAgACAAIAAAAAAgACAAAAAAIAAAAAAgACAAAAAAIAAgAAAAACAAIAAgAAAAACAAIAAgAAAAAAAAAAAgAAAAIAAAAAAAAAAAIAAAACAAAAAAAAAAACAAAAAgACAAAAAAAAAAAAAAAAAAAAAAIAAgACAAIAAgACAAAAAAAAAAACAAAAAAABAAAAArGaDQAAAAAAAjEAAAAnAAAAAIsCAAAAAnv/HwQeBBAEEgQtADIAMQAtADAAMAAwADMANAAAAACHECcAAAAAAgIAAAACBTYyMDAwAhHQn9Ce0JDQki0yMS0wMDAzNAIQJwAAAgIAAAACCtCi0J7Qki0wMTACCtCh0JjQndCY0JkCBzQxLTEwMDACAEAAU43B2AgCAAAAAjTQmNC90YHRgi4g0YHRgtC+0LsgItCy0LXRh9C90YvQuSDQutCw0LvQtdC90LTQsNGA0YwiAgACCtCo0YLRg9C60LACZAAAAAAAAAAAAAAAAAAAAAJkAAAAAAAAAAAAAAAAAAAAAmQAAAAAAAAAAAAAAAAAAAACZAAAAAAAAAAAAAAAAAAAAAKN7wIAAAAAAAAAAAAAAAIAAo3vAgAAAAAAAAAAAAAAAgACFAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACFJMlAQAAAAAAAAAAAAACAAIYSmABAAAAAAAAAAAAAAIAAlw1AAAAAAAAAAAAAAAAAAACAQIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAACAAIAAgACAAAAAAAAAAAAAAAAAAAAAAIBAhhKYAEAAAAAAAAAAAAAAgACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAIAAgAAAAACAAAAAAAAAAAAAAAAAAAAAAIFNjIwMDACAAAAAAAAAAAAAAAAAAAAAAIAAgACAAAAAAIAAgzQkdCY0JfQndCV0KECCNCi0J7QkjIwAgAAAAACAAIAAgAAAAACAAIAAgACAAIAAgACAAIO0J/QntCa0KPQn9Ca0JACCNCi0J7QkjIwAgACGEpgAQAAAAAAAAAAAAACAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAIAAAAAAhSTJQEAAAAAAAAAAAAAAgACje8CAAAAAAAAAAAAAAACAAIAAhSTJQEAAAAAAAAAAAAAAgACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgjQotCe0JIyMAIAAAAAAgACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAgACAAIAAgACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAIUkyUBAAAAAAAAAAAAAAIAAgAAAAAAAAAAAAAAAAAAAAACJAAAAAIAAgAAAAACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAIAAgAAAAACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgACAAAAAAAAAAACAAAAAgACAAIAAgEAAAAAAAAAAAAAAAAAAAACBNCo0KICgJaYAAAAAAAAAAAAAAAFAAKAlpgAAAAAAAAAAAAAAAUAAoCWmAAAAAAAAAAAAAAABQACgJaYAAAAAAAAAAAAAAAFAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAgAAAAIAAAAAAgACAAAAAAAAAAAAAAAAAAAAAAIAAgACAAIAAgACAAIAAgzQnNCe0KHQmtCS0JACAAIAAgAAAAACAAIAAgACAAIAAgACAAIAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAIAAAAAAAAAAAIAAAACAAAAAAAAAAACAAAAAgACAAIAgJYoxMDYCAIAAAACAICWKMTA2AgCAAAAAgECAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAIAAgAAAAACAAIAAAAAAgACAAIAAAAAAgAAAAAAAAAAAgAAAAIAAgACAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAIAAgACAAIAAgACAAIAAgACAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgACAAAAAAICMUQCAAAAAAILIywjIzAuIyMjIyMCCyMsIyMwLjAwIyMjAgsjLCMjMC4jIyMjIwILIywjIzAuMDAjIyMCCyMsIyMwLjAwIyMjAggjLCMjMC4wMAILIywjIzAuIyMjIyMCCCMsIyMwLjAwAggjLCMjMC4wMAILIywjIzAuIyMjIyMCCyMsIyMwLiMjIyMjAAAAAAAAAgNOby4CGkRpcmVjdCBVbml0IENvc3QgRXhjbC4gVkFUAhVMaW5lIEFtb3VudCBFeGNsLiBWQVQCD0RlcGFydG1lbnQgQ29kZQIV0JTQvtGF0YDQsNGB0YUg0JrQvtC0AgxQcm9qZWN0IENvZGUCEkN1c3RvbWVyZ3JvdXAgQ29kZQIJQXJlYSBDb2RlAhJCdXNpbmVzc2dyb3VwIENvZGUCEtCd0YMt0LLQuNC0INCa0L7QtAIY0J3Rgy3QvtCx0YrQtdC60YIg0JrQvtC0";
                byte[] DataSet_cf_2 = Convert.FromBase64String(DataSet_str_cf_2);

                NavDataSet NavDataSet_cf_2 = new NavDataSet { DataSetName = "NewDataSet" };

                var datasetdata_cf_2 = NavDataSet_cf_2.GetType().GetProperty("DataSet", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public).GetValue(NavDataSet_cf_2);
                datasetdata_cf_2.GetType().GetProperty("Data", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public).SetValue(datasetdata_cf_2, DataSet_cf_2);
                NavDataSet_cf_2.GetType().GetProperty("DataSet", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public).SetValue(NavDataSet_cf_2, datasetdata_cf_2);

                ncfa_2_mf.DataSet = NavDataSet_cf_2;
                //************************************

                service.CloseForm(
                    ref ncfa_2_mf,
                    ref ncfa_2_sf,
                    force: false);
            }

            a9("CloseForm - 12431         ", sw_50, sw_51, (short)11);

            //==============================================
            //  CloseForm
            {
                NavCloseFormArguments ncfa_1_mf = new NavCloseFormArguments()
                {
                    ExitAction = FormResult.OK,
                    DataSet = nofa_1_mf.DataSet,
                    State = nofa_1_mf.State
                };

                NavCloseFormArguments[] ncfa_1_sf = null;

                //************************************
                //       DATA FIELD CORRELATION
                string DataSet_str_cf_3 = "Ck5ld0RhdGFTZXR/AAAAAQAAAAEwCQQAALUAAAAIYm9va21hcmsTAAAAAAEwCgAAAAABMQgAAAAAATMRAAAAAAEyEQAAAAABNBEAAAAAATURAAAAAAE2EQAAAAABNxEAAAAAATgRAAAAAAE5EQAAAAACMTARAAAAAAIxMREAAAAAAjEyEQAAAAACMTMRAAAAAAIxNBEAAAAAAjE1EQAAAAACMTYRAAAAAAIxNxEAAAAAAjE4EQAAAAACMTkPAAAAAAIyMA8AAAAAAjIxDwAAAAACMjIRAAAAAAIyMxEAAAAAAjI0DwAAAAACMjUOAAAAAAIyNg8AAAAAAjI3EQAAAAACMjgRAAAAAAIyOREAAAAAAjMwEQAAAAACMzERAAAAAAIzMhEAAAAAAjMzDgAAAAACMzUCAAAAAAIzNxEAAAAAAjQxEQAAAAACNDMRAAAAAAI0NREAAAAAAjQ3CAAAAAACNTERAAAAAAI1MggAAAAAAjUzEQAAAAACNTURAAAAAAI1NwIAAAAAAjU4AgAAAAACNTkCAAAAAAI2MhEAAAAAAjYzEQAAAAACNjQRAAAAAAI2NREAAAAAAjY2EQAAAAACNjcRAAAAAAI2OBEAAAAAAjY5EQAAAAACNzARAAAAAAI3MhEAAAAAAjczEQAAAAACNzQRAAAAAAI3NhEAAAAAAjc3EQAAAAACNzgRAAAAAAI3OREAAAAAAjgwEQAAAAACODERAAAAAAI4MhEAAAAAAjgzEQAAAAACODQRAAAAAAI4NREAAAAAAjg2EQAAAAACODcRAAAAAAI4OBEAAAAAAjg5EQAAAAACOTARAAAAAAI5MREAAAAAAjkyEQAAAAACOTMRAAAAAAI5NAgAAAAAAjk1EQAAAAACOTcRAAAAAAI5OAIAAAAAAjk5DwAAAAADMTAxEQAAAAADMTAyEQAAAAADMTA0EQAAAAADMTA3EQAAAAADMTA4EQAAAAADMTA5EQAAAAADMTE0EQAAAAADMTE1AgAAAAADMTE2EQAAAAADMTE4EQAAAAADMTE5DgAAAAADMTIwCAAAAAADMTIxCAAAAAADMTIyDgAAAAADMTIzAgAAAAADMTI0CAAAAAADMTI1EQAAAAADMTI2EQAAAAADMTI5CAAAAAADMTMwEQAAAAADMTMxEQAAAAADMTMyEQAAAAADMTMzEQAAAAADMTM0DgAAAAADMTM1EQAAAAADMTM2AgAAAAADMTM3DwAAAAADMTM4EQAAAAADMTM5EQAAAAADMTQyDwAAAAADMTQzEQAAAAADMTQ0DgAAAAADMTUxEQAAAAADMTYwCAAAAAADMTYxEgAAAAADMTY1CAAAAAADMTcwEQAAAAADMTcxEQAAAAADNDgwCAAAAAAENTA0OAgAAAAABDUwNTARAAAAAAQ1MDUyEQAAAAAENTA1MxEAAAAABDU3MDARAAAAAAQ1NzUzCAAAAAAENTc5MA8AAAAABDU3OTEPAAAAAAQ1NzkyEQAAAAAENTc5MxEAAAAABDU4MDARAAAAAAQ1ODAxEQAAAAAENTgwMhEAAAAABDU4MDMCAAAAAAQ1ODA0EQAAAAAEODAwMBIAAAAABDkwMDARAAAAAAUxMjQwMAIAAAAABTEyNDAxEQAAAAAFMTI0MDIRAAAAAAUxMjQwMwgAAAAABTEyNDA0AgAAAAAFMTI0MzcIAAAAAAUxMjQzOAgAAAAABTEyNDQwAgAAAAAFMTI0NDEIAAAAAAUxMjQ0MhEAAAAABTEyNDQzCAAAAAAFMTI0NDQRAAAAAAUxMjQ0NREAAAAABTEyNDQ2CAAAAAAFMTI0NDcRAAAAAAUxMjQ3MBEAAAAABTEyNDcxDwAAAAAFMTI0NzIPAAAAAAUxMjQ3Mw8AAAAABTEyNDc0EQAAAAAFMTI0ODURAAAAAAUxMjQ4NgIAAAAABTEyNDkwEQAAAAAFMTI0OTERAAAAAAUxMjQ5OAIAAAAABTEyNDk5DwAAAAAENTc1NBEAAAAABDU3OTYPAAAAAAI0NgIAAAAAAjU2AgAAAAACNjAOAAAAAAI2MQ4AAAAAAzMwMA4AAAAAAzMwMQ4AAAAABDEzMDUOAAAAAAQ1MDQzCAAAAAAENTc1MQIAAAAABDU3NTICAAAAAAQ5MDAxCAAAAAAFMTI0ODAOAAAAABhPcGVuQXBwcm92YWxFbnRyaWVzRXhpc3QCAAAAABhDb250cm9sMTEwMjYwMTAwOV9Gb3JtYXQRAAAAAAEAAAACKwAAACYAAAAAiwIAAAACe/8fBB4EEAQSBC0AMgAxAC0AMAAwADAAMgA2AAAAAAACQJkNAAAAAAACAgAAAAIR0J/QntCQ0JItMjEtMDAwMjYCAAIAAgACAAIAAgACAAIAAgACAAIaQ1JPTlVTINCg0L7RgdGB0LjRjyDQl9CQ0J4CAAIL0KDQuNC90LMsIDUCAAIM0JzQvtGB0LrQstCwAgACAEAAU43B2AgCAAAAAgBAAFONwdgIAgAAAAIAQABTjcHYCAIAAAACGUludm9pY2Ug0J/QntCQ0JItMjEtMDAwMjYCAAIAAAAAAAAAAAIAAAACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAIAAAACAAIAAgACAAIAAgACAAAAAAAAAAAAAAAAAAAAAAIAAgACAAIAAgACAAAAAAIAAgAAAAACAAIAAgACAAIAAhHQn9Ce0JDQki0yMS0wMDAyNgIR0J/QntCQ0JItMjEtMDAwMjYCAAIAAgACAAIR0J/QntCQ0JItMjEtMDAwMjYCAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgYxMDMwNTQCAAICUlUCAAAAAAIAAgACAAIAQABTjcHYCAIAAAACAAIAAgACCdCf0J7Qmi0yMAIJ0J/QntCaLTIwAgnQn9Ce0JotMTUCAAIAAgACAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAACAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgACAAAAAAIAAgACAAAAAAIAAgACAAIAAgAAAAAAAAAAAAAAAAAAAAACAAIBAgAAAAAAAAAAAgAAAAIAAgACAAAAAAAAAAACAAAAAgACAAAAAAAAAAAAAAAAAAAAAAIAAgAAAAACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAgACAAIAAAAAAgEAAAACAAIAAgACAAIAAAAAAgAAAAAAAAAAAgAAAAIAAAAAAAAAAAIAAAACAAIAAgACAAIAAgACAAJBH4v7Xzg+TJf32lH6uKMsAgACAQIAAgACAAAAAAIAAgAAAAACAAAAAAIAAgAAAAACAAIAAAAAAgACAAIAAAAAAgACAAIAAAAAAAAAAAIAAAACAAAAAAAAAAACAAAAAgAAAAAAAAAAAgAAAAIAAgACAAIAAgACAAIAAAAAAAAAAAIAAAAAAAIAAgACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAACAAIAAgAAAAACAAAAAAAAAAAAAAAAAAAAAAIAAgsjLCMjMC4jIyMjIw==";
                byte[] DataSet_cf_3 = Convert.FromBase64String(DataSet_str_cf_3);

                NavDataSet NavDataSet_cf_3 = new NavDataSet { DataSetName = "NewDataSet" };

                var datasetdata_cf_3 = NavDataSet_cf_3.GetType().GetProperty("DataSet", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public).GetValue(NavDataSet_cf_3);
                datasetdata_cf_3.GetType().GetProperty("Data", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public).SetValue(datasetdata_cf_3, DataSet_cf_3);
                NavDataSet_cf_3.GetType().GetProperty("DataSet", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public).SetValue(NavDataSet_cf_3, datasetdata_cf_3);

                ncfa_1_mf.DataSet = NavDataSet_cf_3;
                //************************************

                service.CloseForm(
                    ref ncfa_1_mf,
                    ref ncfa_1_sf,
                    force: false);
            }

            a9("CloseForm - 35610         ", sw_51, sw_52, (short)11);

            //==============================================
            //  OpenCompany
            navWinFormsClientSession.OnExit();

            a9("CloseConnection           ", sw_52, sw_53, (short)9);

            sw_53.Stop();
            //==============================================
            //  CloseConnection

            sw_COMPLEATE.Stop();

            SetConsoleTextAttribute(GetStdHandle(-11), (short)75); Console.WriteLine("\n\n\n###### API execution time ######\t\t{0} sec", Math.Round(sw_COMPLEATE.Elapsed.TotalMilliseconds / 10000, 6, MidpointRounding.AwayFromZero));

            Console.ReadLine();

        }

        static void a9(string b, Stopwatch sw_Stop, Stopwatch sw_Start, short color)
        {


            sw_Stop.Stop();

            SetConsoleTextAttribute(GetStdHandle(-11), color);
            //Console.WriteLine(b + "\t\t\t" + sw_Stop.Elapsed.Seconds.ToString() + "\t\t\t" + sw_Stop.Elapsed.Milliseconds.ToString());
            Console.WriteLine(b + "\t\t\t" + Math.Round(sw_Stop.Elapsed.TotalMilliseconds / 10000, 4, MidpointRounding.AwayFromZero).ToString() + " sec");

            sw_Start.Start();
        }

        static byte[] returnDataByte(NavDataSet DataSet)
        {
            var DataSetRef = DataSet.GetType().GetProperty("DataSet", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public);
            var recdataset = DataSetRef.GetValue(DataSet);
            byte[] databyte = (byte[])recdataset.GetType().GetProperty("Data").GetValue(recdataset);
            return databyte;
        }

        [DllImport("kernel32.dll", SetLastError = true)]
        public static extern bool SetConsoleTextAttribute(IntPtr hConsoleOutput, short attributes);

        [DllImport("kernel32.dll", SetLastError = true)]
        public static extern IntPtr GetStdHandle(int nStdHandle);

        [DllImport("user32.dll")]
        public static extern bool ShowWindow(System.IntPtr hWnd, int cmdShow);

    }


}
