using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.Dynamics.Framework.UI;
using Microsoft.Dynamics.Nav.Client;
using Microsoft.Dynamics.Nav.Client.WinClient;
using Microsoft.Dynamics.Nav.Types.Metadata;
using Microsoft.Dynamics.Nav.Types;
using Microsoft.Dynamics.Nav.Client.Visualizations;
using Microsoft.Dynamics.Nav.Types.Data;
using System.Text.RegularExpressions;
using Microsoft.Dynamics.Nav.Client.Actions;

namespace ConsoleAppCreateAdvanseStatements
{
    public static class Encodinggg
    {
        public static string EncodeBase64(this System.Text.Encoding encoding, string text)
        {

            if (text == null)
            {
                return null;
            }

            byte[] textAsBytes = encoding.GetBytes(text);
            return System.Convert.ToBase64String(textAsBytes);
        }

        public static string DecodeBase64(this System.Text.Encoding encoding, string encodedText)
        {
            if (encodedText == null)
            {
                return null;
            }

            byte[] textAsBytes = System.Convert.FromBase64String(encodedText);
            return encoding.GetString(textAsBytes);
        }
    }




    class Program
    {
        static void Main(string[] args)
        {
            string iam_1 = "B2RhdGFTZXR/AAAAAQAAAA1QdXJjaGFzZSBMaW5lCQQAAOsAAAABMAoAAAAACGJvb2ttYXJrEwAAAAABMQgAAAAAATIRAAAAAAEzEQAAAAABNAgAAAAAATUIAAAAAAE2EQAAAAABNxEAAAAAATgRAAAAAAIxMA8AAAAAAjExEQAAAAACMTIRAAAAAAIxMxEAAAAAAjE1DgAAAAACMTYOAAAAAAIxNw4AAAAAAjE4DgAAAAACMjIOAAAAAAIyMw4AAAAAAjI1DgAAAAACMjcOAAAAAAIyOA4AAAAAAjI5DgAAAAACMzAOAAAAAAIzMQ4AAAAAAjMyAgAAAAACMzQOAAAAAAIzNQ4AAAAAAjM2DgAAAAACMzcOAAAAAAIzOAgAAAAAAjQwEQAAAAACNDERAAAAAAI0NREAAAAAAjU0DgAAAAACNTYCAAAAAAI1Nw4AAAAAAjU4DgAAAAACNTkOAAAAAAI2MA4AAAAAAjYxDgAAAAACNjMRAAAAAAI2NAgAAAAAAjY3DgAAAAACNjgRAAAAAAI2OQ4AAAAAAjcwEQAAAAACNzERAAAAAAI3MggAAAAAAjczAgAAAAACNzQRAAAAAAI3NREAAAAAAjc3CAAAAAACNzgRAAAAAAI3OREAAAAAAjgwCAAAAAACODERAAAAAAI4MhEAAAAAAjgzEQAAAAACODURAAAAAAI4NgIAAAAAAjg3EQAAAAACODgCAAAAAAI4OREAAAAAAjkwEQAAAAACOTERAAAAAAI5Mg4AAAAAAjkzDgAAAAACOTUOAAAAAAI5NxEAAAAAAjk4CAAAAAACOTkOAAAAAAMxMDAOAAAAAAMxMDECAAAAAAMxMDMOAAAAAAMxMDQOAAAAAAMxMDUOAAAAAAMxMDYRAAAAAAMxMDcIAAAAAAMxMDgRAAAAAAMxMDkOAAAAAAMxMTAOAAAAAAMxMTEOAAAAAAMxMTIOAAAAAAMxMTMOAAAAAAMxMTQOAAAAAAMxMTUOAAAAAAMxMTYIAAAAAAMxMTcRAAAAAAMxMTgRAAAAAAMxMTkCAAAAAAMxMjARAAAAAAMxMjEOAAAAAAMxMjIOAAAAAAMxMjMCAAAAAAMxMjQOAAAAAAMxMjkOAAAAAAMxMzARAAAAAAMxMzIOAAAAAAMxMzUOAAAAAAMxMzYOAAAAAAMxMzcOAAAAAAMxNDAOAAAAAAMxNDEOAAAAAAM0ODAIAAAAAAQxMDAxEQAAAAAEMTAwMggAAAAABDEwMDMOAAAAAAQxMDA0DgAAAAAEMTAwNQ4AAAAABDEwMDYOAAAAAAQxMDA3DgAAAAAEMTAwOA4AAAAABDEwMDkOAAAAAAQxMDEwDgAAAAAEMTAxMQ4AAAAABDEwMTIOAAAAAAQxMDEzEQAAAAAEMTAxOQgAAAAABDEwMzAOAAAAAAQxMDMxDgAAAAAEMTcwMBEAAAAABDE3MDIPAAAAAAQ1NDAxEQAAAAAENTQwMhEAAAAABDU0MDMRAAAAAAQ1NDA0DgAAAAAENTQwNxEAAAAABDU0MTUOAAAAAAQ1NDE2DgAAAAAENTQxNw4AAAAABDU0MTgOAAAAAAQ1NDU4DgAAAAAENTQ2MA4AAAAABDU0NjEOAAAAAAQ1NDk1DgAAAAAENTYwMA8AAAAABDU2MDEIAAAAAAQ1NjAyEQAAAAAENTYwMw4AAAAABDU2MDUCAAAAAAQ1NjA2AgAAAAAENTYwOREAAAAABDU2MTARAAAAAAQ1NjExEQAAAAAENTYxMhEAAAAABDU2MTMCAAAAAAQ1NzAwEQAAAAAENTcwNREAAAAABDU3MDYRAAAAAAQ1NzA3CAAAAAAENTcwOBEAAAAABDU3MDkRAAAAAAQ1NzEwAgAAAAAENTcxMREAAAAABDU3MTIRAAAAAAQ1NzEzAgAAAAAENTcxNBEAAAAABDU3MTUIAAAAAAQ1NzUwDgAAAAAENTc1MgIAAAAABDU3OTAPAAAAAAQ1NzkxDwAAAAAENTc5MhEAAAAABDU3OTMRAAAAAAQ1Nzk0DwAAAAAENTc5NQ8AAAAABDU4MDACAAAAAAQ1ODAxDgAAAAAENTgwMg4AAAAABDU4MDMOAAAAAAQ1ODA0DgAAAAAENTgwNQ4AAAAABDU4MDYOAAAAAAQ1ODA3DgAAAAAENTgwOA4AAAAABDU4MDkOAAAAAAQ1ODEwDgAAAAAENjYwMBEAAAAABDY2MDEIAAAAAAQ2NjA4EQAAAAAENjYwOQgAAAAABDY2MTACAAAAAAUxMjQwMBEAAAAABTEyNDAxCAAAAAAFMTI0MDIPAAAAAAUxMjQwMxEAAAAABTEyNDA0EQAAAAAFMTI0MDURAAAAAAUxMjQzMA4AAAAABTEyNDMxDgAAAAAFMTI0ODUCAAAAAAUxMjQ4NhEAAAAABTEyNDg3AgAAAAAFMTI0OTARAAAAAAUxNzMwMBEAAAAACDk5MDAwNzUwEQAAAAAIOTkwMDA3NTERAAAAAAg5OTAwMDc1MhEAAAAACDk5MDAwNzUzAgAAAAAIOTkwMDA3NTQIAAAAAAg5OTAwMDc1NQ4AAAAACDk5MDAwNzU2AgAAAAAIOTkwMDA3NTcIAAAAAAg5OTAwMDc1OBEAAAAACDk5MDAwNzU5CAAAAAAVQ29udHJvbDEyMTAwMzFfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwMzdfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwMzlfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwNDFfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwNDNfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwNDVfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwNDdfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwNDlfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwNTNfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwNTdfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwNTlfRm9ybWF0EQAAAAAOQ29udHJvbDEyMTAwOTERAAAAAA5Db250cm9sMTIxMDA5MxEAAAAADkNvbnRyb2wxMjEwMDk1EQAAAAAOQ29udHJvbDEyMTAwOTcRAAAAAA5Db250cm9sMTIxMDA5OREAAAAADkNvbnRyb2wxMjEwMTAxEQAAAAAdQ29udHJvbDEyMTAwMDdfRHluYW1pY0NhcHRpb24RAAAAAB1Db250cm9sMTIxMDAzN19EeW5hbWljQ2FwdGlvbhEAAAAAHUNvbnRyb2wxMjEwMDQ1X0R5bmFtaWNDYXB0aW9uEQAAAAAdQ29udHJvbDEyMTAwODdfRHluYW1pY0NhcHRpb24RAAAAAB1Db250cm9sMTIxMDA4OV9EeW5hbWljQ2FwdGlvbhEAAAAAHUNvbnRyb2wxMjEwMDkxX0R5bmFtaWNDYXB0aW9uEQAAAAAdQ29udHJvbDEyMTAwOTNfRHluYW1pY0NhcHRpb24RAAAAAB1Db250cm9sMTIxMDA5NV9EeW5hbWljQ2FwdGlvbhEAAAAAHUNvbnRyb2wxMjEwMDk3X0R5bmFtaWNDYXB0aW9uEQAAAAAdQ29udHJvbDEyMTAwOTlfRHluYW1pY0NhcHRpb24RAAAAAB1Db250cm9sMTIxMDEwMV9EeW5hbWljQ2FwdGlvbhEAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=";
            string iam_2 = "B2RhdGFTZXR/AAAAAQAAAA1QdXJjaGFzZSBMaW5lCQQAAOsAAAABMAoAAAAACGJvb2ttYXJrEwAAAAABMQgAAAAAATIRAAAAAAEzEQAAAAABNAgAAAAAATUIAAAAAAE2EQAAAAABNxEAAAAAATgRAAAAAAIxMA8AAAAAAjExEQAAAAACMTIRAAAAAAIxMxEAAAAAAjE1DgAAAAACMTYOAAAAAAIxNw4AAAAAAjE4DgAAAAACMjIOAAAAAAIyMw4AAAAAAjI1DgAAAAACMjcOAAAAAAIyOA4AAAAAAjI5DgAAAAACMzAOAAAAAAIzMQ4AAAAAAjMyAgAAAAACMzQOAAAAAAIzNQ4AAAAAAjM2DgAAAAACMzcOAAAAAAIzOAgAAAAAAjQwEQAAAAACNDERAAAAAAI0NREAAAAAAjU0DgAAAAACNTYCAAAAAAI1Nw4AAAAAAjU4DgAAAAACNTkOAAAAAAI2MA4AAAAAAjYxDgAAAAACNjMRAAAAAAI2NAgAAAAAAjY3DgAAAAACNjgRAAAAAAI2OQ4AAAAAAjcwEQAAAAACNzERAAAAAAI3MggAAAAAAjczAgAAAAACNzQRAAAAAAI3NREAAAAAAjc3CAAAAAACNzgRAAAAAAI3OREAAAAAAjgwCAAAAAACODERAAAAAAI4MhEAAAAAAjgzEQAAAAACODURAAAAAAI4NgIAAAAAAjg3EQAAAAACODgCAAAAAAI4OREAAAAAAjkwEQAAAAACOTERAAAAAAI5Mg4AAAAAAjkzDgAAAAACOTUOAAAAAAI5NxEAAAAAAjk4CAAAAAACOTkOAAAAAAMxMDAOAAAAAAMxMDECAAAAAAMxMDMOAAAAAAMxMDQOAAAAAAMxMDUOAAAAAAMxMDYRAAAAAAMxMDcIAAAAAAMxMDgRAAAAAAMxMDkOAAAAAAMxMTAOAAAAAAMxMTEOAAAAAAMxMTIOAAAAAAMxMTMOAAAAAAMxMTQOAAAAAAMxMTUOAAAAAAMxMTYIAAAAAAMxMTcRAAAAAAMxMTgRAAAAAAMxMTkCAAAAAAMxMjARAAAAAAMxMjEOAAAAAAMxMjIOAAAAAAMxMjMCAAAAAAMxMjQOAAAAAAMxMjkOAAAAAAMxMzARAAAAAAMxMzIOAAAAAAMxMzUOAAAAAAMxMzYOAAAAAAMxMzcOAAAAAAMxNDAOAAAAAAMxNDEOAAAAAAM0ODAIAAAAAAQxMDAxEQAAAAAEMTAwMggAAAAABDEwMDMOAAAAAAQxMDA0DgAAAAAEMTAwNQ4AAAAABDEwMDYOAAAAAAQxMDA3DgAAAAAEMTAwOA4AAAAABDEwMDkOAAAAAAQxMDEwDgAAAAAEMTAxMQ4AAAAABDEwMTIOAAAAAAQxMDEzEQAAAAAEMTAxOQgAAAAABDEwMzAOAAAAAAQxMDMxDgAAAAAEMTcwMBEAAAAABDE3MDIPAAAAAAQ1NDAxEQAAAAAENTQwMhEAAAAABDU0MDMRAAAAAAQ1NDA0DgAAAAAENTQwNxEAAAAABDU0MTUOAAAAAAQ1NDE2DgAAAAAENTQxNw4AAAAABDU0MTgOAAAAAAQ1NDU4DgAAAAAENTQ2MA4AAAAABDU0NjEOAAAAAAQ1NDk1DgAAAAAENTYwMA8AAAAABDU2MDEIAAAAAAQ1NjAyEQAAAAAENTYwMw4AAAAABDU2MDUCAAAAAAQ1NjA2AgAAAAAENTYwOREAAAAABDU2MTARAAAAAAQ1NjExEQAAAAAENTYxMhEAAAAABDU2MTMCAAAAAAQ1NzAwEQAAAAAENTcwNREAAAAABDU3MDYRAAAAAAQ1NzA3CAAAAAAENTcwOBEAAAAABDU3MDkRAAAAAAQ1NzEwAgAAAAAENTcxMREAAAAABDU3MTIRAAAAAAQ1NzEzAgAAAAAENTcxNBEAAAAABDU3MTUIAAAAAAQ1NzUwDgAAAAAENTc1MgIAAAAABDU3OTAPAAAAAAQ1NzkxDwAAAAAENTc5MhEAAAAABDU3OTMRAAAAAAQ1Nzk0DwAAAAAENTc5NQ8AAAAABDU4MDACAAAAAAQ1ODAxDgAAAAAENTgwMg4AAAAABDU4MDMOAAAAAAQ1ODA0DgAAAAAENTgwNQ4AAAAABDU4MDYOAAAAAAQ1ODA3DgAAAAAENTgwOA4AAAAABDU4MDkOAAAAAAQ1ODEwDgAAAAAENjYwMBEAAAAABDY2MDEIAAAAAAQ2NjA4EQAAAAAENjYwOQgAAAAABDY2MTACAAAAAAUxMjQwMBEAAAAABTEyNDAxCAAAAAAFMTI0MDIPAAAAAAUxMjQwMxEAAAAABTEyNDA0EQAAAAAFMTI0MDURAAAAAAUxMjQzMA4AAAAABTEyNDMxDgAAAAAFMTI0ODUCAAAAAAUxMjQ4NhEAAAAABTEyNDg3AgAAAAAFMTI0OTARAAAAAAUxNzMwMBEAAAAACDk5MDAwNzUwEQAAAAAIOTkwMDA3NTERAAAAAAg5OTAwMDc1MhEAAAAACDk5MDAwNzUzAgAAAAAIOTkwMDA3NTQIAAAAAAg5OTAwMDc1NQ4AAAAACDk5MDAwNzU2AgAAAAAIOTkwMDA3NTcIAAAAAAg5OTAwMDc1OBEAAAAACDk5MDAwNzU5CAAAAAAVQ29udHJvbDEyMTAwMzFfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwMzdfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwMzlfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwNDFfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwNDNfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwNDVfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwNDdfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwNDlfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwNTNfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwNTdfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwNTlfRm9ybWF0EQAAAAAOQ29udHJvbDEyMTAwOTERAAAAAA5Db250cm9sMTIxMDA5MxEAAAAADkNvbnRyb2wxMjEwMDk1EQAAAAAOQ29udHJvbDEyMTAwOTcRAAAAAA5Db250cm9sMTIxMDA5OREAAAAADkNvbnRyb2wxMjEwMTAxEQAAAAAdQ29udHJvbDEyMTAwMDdfRHluYW1pY0NhcHRpb24RAAAAAB1Db250cm9sMTIxMDAzN19EeW5hbWljQ2FwdGlvbhEAAAAAHUNvbnRyb2wxMjEwMDQ1X0R5bmFtaWNDYXB0aW9uEQAAAAAdQ29udHJvbDEyMTAwODdfRHluYW1pY0NhcHRpb24RAAAAAB1Db250cm9sMTIxMDA4OV9EeW5hbWljQ2FwdGlvbhEAAAAAHUNvbnRyb2wxMjEwMDkxX0R5bmFtaWNDYXB0aW9uEQAAAAAdQ29udHJvbDEyMTAwOTNfRHluYW1pY0NhcHRpb24RAAAAAB1Db250cm9sMTIxMDA5NV9EeW5hbWljQ2FwdGlvbhEAAAAAHUNvbnRyb2wxMjEwMDk3X0R5bmFtaWNDYXB0aW9uEQAAAAAdQ29udHJvbDEyMTAwOTlfRHluYW1pY0NhcHRpb24RAAAAAB1Db250cm9sMTIxMDEwMV9EeW5hbWljQ2FwdGlvbhEAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=";
            string iam_3 = "B2RhdGFTZXR/AAAAAQAAAA1QdXJjaGFzZSBMaW5lCQQAAOsAAAABMAoAAAAACGJvb2ttYXJrEwAAAAABMQgAAAAAATIRAAAAAAEzEQAAAAABNAgAAAAAATUIAAAAAAE2EQAAAAABNxEAAAAAATgRAAAAAAIxMA8AAAAAAjExEQAAAAACMTIRAAAAAAIxMxEAAAAAAjE1DgAAAAACMTYOAAAAAAIxNw4AAAAAAjE4DgAAAAACMjIOAAAAAAIyMw4AAAAAAjI1DgAAAAACMjcOAAAAAAIyOA4AAAAAAjI5DgAAAAACMzAOAAAAAAIzMQ4AAAAAAjMyAgAAAAACMzQOAAAAAAIzNQ4AAAAAAjM2DgAAAAACMzcOAAAAAAIzOAgAAAAAAjQwEQAAAAACNDERAAAAAAI0NREAAAAAAjU0DgAAAAACNTYCAAAAAAI1Nw4AAAAAAjU4DgAAAAACNTkOAAAAAAI2MA4AAAAAAjYxDgAAAAACNjMRAAAAAAI2NAgAAAAAAjY3DgAAAAACNjgRAAAAAAI2OQ4AAAAAAjcwEQAAAAACNzERAAAAAAI3MggAAAAAAjczAgAAAAACNzQRAAAAAAI3NREAAAAAAjc3CAAAAAACNzgRAAAAAAI3OREAAAAAAjgwCAAAAAACODERAAAAAAI4MhEAAAAAAjgzEQAAAAACODURAAAAAAI4NgIAAAAAAjg3EQAAAAACODgCAAAAAAI4OREAAAAAAjkwEQAAAAACOTERAAAAAAI5Mg4AAAAAAjkzDgAAAAACOTUOAAAAAAI5NxEAAAAAAjk4CAAAAAACOTkOAAAAAAMxMDAOAAAAAAMxMDECAAAAAAMxMDMOAAAAAAMxMDQOAAAAAAMxMDUOAAAAAAMxMDYRAAAAAAMxMDcIAAAAAAMxMDgRAAAAAAMxMDkOAAAAAAMxMTAOAAAAAAMxMTEOAAAAAAMxMTIOAAAAAAMxMTMOAAAAAAMxMTQOAAAAAAMxMTUOAAAAAAMxMTYIAAAAAAMxMTcRAAAAAAMxMTgRAAAAAAMxMTkCAAAAAAMxMjARAAAAAAMxMjEOAAAAAAMxMjIOAAAAAAMxMjMCAAAAAAMxMjQOAAAAAAMxMjkOAAAAAAMxMzARAAAAAAMxMzIOAAAAAAMxMzUOAAAAAAMxMzYOAAAAAAMxMzcOAAAAAAMxNDAOAAAAAAMxNDEOAAAAAAM0ODAIAAAAAAQxMDAxEQAAAAAEMTAwMggAAAAABDEwMDMOAAAAAAQxMDA0DgAAAAAEMTAwNQ4AAAAABDEwMDYOAAAAAAQxMDA3DgAAAAAEMTAwOA4AAAAABDEwMDkOAAAAAAQxMDEwDgAAAAAEMTAxMQ4AAAAABDEwMTIOAAAAAAQxMDEzEQAAAAAEMTAxOQgAAAAABDEwMzAOAAAAAAQxMDMxDgAAAAAEMTcwMBEAAAAABDE3MDIPAAAAAAQ1NDAxEQAAAAAENTQwMhEAAAAABDU0MDMRAAAAAAQ1NDA0DgAAAAAENTQwNxEAAAAABDU0MTUOAAAAAAQ1NDE2DgAAAAAENTQxNw4AAAAABDU0MTgOAAAAAAQ1NDU4DgAAAAAENTQ2MA4AAAAABDU0NjEOAAAAAAQ1NDk1DgAAAAAENTYwMA8AAAAABDU2MDEIAAAAAAQ1NjAyEQAAAAAENTYwMw4AAAAABDU2MDUCAAAAAAQ1NjA2AgAAAAAENTYwOREAAAAABDU2MTARAAAAAAQ1NjExEQAAAAAENTYxMhEAAAAABDU2MTMCAAAAAAQ1NzAwEQAAAAAENTcwNREAAAAABDU3MDYRAAAAAAQ1NzA3CAAAAAAENTcwOBEAAAAABDU3MDkRAAAAAAQ1NzEwAgAAAAAENTcxMREAAAAABDU3MTIRAAAAAAQ1NzEzAgAAAAAENTcxNBEAAAAABDU3MTUIAAAAAAQ1NzUwDgAAAAAENTc1MgIAAAAABDU3OTAPAAAAAAQ1NzkxDwAAAAAENTc5MhEAAAAABDU3OTMRAAAAAAQ1Nzk0DwAAAAAENTc5NQ8AAAAABDU4MDACAAAAAAQ1ODAxDgAAAAAENTgwMg4AAAAABDU4MDMOAAAAAAQ1ODA0DgAAAAAENTgwNQ4AAAAABDU4MDYOAAAAAAQ1ODA3DgAAAAAENTgwOA4AAAAABDU4MDkOAAAAAAQ1ODEwDgAAAAAENjYwMBEAAAAABDY2MDEIAAAAAAQ2NjA4EQAAAAAENjYwOQgAAAAABDY2MTACAAAAAAUxMjQwMBEAAAAABTEyNDAxCAAAAAAFMTI0MDIPAAAAAAUxMjQwMxEAAAAABTEyNDA0EQAAAAAFMTI0MDURAAAAAAUxMjQzMA4AAAAABTEyNDMxDgAAAAAFMTI0ODUCAAAAAAUxMjQ4NhEAAAAABTEyNDg3AgAAAAAFMTI0OTARAAAAAAUxNzMwMBEAAAAACDk5MDAwNzUwEQAAAAAIOTkwMDA3NTERAAAAAAg5OTAwMDc1MhEAAAAACDk5MDAwNzUzAgAAAAAIOTkwMDA3NTQIAAAAAAg5OTAwMDc1NQ4AAAAACDk5MDAwNzU2AgAAAAAIOTkwMDA3NTcIAAAAAAg5OTAwMDc1OBEAAAAACDk5MDAwNzU5CAAAAAAVQ29udHJvbDEyMTAwMzFfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwMzdfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwMzlfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwNDFfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwNDNfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwNDVfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwNDdfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwNDlfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwNTNfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwNTdfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwNTlfRm9ybWF0EQAAAAAOQ29udHJvbDEyMTAwOTERAAAAAA5Db250cm9sMTIxMDA5MxEAAAAADkNvbnRyb2wxMjEwMDk1EQAAAAAOQ29udHJvbDEyMTAwOTcRAAAAAA5Db250cm9sMTIxMDA5OREAAAAADkNvbnRyb2wxMjEwMTAxEQAAAAAdQ29udHJvbDEyMTAwMDdfRHluYW1pY0NhcHRpb24RAAAAAB1Db250cm9sMTIxMDAzN19EeW5hbWljQ2FwdGlvbhEAAAAAHUNvbnRyb2wxMjEwMDQ1X0R5bmFtaWNDYXB0aW9uEQAAAAAdQ29udHJvbDEyMTAwODdfRHluYW1pY0NhcHRpb24RAAAAAB1Db250cm9sMTIxMDA4OV9EeW5hbWljQ2FwdGlvbhEAAAAAHUNvbnRyb2wxMjEwMDkxX0R5bmFtaWNDYXB0aW9uEQAAAAAdQ29udHJvbDEyMTAwOTNfRHluYW1pY0NhcHRpb24RAAAAAB1Db250cm9sMTIxMDA5NV9EeW5hbWljQ2FwdGlvbhEAAAAAHUNvbnRyb2wxMjEwMDk3X0R5bmFtaWNDYXB0aW9uEQAAAAAdQ29udHJvbDEyMTAwOTlfRHluYW1pY0NhcHRpb24RAAAAAB1Db250cm9sMTIxMDEwMV9EeW5hbWljQ2FwdGlvbhEAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=";
            string cf_1 = "Ck5ld0RhdGFTZXR/AAAAAQAAAAEwCQQAAKsAAAAIYm9va21hcmsTAAAAAAEwCgAAAAABMREAAAAAATIRAAAAAAEzEQAAAAABNBEAAAAAATURAAAAAAE2EQAAAAABNxEAAAAAATgRAAAAAAE5EQAAAAACMTARAAAAAAIxNBEAAAAAAjE1EQAAAAACMTYRAAAAAAIxNxEAAAAAAjE5DgAAAAACMjERAAAAAAIyMhEAAAAAAjI0EQAAAAACMjYIAAAAAAIyNxEAAAAAAjI4EQAAAAACMjkRAAAAAAIzMBEAAAAAAjMxEQAAAAACMzMRAAAAAAIzNREAAAAAAjM5CAAAAAACNDURAAAAAAI0NggAAAAAAjQ3EQAAAAACNTMPAAAAAAI1NA8AAAAAAjgwCAAAAAACODICAAAAAAI4NBEAAAAAAjg1EQAAAAACODYRAAAAAAI4OBEAAAAAAjg5EwAAAAACOTARAAAAAAI5MREAAAAAAjkyEQAAAAADMTAyEQAAAAADMTAzEQAAAAADMTA3EQAAAAADMTA4EQAAAAADMTA5AgAAAAADMTEwEQAAAAADMTE2AgAAAAADMTE5EQAAAAADMTI0DgAAAAADMTMyCAAAAAADMTQwFAAAAAADMTUwAgAAAAADMTYwAgAAAAADMTcwEQAAAAADMjg4EQAAAAADODQwEQAAAAAENTA0OREAAAAABDU3MDARAAAAAAQ1NzAxEQAAAAAENTc5MBEAAAAABDc2MDARAAAAAAQ3NjAxEQAAAAAENzYwMgIAAAAABDgwMDASAAAAAAQ4MDAxEgAAAAAEODAwMhIAAAAABDgwMDMSAAAAAAUxMjQwMBEAAAAABTEyNDAxEQAAAAAFMTI0MDIRAAAAAAUxMjQwMxEAAAAABTEyNDA1EQAAAAAFMTI0MDYRAAAAAAUxMjQwOREAAAAABTEyNDEwAgAAAAAFMTI0MTERAAAAAAUxMjQxMggAAAAABTEyNDEzCAAAAAAFMTI0MTQRAAAAAAUxMjQzMggAAAAABTEyNDgwEQAAAAAFMTI0ODERAAAAAAUxMjQ5MAgAAAAABTEyNDk0EQAAAAACNTUPAAAAAAI1NhEAAAAAAjU3EQAAAAADMTExEQAAAAAFMTI0MjURAAAAAAUxMjQyNg8AAAAABTEyNDkxEQAAAAACMzgCAAAAAAI1OA4AAAAAAjU5DgAAAAACNjAOAAAAAAI2MQ4AAAAAAjYyDgAAAAACNjQOAAAAAAI2NQ4AAAAAAjY2DgAAAAACNjcOAAAAAAI2OQ4AAAAAAjcwDgAAAAACNzEOAAAAAAI3Mg4AAAAAAjc0DgAAAAACNzUOAAAAAAI3Ng4AAAAAAjc3DgAAAAACNzgOAAAAAAI3OQ4AAAAAAjk3DgAAAAACOTgOAAAAAAI5OQ4AAAAAAzEwMA4AAAAAAzEwNA4AAAAAAzEwNQ4AAAAAAzExMw4AAAAAAzExNA4AAAAAAzExNw4AAAAAAzExOA4AAAAAAzEyMA4AAAAAAzEyMQ4AAAAAAzEyMg4AAAAAAzEyMw4AAAAAAzEyNQ4AAAAAAzEyNg4AAAAAAzEzMAgAAAAAAzEzMQgAAAAABDcxNzcIAAAAAAQ3MTc4CAAAAAAENzE3OQgAAAAABDcxODAIAAAAAAQ3MTgxCAAAAAAENzE4MggAAAAABDcxODMIAAAAAAQ3MTg0CAAAAAAENzE4NQgAAAAABDcxODYIAAAAAAQ3MTg3CAAAAAAENzE4OAgAAAAABDcxODkIAAAAAAQ3MTkwCAAAAAAENzE5MQgAAAAABDcxOTIIAAAAAAQ3MTkzCAAAAAAENzE5NAgAAAAABDcxOTUIAAAAAAQ3MTk2CAAAAAAENzE5NwgAAAAABDcxOTgIAAAAAAUxMjQwNBEAAAAABTEyNDI3DgAAAAAFMTI0MjgOAAAAAAUxMjQyOQ4AAAAABTEyNDMwDgAAAAAFMTI0MzEOAAAAABtTb2NpYWxMaXN0ZW5pbmdTZXR1cFZpc2libGUCAAAAABZTb2NpYWxMaXN0ZW5pbmdWaXNpYmxlAgAAAAAYT3BlbkFwcHJvdmFsRW50cmllc0V4aXN0AgAAAAAaQ2FuQ2FuY2VsQXBwcm92YWxGb3JSZWNvcmQCAAAAAA5Qb3dlckJJVmlzaWJsZQIAAAAADVJlc3luY1Zpc2libGUCAAAAABlDYW5SZXF1ZXN0QXBwcm92YWxGb3JGbG93AgAAAAAYQ2FuQ2FuY2VsQXBwcm92YWxGb3JGbG93AgAAAAAQQ29udHJvbDMyX0Zvcm1hdBEAAAAAEENvbnRyb2wzNF9Gb3JtYXQRAAAAAAEAAAACFQAAABcAAAACewU2ADIAMAAwADAAAAAAAAJu6QgAAAAAAAIFNjIwMDACH9CX0JDQniAi0KHQv9C+0YDRgtC80LDRgdGC0LXRgCICH9CX0JDQniAi0KHQn9Ce0KDQotCc0JDQodCi0JXQoCICAAIi0YPQuy4g0JHQvtGC0LDQvdC40YfQtdGB0LrQsNGPLCA0NAIAAgzQnNC+0YHQutCy0LACAAIAAgACAAIAAgACAAIAAAAAAAAAAAAAAAAAAAAAAgc2MC0xMDEwAgACAAIAAAAAAgTQndCfAgACBNCS0JUCEtCh0KIu0Jgg0KTQoNCQ0KXQogIAAgU2MjAwMAIAAgAAAAACAAIDAAAAAgACgCvjUDst1wgBAAAAAgAAQwDdLNcIAgAAAAIAAAAAAgACAAIAAgACDNCR0JjQl9Cd0JXQoQACAAIGMTAzMDU0AgACAAIAAgACAAIAAg7Qn9Ce0JrQo9Cf0JrQkAIAAgACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAgEAAAAAAgACAAIAAgACAAIAAgzQnNCe0KHQmtCS0JACCtCR0JXQm9Cr0JkCAAIAAgACAAJZjbo/4WEPQISpaIdh4YfYAgAAAAAAAAAAAAAAAAAAAAACL87I70jmXk6sfXy+RoMLVQIAAAAAAAAAAAAAAAAAAAAAAgACAAIAAgACAAIAAgACAAIAAgAAAAACAAAAAAIAAgAAAAACAAIAAgAAAAACCdCf0J7Qmi0wMgAAAAAAAAACAAIAAAAAAAAAAAAAAAAAAAAAAjQMWwQAAAAAAAAAAAAAAQACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACNAxbBAAAAAAAAAAAAAABAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAIAAAAAAgAAAAACAAAAAAIAAAAAAgAAAAACAAAAAAIAAAAAAgAAAAACAAAAAAIAAAAAAgAAAAACAAAAAAIAAAAAAgAAAAACAAAAAAIAAAAAAgAAAAACAAAAAAIAAAAAAgAAAAACAAAAAAIAAAAAAgAAAAACAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAIAAgACAAIBAgACAAIAAggjLCMjMC4wMAIIIywjIzAuMDA=";
            string vf_1 = "B2RhdGFTZXR/AAAAAQAAAA9QdXJjaGFzZSBIZWFkZXIJBAAAswAAAAEwCgAAAAAIYm9va21hcmsTAAAAAAExCAAAAAABMhEAAAAAATMRAAAAAAE0EQAAAAABNREAAAAAATYRAAAAAAE3EQAAAAABOBEAAAAAATkRAAAAAAIxMBEAAAAAAjExEQAAAAACMTIRAAAAAAIxMxEAAAAAAjE0EQAAAAACMTURAAAAAAIxNhEAAAAAAjE3EQAAAAACMTgRAAAAAAIxOQ8AAAAAAjIwDwAAAAACMjEPAAAAAAIyMhEAAAAAAjIzEQAAAAACMjQPAAAAAAIyNQ4AAAAAAjI2DwAAAAACMjcRAAAAAAIyOBEAAAAAAjI5EQAAAAACMzARAAAAAAIzMREAAAAAAjMyEQAAAAACMzMOAAAAAAIzNQIAAAAAAjM3EQAAAAACNDERAAAAAAI0MxEAAAAAAjQ1EQAAAAACNDYCAAAAAAI0NwgAAAAAAjUxEQAAAAACNTIIAAAAAAI1MxEAAAAAAjU1EQAAAAACNTYCAAAAAAI1NwIAAAAAAjU4AgAAAAACNTkCAAAAAAI2MA4AAAAAAjYxDgAAAAACNjIRAAAAAAI2MxEAAAAAAjY0EQAAAAACNjURAAAAAAI2NhEAAAAAAjY3EQAAAAACNjgRAAAAAAI2OREAAAAAAjcwEQAAAAACNzIRAAAAAAI3MxEAAAAAAjc0EQAAAAACNzYRAAAAAAI3NxEAAAAAAjc4EQAAAAACNzkRAAAAAAI4MBEAAAAAAjgxEQAAAAACODIRAAAAAAI4MxEAAAAAAjg0EQAAAAACODURAAAAAAI4NhEAAAAAAjg3EQAAAAACODgRAAAAAAI4OREAAAAAAjkwEQAAAAACOTERAAAAAAI5MhEAAAAAAjkzEQAAAAACOTQIAAAAAAI5NREAAAAAAjk3EQAAAAACOTgCAAAAAAI5OQ8AAAAAAzEwMREAAAAAAzEwMhEAAAAAAzEwNBEAAAAAAzEwNxEAAAAAAzEwOBEAAAAAAzEwOREAAAAAAzExNBEAAAAAAzExNQIAAAAAAzExNhEAAAAAAzExOBEAAAAAAzExOQ4AAAAAAzEyMAgAAAAAAzEyMQgAAAAAAzEyMg4AAAAAAzEyMwIAAAAAAzEyNAgAAAAAAzEyNREAAAAAAzEyNhEAAAAAAzEyOQgAAAAAAzEzMBEAAAAAAzEzMREAAAAAAzEzMhEAAAAAAzEzMxEAAAAAAzEzNA4AAAAAAzEzNREAAAAAAzEzNgIAAAAAAzEzNw8AAAAAAzEzOBEAAAAAAzEzOREAAAAAAzE0Mg8AAAAAAzE0MxEAAAAAAzE0NA4AAAAAAzE1MREAAAAAAzE2MAgAAAAAAzE2MRIAAAAAAzE2NQgAAAAAAzE3MBEAAAAAAzE3MREAAAAAAzMwMA4AAAAAAzMwMQ4AAAAAAzQ4MAgAAAAABDEzMDUOAAAAAAQ1MDQzCAAAAAAENTA0OAgAAAAABDUwNTARAAAAAAQ1MDUyEQAAAAAENTA1MxEAAAAABDU3MDARAAAAAAQ1NzUxAgAAAAAENTc1MgIAAAAABDU3NTMIAAAAAAQ1NzkwDwAAAAAENTc5MQ8AAAAABDU3OTIRAAAAAAQ1NzkzEQAAAAAENTgwMBEAAAAABDU4MDERAAAAAAQ1ODAyEQAAAAAENTgwMwIAAAAABDU4MDQRAAAAAAQ4MDAwEgAAAAAEOTAwMBEAAAAABDkwMDEIAAAAAAUxMjQwMAIAAAAABTEyNDAxEQAAAAAFMTI0MDIRAAAAAAUxMjQwMwgAAAAABTEyNDA0AgAAAAAFMTI0MzcIAAAAAAUxMjQzOAgAAAAABTEyNDQwAgAAAAAFMTI0NDEIAAAAAAUxMjQ0MhEAAAAABTEyNDQzCAAAAAAFMTI0NDQRAAAAAAUxMjQ0NREAAAAABTEyNDQ2CAAAAAAFMTI0NDcRAAAAAAUxMjQ3MBEAAAAABTEyNDcxDwAAAAAFMTI0NzIPAAAAAAUxMjQ3Mw8AAAAABTEyNDc0EQAAAAAFMTI0ODAOAAAAAAUxMjQ4NREAAAAABTEyNDg2AgAAAAAFMTI0OTARAAAAAAUxMjQ5MREAAAAABTEyNDk4AgAAAAAFMTI0OTkPAAAAAAQ1NzU0EQAAAAAENTc5NhEAAAAAAgAAAAKpmg0AAAAAAAIrAAAAJgAAAACLAgAAAAJ7/x8EHgQQBBIELQAyADEALQAwADAAMAAzADQAAAAAAAICAAAAAgACEdCf0J7QkNCSLTIxLTAwMDM0AgACAAIAAgACAAIAAgACAAIAAhpDUk9OVVMg0KDQvtGB0YHQuNGPINCX0JDQngIAAgvQoNC40L3QsywgNQIAAgzQnNC+0YHQutCy0LACAAIAQABTjcHYCAIAAAACAEAAU43B2AgCAAAAAgBAAFONwdgIAgAAAAIZSW52b2ljZSDQn9Ce0JDQki0yMS0wMDAzNAIAAgAAAAAAAAAAAgAAAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAgAAAAIAAgACAAIAAgACAAIAAAAAAAAAAAAAAAAAAAAAAgACAAIAAgACAAIAAgAAAAACAAIAAAAAAgACAAIAAgACAAIAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAIR0J/QntCQ0JItMjEtMDAwMzQCEdCf0J7QkNCSLTIxLTAwMDM0AgACAAIAAgACEdCf0J7QkNCSLTIxLTAwMDM0AgACAAIAAgACAAIAAgACAAIFNjIwMDACAAIAAgACAAIAAgACAAIAAgACAAIAAgYxMDMwNTQCAAICUlUCAAAAAAIAAgACAAIAQABTjcHYCAIAAAACAAIAAgACCdCf0J7Qmi0yMAIJ0J/QntCaLTIwAgnQn9Ce0JotMTUCAAIAAgACAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAACAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgACAAAAAAIAAgACAAAAAAIAAgACAAIAAgAAAAAAAAAAAAAAAAAAAAACAAIBAgAAAAAAAAAAAgAAAAIAAgACAAAAAAAAAAACAAAAAgACAAAAAAAAAAAAAAAAAAAAAAIAAgAAAAACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAgACAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAACAQAAAAIAAgACAAIAAgACAAIAAAAAAgAAAAAAAAAAAgAAAAIAAAAAAAAAAAIAAAACAAIAAgACAAIAAgACAAKs0IGOx9pzSZIoLF1gkGW/AgACAAAAAAIBAgACAAIAAAAAAgACAAAAAAIAAAAAAgACAAAAAAIAAgAAAAACAAIAAgAAAAACAAIAAgAAAAAAAAAAAgAAAAIAAAAAAAAAAAIAAAACAAAAAAAAAAACAAAAAgACAAAAAAAAAAAAAAAAAAAAAAIAAgACAAIAAgACAAAAAAAAAAACAAAAAAACqZoNAAAAAAACKwAAACYAAAAAiwIAAAACe/8fBB4EEAQSBC0AMgAxAC0AMAAwADAAMwA0AAAAAAACAgAAAAIAAhHQn9Ce0JDQki0yMS0wMDAzNAIAAgACAAIAAgACAAIAAgACAAIaQ1JPTlVTINCg0L7RgdGB0LjRjyDQl9CQ0J4CAAIL0KDQuNC90LMsIDUCAAIM0JzQvtGB0LrQstCwAgACAEAAU43B2AgCAAAAAgBAAFONwdgIAgAAAAIAQABTjcHYCAIAAAACGUludm9pY2Ug0J/QntCQ0JItMjEtMDAwMzQCAAIAAAAAAAAAAAIAAAACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAIAAAACAAIAAgACAAIAAgACAAAAAAAAAAAAAAAAAAAAAAIAAgACAAIAAgACAAIAAAAAAgACAAAAAAIAAgACAAIAAgACAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACEdCf0J7QkNCSLTIxLTAwMDM0AhHQn9Ce0JDQki0yMS0wMDAzNAIAAgACAAIAAhHQn9Ce0JDQki0yMS0wMDAzNAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACBjEwMzA1NAIAAgJSVQIAAAAAAgACAAIAAgBAAFONwdgIAgAAAAIAAgACAAIJ0J/QntCaLTIwAgnQn9Ce0JotMjACCdCf0J7Qmi0xNQIAAgACAAIAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAIAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAIAAAAAAgACAAIAAAAAAgACAAIAAgACAAAAAAAAAAAAAAAAAAAAAAIAAgECAAAAAAAAAAACAAAAAgACAAIAAAAAAAAAAAIAAAACAAIAAAAAAAAAAAAAAAAAAAAAAgACAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAACAAIAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAIBAAAAAgACAAIAAgACAAIAAgAAAAACAAAAAAAAAAACAAAAAgAAAAAAAAAAAgAAAAIAAgACAAIAAgACAAIAAqzQgY7H2nNJkigsXWCQZb8CAAIAAAAAAgECAAIAAgAAAAACAAIAAAAAAgAAAAACAAIAAAAAAgACAAAAAAIAAgACAAAAAAIAAgACAAAAAAAAAAACAAAAAgAAAAAAAAAAAgAAAAIAAAAAAAAAAAIAAAACAAIAAAAAAAAAAAAAAAAAAAAAAgACAAIAAgACAAIAAAAAAAAAAAIAAAAAAA==";
            string textDecoded1 = System.Text.Encoding.UTF8.DecodeBase64(iam_1);
            string textDecoded2 = System.Text.Encoding.UTF8.DecodeBase64(iam_2);
            string textDecoded3 = System.Text.Encoding.UTF8.DecodeBase64(iam_3);
            string textDecoded4 = System.Text.Encoding.UTF8.DecodeBase64(cf_1);
            string textDecoded5 = System.Text.Encoding.UTF8.DecodeBase64(vf_1);

            string iam_first = "B2RhdGFTZXR/AAAAAQAAAA9QdXJjaGFzZSBIZWFkZXIJBAAAswAAAAEwCgAAAAAIYm9va21hcmsTAAAAAAExCAAAAAABMhEAAAAAATMRAAAAAAE0EQAAAAABNREAAAAAATYRAAAAAAE3EQAAAAABOBEAAAAAATkRAAAAAAIxMBEAAAAAAjExEQAAAAACMTIRAAAAAAIxMxEAAAAAAjE0EQAAAAACMTURAAAAAAIxNhEAAAAAAjE3EQAAAAACMTgRAAAAAAIxOQ8AAAAAAjIwDwAAAAACMjEPAAAAAAIyMhEAAAAAAjIzEQAAAAACMjQPAAAAAAIyNQ4AAAAAAjI2DwAAAAACMjcRAAAAAAIyOBEAAAAAAjI5EQAAAAACMzARAAAAAAIzMREAAAAAAjMyEQAAAAACMzMOAAAAAAIzNQIAAAAAAjM3EQAAAAACNDERAAAAAAI0MxEAAAAAAjQ1EQAAAAACNDYCAAAAAAI0NwgAAAAAAjUxEQAAAAACNTIIAAAAAAI1MxEAAAAAAjU1EQAAAAACNTYCAAAAAAI1NwIAAAAAAjU4AgAAAAACNTkCAAAAAAI2MA4AAAAAAjYxDgAAAAACNjIRAAAAAAI2MxEAAAAAAjY0EQAAAAACNjURAAAAAAI2NhEAAAAAAjY3EQAAAAACNjgRAAAAAAI2OREAAAAAAjcwEQAAAAACNzIRAAAAAAI3MxEAAAAAAjc0EQAAAAACNzYRAAAAAAI3NxEAAAAAAjc4EQAAAAACNzkRAAAAAAI4MBEAAAAAAjgxEQAAAAACODIRAAAAAAI4MxEAAAAAAjg0EQAAAAACODURAAAAAAI4NhEAAAAAAjg3EQAAAAACODgRAAAAAAI4OREAAAAAAjkwEQAAAAACOTERAAAAAAI5MhEAAAAAAjkzEQAAAAACOTQIAAAAAAI5NREAAAAAAjk3EQAAAAACOTgCAAAAAAI5OQ8AAAAAAzEwMREAAAAAAzEwMhEAAAAAAzEwNBEAAAAAAzEwNxEAAAAAAzEwOBEAAAAAAzEwOREAAAAAAzExNBEAAAAAAzExNQIAAAAAAzExNhEAAAAAAzExOBEAAAAAAzExOQ4AAAAAAzEyMAgAAAAAAzEyMQgAAAAAAzEyMg4AAAAAAzEyMwIAAAAAAzEyNAgAAAAAAzEyNREAAAAAAzEyNhEAAAAAAzEyOQgAAAAAAzEzMBEAAAAAAzEzMREAAAAAAzEzMhEAAAAAAzEzMxEAAAAAAzEzNA4AAAAAAzEzNREAAAAAAzEzNgIAAAAAAzEzNw8AAAAAAzEzOBEAAAAAAzEzOREAAAAAAzE0Mg8AAAAAAzE0MxEAAAAAAzE0NA4AAAAAAzE1MREAAAAAAzE2MAgAAAAAAzE2MRIAAAAAAzE2NQgAAAAAAzE3MBEAAAAAAzE3MREAAAAAAzMwMA4AAAAAAzMwMQ4AAAAAAzQ4MAgAAAAABDEzMDUOAAAAAAQ1MDQzCAAAAAAENTA0OAgAAAAABDUwNTARAAAAAAQ1MDUyEQAAAAAENTA1MxEAAAAABDU3MDARAAAAAAQ1NzUxAgAAAAAENTc1MgIAAAAABDU3NTMIAAAAAAQ1NzkwDwAAAAAENTc5MQ8AAAAABDU3OTIRAAAAAAQ1NzkzEQAAAAAENTgwMBEAAAAABDU4MDERAAAAAAQ1ODAyEQAAAAAENTgwMwIAAAAABDU4MDQRAAAAAAQ4MDAwEgAAAAAEOTAwMBEAAAAABDkwMDEIAAAAAAUxMjQwMAIAAAAABTEyNDAxEQAAAAAFMTI0MDIRAAAAAAUxMjQwMwgAAAAABTEyNDA0AgAAAAAFMTI0MzcIAAAAAAUxMjQzOAgAAAAABTEyNDQwAgAAAAAFMTI0NDEIAAAAAAUxMjQ0MhEAAAAABTEyNDQzCAAAAAAFMTI0NDQRAAAAAAUxMjQ0NREAAAAABTEyNDQ2CAAAAAAFMTI0NDcRAAAAAAUxMjQ3MBEAAAAABTEyNDcxDwAAAAAFMTI0NzIPAAAAAAUxMjQ3Mw8AAAAABTEyNDc0EQAAAAAFMTI0ODAOAAAAAAUxMjQ4NREAAAAABTEyNDg2AgAAAAAFMTI0OTARAAAAAAUxMjQ5MREAAAAABTEyNDk4AgAAAAAFMTI0OTkPAAAAAAQ1NzU0EQAAAAAENTc5NhEAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
            string iam_general = "B2RhdGFTZXR/AAAAAQAAAA1QdXJjaGFzZSBMaW5lCQQAAOsAAAABMAoAAAAACGJvb2ttYXJrEwAAAAABMQgAAAAAATIRAAAAAAEzEQAAAAABNAgAAAAAATUIAAAAAAE2EQAAAAABNxEAAAAAATgRAAAAAAIxMA8AAAAAAjExEQAAAAACMTIRAAAAAAIxMxEAAAAAAjE1DgAAAAACMTYOAAAAAAIxNw4AAAAAAjE4DgAAAAACMjIOAAAAAAIyMw4AAAAAAjI1DgAAAAACMjcOAAAAAAIyOA4AAAAAAjI5DgAAAAACMzAOAAAAAAIzMQ4AAAAAAjMyAgAAAAACMzQOAAAAAAIzNQ4AAAAAAjM2DgAAAAACMzcOAAAAAAIzOAgAAAAAAjQwEQAAAAACNDERAAAAAAI0NREAAAAAAjU0DgAAAAACNTYCAAAAAAI1Nw4AAAAAAjU4DgAAAAACNTkOAAAAAAI2MA4AAAAAAjYxDgAAAAACNjMRAAAAAAI2NAgAAAAAAjY3DgAAAAACNjgRAAAAAAI2OQ4AAAAAAjcwEQAAAAACNzERAAAAAAI3MggAAAAAAjczAgAAAAACNzQRAAAAAAI3NREAAAAAAjc3CAAAAAACNzgRAAAAAAI3OREAAAAAAjgwCAAAAAACODERAAAAAAI4MhEAAAAAAjgzEQAAAAACODURAAAAAAI4NgIAAAAAAjg3EQAAAAACODgCAAAAAAI4OREAAAAAAjkwEQAAAAACOTERAAAAAAI5Mg4AAAAAAjkzDgAAAAACOTUOAAAAAAI5NxEAAAAAAjk4CAAAAAACOTkOAAAAAAMxMDAOAAAAAAMxMDECAAAAAAMxMDMOAAAAAAMxMDQOAAAAAAMxMDUOAAAAAAMxMDYRAAAAAAMxMDcIAAAAAAMxMDgRAAAAAAMxMDkOAAAAAAMxMTAOAAAAAAMxMTEOAAAAAAMxMTIOAAAAAAMxMTMOAAAAAAMxMTQOAAAAAAMxMTUOAAAAAAMxMTYIAAAAAAMxMTcRAAAAAAMxMTgRAAAAAAMxMTkCAAAAAAMxMjARAAAAAAMxMjEOAAAAAAMxMjIOAAAAAAMxMjMCAAAAAAMxMjQOAAAAAAMxMjkOAAAAAAMxMzARAAAAAAMxMzIOAAAAAAMxMzUOAAAAAAMxMzYOAAAAAAMxMzcOAAAAAAMxNDAOAAAAAAMxNDEOAAAAAAM0ODAIAAAAAAQxMDAxEQAAAAAEMTAwMggAAAAABDEwMDMOAAAAAAQxMDA0DgAAAAAEMTAwNQ4AAAAABDEwMDYOAAAAAAQxMDA3DgAAAAAEMTAwOA4AAAAABDEwMDkOAAAAAAQxMDEwDgAAAAAEMTAxMQ4AAAAABDEwMTIOAAAAAAQxMDEzEQAAAAAEMTAxOQgAAAAABDEwMzAOAAAAAAQxMDMxDgAAAAAEMTcwMBEAAAAABDE3MDIPAAAAAAQ1NDAxEQAAAAAENTQwMhEAAAAABDU0MDMRAAAAAAQ1NDA0DgAAAAAENTQwNxEAAAAABDU0MTUOAAAAAAQ1NDE2DgAAAAAENTQxNw4AAAAABDU0MTgOAAAAAAQ1NDU4DgAAAAAENTQ2MA4AAAAABDU0NjEOAAAAAAQ1NDk1DgAAAAAENTYwMA8AAAAABDU2MDEIAAAAAAQ1NjAyEQAAAAAENTYwMw4AAAAABDU2MDUCAAAAAAQ1NjA2AgAAAAAENTYwOREAAAAABDU2MTARAAAAAAQ1NjExEQAAAAAENTYxMhEAAAAABDU2MTMCAAAAAAQ1NzAwEQAAAAAENTcwNREAAAAABDU3MDYRAAAAAAQ1NzA3CAAAAAAENTcwOBEAAAAABDU3MDkRAAAAAAQ1NzEwAgAAAAAENTcxMREAAAAABDU3MTIRAAAAAAQ1NzEzAgAAAAAENTcxNBEAAAAABDU3MTUIAAAAAAQ1NzUwDgAAAAAENTc1MgIAAAAABDU3OTAPAAAAAAQ1NzkxDwAAAAAENTc5MhEAAAAABDU3OTMRAAAAAAQ1Nzk0DwAAAAAENTc5NQ8AAAAABDU4MDACAAAAAAQ1ODAxDgAAAAAENTgwMg4AAAAABDU4MDMOAAAAAAQ1ODA0DgAAAAAENTgwNQ4AAAAABDU4MDYOAAAAAAQ1ODA3DgAAAAAENTgwOA4AAAAABDU4MDkOAAAAAAQ1ODEwDgAAAAAENjYwMBEAAAAABDY2MDEIAAAAAAQ2NjA4EQAAAAAENjYwOQgAAAAABDY2MTACAAAAAAUxMjQwMBEAAAAABTEyNDAxCAAAAAAFMTI0MDIPAAAAAAUxMjQwMxEAAAAABTEyNDA0EQAAAAAFMTI0MDURAAAAAAUxMjQzMA4AAAAABTEyNDMxDgAAAAAFMTI0ODUCAAAAAAUxMjQ4NhEAAAAABTEyNDg3AgAAAAAFMTI0OTARAAAAAAUxNzMwMBEAAAAACDk5MDAwNzUwEQAAAAAIOTkwMDA3NTERAAAAAAg5OTAwMDc1MhEAAAAACDk5MDAwNzUzAgAAAAAIOTkwMDA3NTQIAAAAAAg5OTAwMDc1NQ4AAAAACDk5MDAwNzU2AgAAAAAIOTkwMDA3NTcIAAAAAAg5OTAwMDc1OBEAAAAACDk5MDAwNzU5CAAAAAAVQ29udHJvbDEyMTAwMzFfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwMzdfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwMzlfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwNDFfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwNDNfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwNDVfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwNDdfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwNDlfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwNTNfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwNTdfRm9ybWF0EQAAAAAVQ29udHJvbDEyMTAwNTlfRm9ybWF0EQAAAAAOQ29udHJvbDEyMTAwOTERAAAAAA5Db250cm9sMTIxMDA5MxEAAAAADkNvbnRyb2wxMjEwMDk1EQAAAAAOQ29udHJvbDEyMTAwOTcRAAAAAA5Db250cm9sMTIxMDA5OREAAAAADkNvbnRyb2wxMjEwMTAxEQAAAAAdQ29udHJvbDEyMTAwMDdfRHluYW1pY0NhcHRpb24RAAAAAB1Db250cm9sMTIxMDAzN19EeW5hbWljQ2FwdGlvbhEAAAAAHUNvbnRyb2wxMjEwMDQ1X0R5bmFtaWNDYXB0aW9uEQAAAAAdQ29udHJvbDEyMTAwODdfRHluYW1pY0NhcHRpb24RAAAAAB1Db250cm9sMTIxMDA4OV9EeW5hbWljQ2FwdGlvbhEAAAAAHUNvbnRyb2wxMjEwMDkxX0R5bmFtaWNDYXB0aW9uEQAAAAAdQ29udHJvbDEyMTAwOTNfRHluYW1pY0NhcHRpb24RAAAAAB1Db250cm9sMTIxMDA5NV9EeW5hbWljQ2FwdGlvbhEAAAAAHUNvbnRyb2wxMjEwMDk3X0R5bmFtaWNDYXB0aW9uEQAAAAAdQ29udHJvbDEyMTAwOTlfRHluYW1pY0NhcHRpb24RAAAAAB1Db250cm9sMTIxMDEwMV9EeW5hbWljQ2FwdGlvbhEAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=";

            string textDecoded6 = System.Text.Encoding.UTF8.DecodeBase64(iam_first);
            string textDecoded7 = System.Text.Encoding.UTF8.DecodeBase64(iam_general);


            Console.WriteLine("123123");


            //*************************************************
            //  ЛОГИН
            //*************************************************

            //==============================================
            //  OpenConnection, SetClientSettings, GetAddInRegistrations
            // Старт клиента
            IProductNameProvider productNameProvider = new StaticProductNameProvider("Performance Test");                                                                       a9("StaticProductNameProvider");
            NavWinFormsClientSessionPreparation navWinFormsClientSessionPreparation = new NavWinFormsClientSessionPreparation(productNameProvider, false);                      a9("NavWinFormsClientSessionPreparation");
            NavWinFormsClientSession navWinFormsClientSession = new NavWinFormsClientSession(navWinFormsClientSessionPreparation);                                               a9("NavWinFormsClientSession");
            navWinFormsClientSession.Init();                                                                                                                                     a9("!!!!!!!!!!Init");

            String personalizationId = navWinFormsClientSession.UISession.SessionPersonalizationId;                                                                              a9("SessionPersonalizationId");

            String personalizationId1 = "ec29feaf-58ae-4c7a-8c7f-792d5cfd9aa0";
            String personalizationId2 = "374f138d-58a0-4b24-b6f9-da451371b033";

            IService service = navWinFormsClientSession.BuilderSession.Service;                                                                                                 a9("Service");
            IMetadataService metadataService = navWinFormsClientSession.BuilderSession.MetadataService;                                                                         a9("MetadataService");

            //==============================================
            //  GetPage

            //==============================================
            //  GetPage

            //==============================================
            //  GetNavigationFrame
            // Открытие панелей клиента
            MasterNavigation masterNavigation1 = metadataService.GetNavigationFrame(
                applyPersonalization: true,
                getNavigationFrameFromServer: true
                );

            a9("GetNavigationFrame");

            //==============================================
            //  GetNavigationFrame
            MasterNavigation masterNavigation2 = metadataService.GetNavigationFrame(
                applyPersonalization: true,
                getNavigationFrameFromServer: true
                );

            // Получение главного окна
            ActionDefinition control_Role_Center = masterNavigation2.NavigationPane.
                    Actions.Single(a => a.ALIdentifier == "Control_Home").
                    Actions.Single(a => a.Name == "Control_Role_Center") as ActionDefinition;

            a9("GetNavigationFrame");

            //==============================================
            //  GetMetadataForPageAndAllItsDependencies
            MasterPage masterPage = metadataService.GetMasterPage(
                pageId: control_Role_Center.TargetID, // 9006
                personalizationId: personalizationId1,
                applyPersonalization: true
                );
            //MasterPage myNotes = metadataService.GetSystemPart(
            //    partType: SystemPartTypes.MyNotes
            //    );
            //MetaTable myNotesTable = metadataService.GetTableMetadata(
            //    tableId: myNotes.PageProperties.SourceObject.SourceTable // 2000000068
            //    );

            a9("GetMetadataForPageAndAllItsDependencies");

            //==============================================
            //  GetWorkDate
            DateTime workDate = service.GetWorkDate();

            a9("GetWorkDate");






            //*************************************************
            //  ПОИСК ОКНА ОТЧЕТОВ
            //*************************************************

            //==============================================
            //  GetMetadataForPageAndAllItsDependencies

            MasterPage gmfpaaid_1 = metadataService.GetMasterPage(
                pageId: 35610,
                personalizationId: personalizationId2,
                applyPersonalization: true
            );

            //CodeUnitResponse aaaa = service.InvokeApplicationMethod();

            a9("GetMetadataForPageAndAllItsDependencies");

            //==============================================
            //  lnvokeApplicationMethod
            NavVisualizationHelper.Initialize(service);

            a9("lnvokeApplicationMethod");

            //==============================================
            //  OpenForm
            string nofa_1_mf_cr = "JgAAAACLAgAAAAJ7/x8EHgQQBBIELQAyADEALQAwADAAMAAyADYAAAAAAA==";

            NavOpenFormArguments nofa_1_mf = new NavOpenFormArguments()
            {
                State = new NavRecordState()
                {
                    CurrentRecord = Convert.FromBase64String(nofa_1_mf_cr),
                    FormId = 35610, // gmfpaaid_1.ID, 
                    PersonalizationId = personalizationId2,
                    ParentFormId = 0,
                    NavFormEditable = false,
                    RenamingMode = RenamingMode.SingleKeyServerSide,
                    TableView = new NavTableView()
                    {
                        Ascending = true,
                        TableId = 38,//gmfpaaid_1.PageProperties.SourceObject.SourceTable,
                        SearchFilter = new NavFilterGroup()
                        {
                            FilterGroupNo = -1,
                            Filters = new NavFilter[0]
                        }
                    },
                    ValidateFieldsInOnNewRecord = true,
                    ValidateRequired = true
                }
            };
            NavOpenFormArguments[] nofa_1_sf = null;

            service.OpenForm(
                    mainForm: ref nofa_1_mf,
                    subForms: ref nofa_1_sf
                );

            a9("OpenForm");

            //==============================================
            //  GetPage
            NavRecordState gp_mf_1 = nofa_1_mf.State;
            string gp_sb_1 = "JgAAAACLAgAAAAJ7/x8EHgQQBBIELQAyADEALQAwADAAMAAyADYAAAAAAA==";


            service.GetPage(
                pageRequestDefinition: new PageRequestDefinition()
                {
                    IncludeMoreDataInformation = true,
                    IncludeNonRowData = true,
                    PageSize = 50,
                    PageSizeInOppositeDirection = 50,
                    ReadDirection = ReadDirection.Next,
                    StartFromPage = StartingPage.Specific,
                    StartingBookmark = Convert.FromBase64String(gp_sb_1)
                },
                state: ref gp_mf_1
                );

            a9("GetPage");

            //*************************************************
            //  СОЗДАНИЕ ОТЧЕТА
            //*************************************************

            //==============================================
            //  GetMetadataForPageAndAllItsDependencies

            MasterPage gmfpaaid_2 = metadataService.GetMasterPage(
                pageId: 12431,
                personalizationId: string.Empty,
                applyPersonalization: true
            );

            a9("GetMetadataForPageAndAllItsDependencies");

            //==============================================
            //  OpenForm
            NavOpenFormArguments nofa_2_mf = new NavOpenFormArguments()
            {
                ControlId = null,

                State = new NavRecordState()
                {
                    CurrentRecord = null,
                    FormId = 12431, //gmfpaaid_2.ID
                    //PersonalizationId = null,
                    ParentFormId = 0,
                    NavFormEditable = true,
                    RenamingMode = RenamingMode.SingleKeyServerSide,
                    TableView = new NavTableView()
                    {
                        Ascending = true,
                        TableId = 38,
                        CurrentSortingFieldIds = new int[2] { 1, 3 },
                        SearchFilter = new NavFilterGroup()
                        {
                            FilterGroupNo = -1,
                            Filters = new NavFilter[0]
                        },
                        CurrentFilters = new NavFilterGroup[1] {
                            new NavFilterGroup() {
                                FilterGroupNo = 2,
                                Filters = new NavFilter[2]{
                                    new NavFilter(){
                                        FilterField = 1,
                                        FilterValue = "2",
                                        IsExactValue = true,
                                        OptionsAsCaptionsFilterValue = "Invoice",
                                        UserTypedFilterValue = null
                                    },
                                    new NavFilter(){
                                        FilterField = 12400,
                                        FilterValue = "1",
                                        IsExactValue = true,
                                        OptionsAsCaptionsFilterValue = "Yes",
                                        UserTypedFilterValue = null
                                    }
                                }
                            }
                        }
                    },
                    ValidateFieldsInOnNewRecord = true,
                    ValidateRequired = true
                }
            };
            NavOpenFormArguments[] nofa_2_sf = new List<NavOpenFormArguments>().Append(new NavOpenFormArguments()
            {
                ControlId = "1210001",

                State = new NavRecordState()
                {                    
                    CurrentRecord = null,
                    FormId = 12432, 
                    //PersonalizationId = personalizationId2,
                    ParentFormId = 12431,
                    NavFormEditable = true,
                    RenamingMode = RenamingMode.NoKeys,
                    TableView = new NavTableView()
                    {
                        Ascending = true,
                        TableId = 39,
                        SearchFilter = new NavFilterGroup()
                        {
                            FilterGroupNo = -1,
                            Filters = new NavFilter[0]
                        }
                    },
                    ValidateFieldsInOnNewRecord = true,
                    ValidateRequired = true
                }
            }).ToArray();

            service.OpenForm(
                        mainForm: ref nofa_2_mf,
                        subForms: ref nofa_2_sf
                    );

            a9("OpenForm");

            //}
            //==============================================
            //  lnvokeApplicationMethod
            //string ApplicationMethodRequestDataSet10 = "B2RhdGFTZXR/AAAAAQAAAA9QdXJjaGFzZSBIZWFkZXIJBAAAsgAAAAEwCgAAAAAIYm9va21hcmsTAAAAAAExCAAAAAABMhEAAAAAATMRAAAAAAE0EQAAAAABNREAAAAAATYRAAAAAAE3EQAAAAABOBEAAAAAATkRAAAAAAIxMBEAAAAAAjExEQAAAAACMTIRAAAAAAIxMxEAAAAAAjE0EQAAAAACMTURAAAAAAIxNhEAAAAAAjE3EQAAAAACMTgRAAAAAAIxOQ8AAAAAAjIwDwAAAAACMjEPAAAAAAIyMhEAAAAAAjIzEQAAAAACMjQPAAAAAAIyNQ4AAAAAAjI2DwAAAAACMjcRAAAAAAIyOBEAAAAAAjI5EQAAAAACMzARAAAAAAIzMREAAAAAAjMyEQAAAAACMzMOAAAAAAIzNQIAAAAAAjM3EQAAAAACNDERAAAAAAI0MxEAAAAAAjQ1EQAAAAACNDYCAAAAAAI0NwgAAAAAAjUxEQAAAAACNTIIAAAAAAI1MxEAAAAAAjU1EQAAAAACNTYCAAAAAAI1NwIAAAAAAjU4AgAAAAACNTkCAAAAAAI2MA4AAAAAAjYxDgAAAAACNjIRAAAAAAI2MxEAAAAAAjY0EQAAAAACNjURAAAAAAI2NhEAAAAAAjY3EQAAAAACNjgRAAAAAAI2OREAAAAAAjcwEQAAAAACNzIRAAAAAAI3MxEAAAAAAjc0EQAAAAACNzYRAAAAAAI3NxEAAAAAAjc4EQAAAAACNzkRAAAAAAI4MBEAAAAAAjgxEQAAAAACODIRAAAAAAI4MxEAAAAAAjg0EQAAAAACODURAAAAAAI4NhEAAAAAAjg3EQAAAAACODgRAAAAAAI4OREAAAAAAjkwEQAAAAACOTERAAAAAAI5MhEAAAAAAjkzEQAAAAACOTQIAAAAAAI5NREAAAAAAjk3EQAAAAACOTgCAAAAAAI5OQ8AAAAAAzEwMREAAAAAAzEwMhEAAAAAAzEwNBEAAAAAAzEwNxEAAAAAAzEwOBEAAAAAAzEwOREAAAAAAzExNBEAAAAAAzExNQIAAAAAAzExNhEAAAAAAzExOBEAAAAAAzExOQ4AAAAAAzEyMAgAAAAAAzEyMQgAAAAAAzEyMg4AAAAAAzEyMwIAAAAAAzEyNAgAAAAAAzEyNREAAAAAAzEyNhEAAAAAAzEyOQgAAAAAAzEzMBEAAAAAAzEzMREAAAAAAzEzMhEAAAAAAzEzMxEAAAAAAzEzNA4AAAAAAzEzNREAAAAAAzEzNgIAAAAAAzEzNw8AAAAAAzEzOBEAAAAAAzEzOREAAAAAAzE0Mg8AAAAAAzE0MxEAAAAAAzE0NA4AAAAAAzE1MREAAAAAAzE2MAgAAAAAAzE2MRIAAAAAAzE2NQgAAAAAAzE3MBEAAAAAAzE3MREAAAAAAzMwMA4AAAAAAzMwMQ4AAAAAAzQ4MAgAAAAABDEzMDUOAAAAAAQ1MDQzCAAAAAAENTA0OAgAAAAABDUwNTARAAAAAAQ1MDUyEQAAAAAENTA1MxEAAAAABDU3MDARAAAAAAQ1NzUyAgAAAAAENTc1MwgAAAAABDU3OTAPAAAAAAQ1NzkxDwAAAAAENTc5MhEAAAAABDU3OTMRAAAAAAQ1ODAwEQAAAAAENTgwMREAAAAABDU4MDIRAAAAAAQ1ODAzAgAAAAAENTgwNBEAAAAABDgwMDASAAAAAAQ5MDAwEQAAAAAEOTAwMQgAAAAABTEyNDAwAgAAAAAFMTI0MDERAAAAAAUxMjQwMhEAAAAABTEyNDAzCAAAAAAFMTI0MDQCAAAAAAUxMjQzNwgAAAAABTEyNDM4CAAAAAAFMTI0NDACAAAAAAUxMjQ0MQgAAAAABTEyNDQyEQAAAAAFMTI0NDMIAAAAAAUxMjQ0NBEAAAAABTEyNDQ1EQAAAAAFMTI0NDYIAAAAAAUxMjQ0NxEAAAAABTEyNDcwEQAAAAAFMTI0NzEPAAAAAAUxMjQ3Mg8AAAAABTEyNDczDwAAAAAFMTI0NzQRAAAAAAUxMjQ4MA4AAAAABTEyNDg1EQAAAAAFMTI0ODYCAAAAAAUxMjQ5MBEAAAAABTEyNDkxEQAAAAAFMTI0OTgCAAAAAAUxMjQ5OQ8AAAAABDU3NTQRAAAAAAQ1Nzk2EQAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==";
            //string textDecoded1 = System.Text.Encoding.UTF8.DecodeBase64(ApplicationMethodRequestDataSet10);
            //byte[] ApplicationMethodRequestDataSetbyte10 = Convert.FromBase64String(ApplicationMethodRequestDataSet10);
            //string ApplicationMethodRequestDataSet11 = "B2RhdGFTZXR/AAAAAQAAAA1QdXJjaGFzZSBMaW5lCQQAAOoAAAABMAoAAAAACGJvb2ttYXJrEwAAAAABMQgAAAAAATIRAAAAAAEzEQAAAAABNAgAAAAAATUIAAAAAAE2EQAAAAABNxEAAAAAATgRAAAAAAIxMA8AAAAAAjExEQAAAAACMTIRAAAAAAIxMxEAAAAAAjE1DgAAAAACMTYOAAAAAAIxNw4AAAAAAjE4DgAAAAACMjIOAAAAAAIyMw4AAAAAAjI1DgAAAAACMjcOAAAAAAIyOA4AAAAAAjI5DgAAAAACMzAOAAAAAAIzMQ4AAAAAAjMyAgAAAAACMzQOAAAAAAIzNQ4AAAAAAjM2DgAAAAACMzcOAAAAAAIzOAgAAAAAAjQwEQAAAAACNDERAAAAAAI0NREAAAAAAjU0DgAAAAACNTYCAAAAAAI1Nw4AAAAAAjU4DgAAAAACNTkOAAAAAAI2MA4AAAAAAjYxDgAAAAACNjMRAAAAAAI2NAgAAAAAAjY3DgAAAAACNjgRAAAAAAI2OQ4AAAAAAjcwEQAAAAACNzERAAAAAAI3MggAAAAAAjczAgAAAAACNzQRAAAAAAI3NREAAAAAAjc3CAAAAAACNzgRAAAAAAI3OREAAAAAAjgwCAAAAAACODERAAAAAAI4MhEAAAAAAjgzEQAAAAACODURAAAAAAI4NgIAAAAAAjg3EQAAAAACODgCAAAAAAI4OREAAAAAAjkwEQAAAAACOTERAAAAAAI5Mg4AAAAAAjkzDgAAAAACOTUOAAAAAAI5NxEAAAAAAjk4CAAAAAACOTkOAAAAAAMxMDAOAAAAAAMxMDECAAAAAAMxMDMOAAAAAAMxMDQOAAAAAAMxMDUOAAAAAAMxMDYRAAAAAAMxMDcIAAAAAAMxMDgRAAAAAAMxMDkOAAAAAAMxMTAOAAAAAAMxMTEOAAAAAAMxMTIOAAAAAAMxMTMOAAAAAAMxMTQOAAAAAAMxMTUOAAAAAAMxMTYIAAAAAAMxMTcRAAAAAAMxMTgRAAAAAAMxMTkCAAAAAAMxMjARAAAAAAMxMjEOAAAAAAMxMjIOAAAAAAMxMjMCAAAAAAMxMjQOAAAAAAMxMjkOAAAAAAMxMzARAAAAAAMxMzIOAAAAAAMxMzUOAAAAAAMxMzYOAAAAAAMxMzcOAAAAAAMxNDAOAAAAAAMxNDEOAAAAAAM0ODAIAAAAAAQxMDAxEQAAAAAEMTAwMggAAAAABDEwMDMOAAAAAAQxMDA0DgAAAAAEMTAwNQ4AAAAABDEwMDYOAAAAAAQxMDA3DgAAAAAEMTAwOA4AAAAABDEwMDkOAAAAAAQxMDEwDgAAAAAEMTAxMQ4AAAAABDEwMTIOAAAAAAQxMDEzEQAAAAAEMTAxOQgAAAAABDEwMzAOAAAAAAQxMDMxDgAAAAAEMTcwMBEAAAAABDE3MDIPAAAAAAQ1NDAxEQAAAAAENTQwMhEAAAAABDU0MDMRAAAAAAQ1NDA0DgAAAAAENTQwNxEAAAAABDU0MTUOAAAAAAQ1NDE2DgAAAAAENTQxNw4AAAAABDU0MTgOAAAAAAQ1NDU4DgAAAAAENTQ2MA4AAAAABDU0NjEOAAAAAAQ1NDk1DgAAAAAENTYwMA8AAAAABDU2MDEIAAAAAAQ1NjAyEQAAAAAENTYwMw4AAAAABDU2MDUCAAAAAAQ1NjA2AgAAAAAENTYwOREAAAAABDU2MTARAAAAAAQ1NjExEQAAAAAENTYxMhEAAAAABDU2MTMCAAAAAAQ1NzAwEQAAAAAENTcwNREAAAAABDU3MDYRAAAAAAQ1NzA3CAAAAAAENTcwOBEAAAAABDU3MDkRAAAAAAQ1NzEwAgAAAAAENTcxMREAAAAABDU3MTIRAAAAAAQ1NzEzAgAAAAAENTcxNBEAAAAABDU3MTUIAAAAAAQ1NzUwDgAAAAAENTc1MgIAAAAABDU3OTAPAAAAAAQ1NzkxDwAAAAAENTc5MhEAAAAABDU3OTMRAAAAAAQ1Nzk0DwAAAAAENTc5NQ8AAAAABDU4MDACAAAAAAQ1ODAxDgAAAAAENTgwMg4AAAAABDU4MDMOAAAAAAQ1ODA0DgAAAAAENTgwNQ4AAAAABDU4MDYOAAAAAAQ1ODA3DgAAAAAENTgwOA4AAAAABDU4MDkOAAAAAAQ1ODEwDgAAAAAENjYwMBEAAAAABDY2MDEIAAAAAAQ2NjA4EQAAAAAENjYwOQgAAAAABTEyNDAwEQAAAAAFMTI0MDEIAAAAAAUxMjQwMg8AAAAABTEyNDAzEQAAAAAFMTI0MDQRAAAAAAUxMjQwNREAAAAABTEyNDMwDgAAAAAFMTI0MzEOAAAAAAUxMjQ4NQIAAAAABTEyNDg2EQAAAAAFMTI0ODcCAAAAAAUxMjQ5MBEAAAAABTE3MzAwEQAAAAAIOTkwMDA3NTARAAAAAAg5OTAwMDc1MREAAAAACDk5MDAwNzUyEQAAAAAIOTkwMDA3NTMCAAAAAAg5OTAwMDc1NAgAAAAACDk5MDAwNzU1DgAAAAAIOTkwMDA3NTYCAAAAAAg5OTAwMDc1NwgAAAAACDk5MDAwNzU4EQAAAAAIOTkwMDA3NTkIAAAAABVDb250cm9sMTIxMDAzMV9Gb3JtYXQRAAAAABVDb250cm9sMTIxMDAzN19Gb3JtYXQRAAAAABVDb250cm9sMTIxMDAzOV9Gb3JtYXQRAAAAABVDb250cm9sMTIxMDA0MV9Gb3JtYXQRAAAAABVDb250cm9sMTIxMDA0M19Gb3JtYXQRAAAAABVDb250cm9sMTIxMDA0NV9Gb3JtYXQRAAAAABVDb250cm9sMTIxMDA0N19Gb3JtYXQRAAAAABVDb250cm9sMTIxMDA0OV9Gb3JtYXQRAAAAABVDb250cm9sMTIxMDA1M19Gb3JtYXQRAAAAABVDb250cm9sMTIxMDA1N19Gb3JtYXQRAAAAABVDb250cm9sMTIxMDA1OV9Gb3JtYXQRAAAAAA5Db250cm9sMTIxMDA5MREAAAAADkNvbnRyb2wxMjEwMDkzEQAAAAAOQ29udHJvbDEyMTAwOTURAAAAAA5Db250cm9sMTIxMDA5NxEAAAAADkNvbnRyb2wxMjEwMDk5EQAAAAAOQ29udHJvbDEyMTAxMDERAAAAAB1Db250cm9sMTIxMDAwN19EeW5hbWljQ2FwdGlvbhEAAAAAHUNvbnRyb2wxMjEwMDM3X0R5bmFtaWNDYXB0aW9uEQAAAAAdQ29udHJvbDEyMTAwNDVfRHluYW1pY0NhcHRpb24RAAAAAB1Db250cm9sMTIxMDA4N19EeW5hbWljQ2FwdGlvbhEAAAAAHUNvbnRyb2wxMjEwMDg5X0R5bmFtaWNDYXB0aW9uEQAAAAAdQ29udHJvbDEyMTAwOTFfRHluYW1pY0NhcHRpb24RAAAAAB1Db250cm9sMTIxMDA5M19EeW5hbWljQ2FwdGlvbhEAAAAAHUNvbnRyb2wxMjEwMDk1X0R5bmFtaWNDYXB0aW9uEQAAAAAdQ29udHJvbDEyMTAwOTdfRHluYW1pY0NhcHRpb24RAAAAAB1Db250cm9sMTIxMDA5OV9EeW5hbWljQ2FwdGlvbhEAAAAAHUNvbnRyb2wxMjEwMTAxX0R5bmFtaWNDYXB0aW9uEQAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
            //string textDecoded2 = System.Text.Encoding.UTF8.DecodeBase64(ApplicationMethodRequestDataSet11);
            //byte[] ApplicationMethodRequestDataSetbyte11 = Convert.FromBase64String(ApplicationMethodRequestDataSet11);

            //string ApplicationMethodRequestDataSet12 = "JgAAAACLAgAAAAJ7/x8EHgQQBBIELQAyADEALQAwADAAMAAyADYAAAAAAA==";
            //string textDecoded3 = System.Text.Encoding.UTF8.DecodeBase64(ApplicationMethodRequestDataSet12);
            //byte[] ApplicationMethodRequestDataSetbyte10 = Convert.FromBase64String(ApplicationMethodRequestDataSet10);

            //service.InvokeApplicationMethod(ApplicationCodeType.FormCode, 12431, "NewRecord", dataSet: ref nofa_2_mf.DataSet, state: ref nofa_2_mf.State, null);

            NavRecordState iam_s_1 = nofa_2_mf.State;
            NavDataSet iam_nds_1 = nofa_2_mf.DataSet;
            int iam_s_fid_1 = nofa_2_mf.State.FormId;
            object[] iam_obj_1 = new object[1];     iam_obj_1[0] = true;

            //извлекаем из структуры NAV отражением и проверяем что внурри до перезаписи
            var recdatasetref_1 = iam_nds_1.GetType().GetProperty("DataSet", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public);
            var recdataset_1 = recdatasetref_1.GetValue(iam_nds_1);
            byte[] databyte_1 = (byte[])recdataset_1.GetType().GetProperty("Data").GetValue(recdataset_1);

            string datastr_original_1 = System.Text.Encoding.UTF8.GetString((byte[])databyte_1);


            //************************************
            //       DATA FIELD CORRELATION
            //

            //записываем в структуру NAV отражением
            string DataSet_str_iam_1 = "B2RhdGFTZXR/AAAAAQAAAA9QdXJjaGFzZSBIZWFkZXIJBAAAswAAAAEwCgAAAAAIYm9va21hcmsTAAAAAAExCAAAAAABMhEAAAAAATMRAAAAAAE0EQAAAAABNREAAAAAATYRAAAAAAE3EQAAAAABOBEAAAAAATkRAAAAAAIxMBEAAAAAAjExEQAAAAACMTIRAAAAAAIxMxEAAAAAAjE0EQAAAAACMTURAAAAAAIxNhEAAAAAAjE3EQAAAAACMTgRAAAAAAIxOQ8AAAAAAjIwDwAAAAACMjEPAAAAAAIyMhEAAAAAAjIzEQAAAAACMjQPAAAAAAIyNQ4AAAAAAjI2DwAAAAACMjcRAAAAAAIyOBEAAAAAAjI5EQAAAAACMzARAAAAAAIzMREAAAAAAjMyEQAAAAACMzMOAAAAAAIzNQIAAAAAAjM3EQAAAAACNDERAAAAAAI0MxEAAAAAAjQ1EQAAAAACNDYCAAAAAAI0NwgAAAAAAjUxEQAAAAACNTIIAAAAAAI1MxEAAAAAAjU1EQAAAAACNTYCAAAAAAI1NwIAAAAAAjU4AgAAAAACNTkCAAAAAAI2MA4AAAAAAjYxDgAAAAACNjIRAAAAAAI2MxEAAAAAAjY0EQAAAAACNjURAAAAAAI2NhEAAAAAAjY3EQAAAAACNjgRAAAAAAI2OREAAAAAAjcwEQAAAAACNzIRAAAAAAI3MxEAAAAAAjc0EQAAAAACNzYRAAAAAAI3NxEAAAAAAjc4EQAAAAACNzkRAAAAAAI4MBEAAAAAAjgxEQAAAAACODIRAAAAAAI4MxEAAAAAAjg0EQAAAAACODURAAAAAAI4NhEAAAAAAjg3EQAAAAACODgRAAAAAAI4OREAAAAAAjkwEQAAAAACOTERAAAAAAI5MhEAAAAAAjkzEQAAAAACOTQIAAAAAAI5NREAAAAAAjk3EQAAAAACOTgCAAAAAAI5OQ8AAAAAAzEwMREAAAAAAzEwMhEAAAAAAzEwNBEAAAAAAzEwNxEAAAAAAzEwOBEAAAAAAzEwOREAAAAAAzExNBEAAAAAAzExNQIAAAAAAzExNhEAAAAAAzExOBEAAAAAAzExOQ4AAAAAAzEyMAgAAAAAAzEyMQgAAAAAAzEyMg4AAAAAAzEyMwIAAAAAAzEyNAgAAAAAAzEyNREAAAAAAzEyNhEAAAAAAzEyOQgAAAAAAzEzMBEAAAAAAzEzMREAAAAAAzEzMhEAAAAAAzEzMxEAAAAAAzEzNA4AAAAAAzEzNREAAAAAAzEzNgIAAAAAAzEzNw8AAAAAAzEzOBEAAAAAAzEzOREAAAAAAzE0Mg8AAAAAAzE0MxEAAAAAAzE0NA4AAAAAAzE1MREAAAAAAzE2MAgAAAAAAzE2MRIAAAAAAzE2NQgAAAAAAzE3MBEAAAAAAzE3MREAAAAAAzMwMA4AAAAAAzMwMQ4AAAAAAzQ4MAgAAAAABDEzMDUOAAAAAAQ1MDQzCAAAAAAENTA0OAgAAAAABDUwNTARAAAAAAQ1MDUyEQAAAAAENTA1MxEAAAAABDU3MDARAAAAAAQ1NzUxAgAAAAAENTc1MgIAAAAABDU3NTMIAAAAAAQ1NzkwDwAAAAAENTc5MQ8AAAAABDU3OTIRAAAAAAQ1NzkzEQAAAAAENTgwMBEAAAAABDU4MDERAAAAAAQ1ODAyEQAAAAAENTgwMwIAAAAABDU4MDQRAAAAAAQ4MDAwEgAAAAAEOTAwMBEAAAAABDkwMDEIAAAAAAUxMjQwMAIAAAAABTEyNDAxEQAAAAAFMTI0MDIRAAAAAAUxMjQwMwgAAAAABTEyNDA0AgAAAAAFMTI0MzcIAAAAAAUxMjQzOAgAAAAABTEyNDQwAgAAAAAFMTI0NDEIAAAAAAUxMjQ0MhEAAAAABTEyNDQzCAAAAAAFMTI0NDQRAAAAAAUxMjQ0NREAAAAABTEyNDQ2CAAAAAAFMTI0NDcRAAAAAAUxMjQ3MBEAAAAABTEyNDcxDwAAAAAFMTI0NzIPAAAAAAUxMjQ3Mw8AAAAABTEyNDc0EQAAAAAFMTI0ODAOAAAAAAUxMjQ4NREAAAAABTEyNDg2AgAAAAAFMTI0OTARAAAAAAUxMjQ5MREAAAAABTEyNDk4AgAAAAAFMTI0OTkPAAAAAAQ1NzU0EQAAAAAENTc5NhEAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
            byte[] DataSet_iam_1 = Convert.FromBase64String(DataSet_str_iam_1);

            NavDataSet NavDataSet_0 = new NavDataSet { DataSetName = "NewDataSet" };

            var datasetdata_0 = NavDataSet_0.GetType().GetProperty("DataSet", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public).GetValue(NavDataSet_0);
            datasetdata_0.GetType().GetProperty("Data", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public).SetValue(datasetdata_0, DataSet_iam_1);
            NavDataSet_0.GetType().GetProperty("DataSet", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public).SetValue(NavDataSet_0, datasetdata_0);

            iam_nds_1 = NavDataSet_0;   //запись правильного поля Data, автоматически генерируется неправильно

            //извлекаем из структуры NAV отражением и проверяем что записалось
            var recdatasetref_2 = iam_nds_1.GetType().GetProperty("DataSet", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public);
            var recdataset_2 = recdatasetref_2.GetValue(iam_nds_1);
            byte[] databyte_2 = (byte[])recdataset_2.GetType().GetProperty("Data").GetValue(recdataset_2);

            string datastr_original_2 = System.Text.Encoding.UTF8.GetString((byte[])databyte_2);

            //************************************

            service.InvokeApplicationMethod(
                objectType: ApplicationCodeType.FormCode,
                objectId: iam_s_fid_1,
                methodName: "NewRecord",
                dataSet: ref iam_nds_1,
                state: ref iam_s_1,
                args: ref iam_obj_1
                );
            //object InvokeApplicationMethod(ApplicationCodeType objectType, int objectId, string methodName, ref NavDataSet dataSet, ref NavRecordState state, ref object[] args);
            //InvokeApplicationMethod(INavService INavService_1, Guid ServerFromHandle, int objectId, int tableId, int formId, RenamingMode RenamingMode, string MethodName, byte[] ApplicationMethodRequestDataSetByte, ApplicationCodeType codeType)
            //InvokeApplicationMethod(INavService_1, ServerFormHandle_form_2_0, form_2.States[0].FormId, form_2.States[0].TableId, form_2.States[0].FormId, form_2.States[0].RenamingMode, "NewRecord", ApplicationMethodRequestDataSetbyte10, ApplicationCodeType.FormCode); //75 76

            NavVisualizationHelper.Initialize(service);

            a9("lnvokeApplicationMethod");

            //==============================================
            //  GetPage
            NavRecordState gp_mf_2 = nofa_2_sf[0].State;
            service.GetPage(
                pageRequestDefinition: new PageRequestDefinition()
                {
                    CalcFields = new int[2] { 5801, 5802 },
                    IncludeMoreDataInformation = true,
                    IncludeNonRowData = true,
                    PageSize = 20,
                    PageSizeInOppositeDirection = 20,
                    ReadDirection = ReadDirection.Next,
                    StartFromPage = StartingPage.Specific,
                },
                state: ref gp_mf_2
                );

            a9("GetPage");

            //==============================================
            //  lnvokeApplicationMethod

            NavVisualizationHelper.Initialize(service);

            a9("lnvokeApplicationMethod");

            //*************************************************
            //  ЗАПОЛНЕНИЕ ОТЧЕТА
            //*************************************************

            //==============================================
            //  Channel/RealAction ---------------- INSERT RECORD (!!!)SLSR(!!!)

            NavDataSet asdasda = service.InsertRecord(state: ref iam_s_1, recDataSet: iam_nds_1, true, false);

            byte[] databyte1 = returnDataByte(asdasda);
            string datastr1 = System.Text.Encoding.UTF8.GetString((byte[])databyte1);
            string poav_filter = Regex.Match(datastr1, "ПОАВ.{9}").ToString();

            a9("INSERT RECORD");

            //==============================================
            //  GetMetadataForPageAndAllItsDependencies

            MasterPage gmfpaaid_3 = metadataService.GetMasterPage(
                pageId: 27,
                personalizationId: string.Empty,
                applyPersonalization: true
            );

            a9("GetMetadataForPageAndAllItsDependencies");

            //==============================================
            //  OpenForm
            NavOpenFormArguments nofa_3_mf = new NavOpenFormArguments()
            {
                ControlId = null,

                State = new NavRecordState()
                {
                    CurrentRecord = null,
                    FormId = 27, //gmfpaaid_3.ID
                    //PersonalizationId = personalizationId2,
                    ParentFormId = 0,
                    NavFormEditable = false,
                    RenamingMode = RenamingMode.NoKeys,
                    TableView = new NavTableView()
                    {
                        Ascending = true,
                        TableId = 23,
                        SearchFilter = new NavFilterGroup()
                        {
                            FilterGroupNo = -1,
                            Filters = new NavFilter[0]
                        }
                    },
                    ValidateFieldsInOnNewRecord = true,
                    ValidateRequired = true
                }
            };
            NavOpenFormArguments[] nofa_3_sf = new List<NavOpenFormArguments>().Append(new NavOpenFormArguments()
            {
                ControlId = "1904651607",

                State = new NavRecordState()
                {
                    CurrentRecord = null,
                    FormId = 9094,
                    //PersonalizationId = personalizationId2,
                    ParentFormId = 27,
                    NavFormEditable = false,
                    RenamingMode = RenamingMode.NoKeys,
                    TableView = new NavTableView()
                    {
                        Ascending = true,
                        TableId = 23,
                        SearchFilter = new NavFilterGroup()
                        {
                            FilterGroupNo = -1,
                            Filters = new NavFilter[0]
                        }
                    },
                    ValidateFieldsInOnNewRecord = true,
                    ValidateRequired = true
                }
            }).Append(new NavOpenFormArguments()
            {
                ControlId = "1903435607",

                State = new NavRecordState()
                {
                    CurrentRecord = null,
                    FormId = 9095,
                    //PersonalizationId = personalizationId2,
                    ParentFormId = 27,
                    NavFormEditable = false,
                    RenamingMode = RenamingMode.NoKeys,
                    TableView = new NavTableView()
                    {
                        Ascending = true,
                        TableId = 23,
                        SearchFilter = new NavFilterGroup()
                        {
                            FilterGroupNo = -1,
                            Filters = new NavFilter[0]
                        }
                    },
                    ValidateFieldsInOnNewRecord = true,
                    ValidateRequired = true
                }
            }).ToArray();

            service.OpenForm(
                        mainForm: ref nofa_3_mf,
                        subForms: ref nofa_3_sf
                    );

            a9("OpenForm");

            //==============================================
            //  GetPage
            NavRecordState gp_mf_3 = nofa_3_mf.State;
            service.GetPage(
                pageRequestDefinition: new PageRequestDefinition()
                {
                    CalcFields = new int[2] { 59, 67 },
                    IncludeMoreDataInformation = true,
                    IncludeNonRowData = true,
                    PageSize = 20,
                    PageSizeInOppositeDirection = 20,
                    ReadDirection = ReadDirection.Next,
                    StartFromPage = StartingPage.Specific,
                },
                state: ref gp_mf_3
                );

            a9("GetPage");

            //==============================================
            //  GetPage
            string gp_mf_4sb = "JgAAAACLAgAAAAJ7/x8EHgQQBBIELQAyADEALQAwADAAMAAzADQAAAAAAA==";

            NavRecordState gp_mf_4 = nofa_1_mf.State;
            service.GetPage(
                pageRequestDefinition: new PageRequestDefinition()
                {
                    IncludeMoreDataInformation = false,
                    IncludeNonRowData = true,
                    PageSize = 1,
                    PageSizeInOppositeDirection = 0,
                    ReadDirection = ReadDirection.Next,
                    StartFromPage = StartingPage.Specific,
                    StartingBookmark = Convert.FromBase64String(gp_mf_4sb)
                },
                state: ref gp_mf_4
                );

            a9("GetPage");

            //==============================================
            //  GetPage
            NavRecordState gp_mf_5 = nofa_2_sf[0].State;
            service.GetPage(
                pageRequestDefinition: new PageRequestDefinition()
                {
                    CalcFields = new int[2] { 5801, 5802 },
                    IncludeMoreDataInformation = true,
                    IncludeNonRowData = true,
                    PageSize = 20,
                    PageSizeInOppositeDirection = 20,
                    ReadDirection = ReadDirection.Next,
                    StartFromPage = StartingPage.Specific,
                },
                state: ref gp_mf_5
                );

            a9("GetPage");

            //==============================================
            //  lnvokeApplicationMethod
            NavVisualizationHelper.Initialize(service);

            a9("lnvokeApplicationMethod");

            //==============================================
            //  lnvokeApplicationMethod
            NavVisualizationHelper.Initialize(service);

            a9("lnvokeApplicationMethod");

            //==============================================
            //  lnvokeApplicationMethod
            NavVisualizationHelper.Initialize(service);

            a9("lnvokeApplicationMethod");

            //==============================================
            //  CloseForm
            {
                NavCloseFormArguments ncfa_3_mf = new NavCloseFormArguments()
                {
                    ExitAction = FormResult.LookupOK,
                    DataSet = nofa_3_mf.DataSet,
                    State = nofa_3_mf.State
                };

                NavCloseFormArguments[] ncfa_3_sf = nofa_3_sf
                    .Select(sf => new NavCloseFormArguments() { DataSet = sf.DataSet, State = sf.State, ExitAction = FormResult.None })
                    .ToArray();

                //************************************
                //       DATA FIELD CORRELATION
                //Ck5ld0RhdGFTZXR/AAAAAQAAAAEwCQQAAKsAAAAIYm9va21hcmsTAAAAAAEwCgAAAAABMREAAAAAATIRAAAAAAEzEQAAAAABNBEAAAAAATURAAAAAAE2EQAAAAABNxEAAAAAATgRAAAAAAE5EQAAAAACMTARAAAAAAIxNBEAAAAAAjE1EQAAAAACMTYRAAAAAAIxNxEAAAAAAjE5DgAAAAACMjERAAAAAAIyMhEAAAAAAjI0EQAAAAACMjYIAAAAAAIyNxEAAAAAAjI4EQAAAAACMjkRAAAAAAIzMBEAAAAAAjMxEQAAAAACMzMRAAAAAAIzNREAAAAAAjM5CAAAAAACNDURAAAAAAI0NggAAAAAAjQ3EQAAAAACNTMPAAAAAAI1NA8AAAAAAjgwCAAAAAACODICAAAAAAI4NBEAAAAAAjg1EQAAAAACODYRAAAAAAI4OBEAAAAAAjg5EwAAAAACOTARAAAAAAI5MREAAAAAAjkyEQAAAAADMTAyEQAAAAADMTAzEQAAAAADMTA3EQAAAAADMTA4EQAAAAADMTA5AgAAAAADMTEwEQAAAAADMTE2AgAAAAADMTE5EQAAAAADMTI0DgAAAAADMTMyCAAAAAADMTQwFAAAAAADMTUwAgAAAAADMTYwAgAAAAADMTcwEQAAAAADMjg4EQAAAAADODQwEQAAAAAENTA0OREAAAAABDU3MDARAAAAAAQ1NzAxEQAAAAAENTc5MBEAAAAABDc2MDARAAAAAAQ3NjAxEQAAAAAENzYwMgIAAAAABDgwMDASAAAAAAQ4MDAxEgAAAAAEODAwMhIAAAAABDgwMDMSAAAAAAUxMjQwMBEAAAAABTEyNDAxEQAAAAAFMTI0MDIRAAAAAAUxMjQwMxEAAAAABTEyNDA1EQAAAAAFMTI0MDYRAAAAAAUxMjQwOREAAAAABTEyNDEwAgAAAAAFMTI0MTERAAAAAAUxMjQxMggAAAAABTEyNDEzCAAAAAAFMTI0MTQRAAAAAAUxMjQzMggAAAAABTEyNDgwEQAAAAAFMTI0ODERAAAAAAUxMjQ5MAgAAAAABTEyNDk0EQAAAAACNTUPAAAAAAI1NhEAAAAAAjU3EQAAAAADMTExEQAAAAAFMTI0MjURAAAAAAUxMjQyNg8AAAAABTEyNDkxEQAAAAACMzgCAAAAAAI1OA4AAAAAAjU5DgAAAAACNjAOAAAAAAI2MQ4AAAAAAjYyDgAAAAACNjQOAAAAAAI2NQ4AAAAAAjY2DgAAAAACNjcOAAAAAAI2OQ4AAAAAAjcwDgAAAAACNzEOAAAAAAI3Mg4AAAAAAjc0DgAAAAACNzUOAAAAAAI3Ng4AAAAAAjc3DgAAAAACNzgOAAAAAAI3OQ4AAAAAAjk3DgAAAAACOTgOAAAAAAI5OQ4AAAAAAzEwMA4AAAAAAzEwNA4AAAAAAzEwNQ4AAAAAAzExMw4AAAAAAzExNA4AAAAAAzExNw4AAAAAAzExOA4AAAAAAzEyMA4AAAAAAzEyMQ4AAAAAAzEyMg4AAAAAAzEyMw4AAAAAAzEyNQ4AAAAAAzEyNg4AAAAAAzEzMAgAAAAAAzEzMQgAAAAABDcxNzcIAAAAAAQ3MTc4CAAAAAAENzE3OQgAAAAABDcxODAIAAAAAAQ3MTgxCAAAAAAENzE4MggAAAAABDcxODMIAAAAAAQ3MTg0CAAAAAAENzE4NQgAAAAABDcxODYIAAAAAAQ3MTg3CAAAAAAENzE4OAgAAAAABDcxODkIAAAAAAQ3MTkwCAAAAAAENzE5MQgAAAAABDcxOTIIAAAAAAQ3MTkzCAAAAAAENzE5NAgAAAAABDcxOTUIAAAAAAQ3MTk2CAAAAAAENzE5NwgAAAAABDcxOTgIAAAAAAUxMjQwNBEAAAAABTEyNDI3DgAAAAAFMTI0MjgOAAAAAAUxMjQyOQ4AAAAABTEyNDMwDgAAAAAFMTI0MzEOAAAAABtTb2NpYWxMaXN0ZW5pbmdTZXR1cFZpc2libGUCAAAAABZTb2NpYWxMaXN0ZW5pbmdWaXNpYmxlAgAAAAAYT3BlbkFwcHJvdmFsRW50cmllc0V4aXN0AgAAAAAaQ2FuQ2FuY2VsQXBwcm92YWxGb3JSZWNvcmQCAAAAAA5Qb3dlckJJVmlzaWJsZQIAAAAADVJlc3luY1Zpc2libGUCAAAAABlDYW5SZXF1ZXN0QXBwcm92YWxGb3JGbG93AgAAAAAYQ2FuQ2FuY2VsQXBwcm92YWxGb3JGbG93AgAAAAAQQ29udHJvbDMyX0Zvcm1hdBEAAAAAEENvbnRyb2wzNF9Gb3JtYXQRAAAAAAEAAAACFQAAABcAAAACewU2ADIAMAAwADAAAAAAAAJu6QgAAAAAAAIFNjIwMDACH9CX0JDQniAi0KHQv9C+0YDRgtC80LDRgdGC0LXRgCICH9CX0JDQniAi0KHQn9Ce0KDQotCc0JDQodCi0JXQoCICAAIi0YPQuy4g0JHQvtGC0LDQvdC40YfQtdGB0LrQsNGPLCA0NAIAAgzQnNC+0YHQutCy0LACAAIAAgACAAIAAgACAAIAAAAAAAAAAAAAAAAAAAAAAgc2MC0xMDEwAgACAAIAAAAAAgTQndCfAgACBNCS0JUCEtCh0KIu0Jgg0KTQoNCQ0KXQogIAAgU2MjAwMAIAAgAAAAACAAIDAAAAAgACgCvjUDst1wgBAAAAAgAAQwDdLNcIAgAAAAIAAAAAAgACAAIAAgACDNCR0JjQl9Cd0JXQoQACAAIGMTAzMDU0AgACAAIAAgACAAIAAg7Qn9Ce0JrQo9Cf0JrQkAIAAgACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAgEAAAAAAgACAAIAAgACAAIAAgzQnNCe0KHQmtCS0JACCtCR0JXQm9Cr0JkCAAIAAgACAAJZjbo/4WEPQISpaIdh4YfYAgAAAAAAAAAAAAAAAAAAAAACL87I70jmXk6sfXy+RoMLVQIAAAAAAAAAAAAAAAAAAAAAAgACAAIAAgACAAIAAgACAAIAAgAAAAACAAAAAAIAAgAAAAACAAIAAgAAAAACCdCf0J7Qmi0wMgAAAAAAAAACAAIAAAAAAAAAAAAAAAAAAAAAAjQMWwQAAAAAAAAAAAAAAQACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACNAxbBAAAAAAAAAAAAAABAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAIAAAAAAgAAAAACAAAAAAIAAAAAAgAAAAACAAAAAAIAAAAAAgAAAAACAAAAAAIAAAAAAgAAAAACAAAAAAIAAAAAAgAAAAACAAAAAAIAAAAAAgAAAAACAAAAAAIAAAAAAgAAAAACAAAAAAIAAAAAAgAAAAACAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAIAAgACAAIBAgACAAIAAggjLCMjMC4wMAIIIywjIzAuMDA=
                string DataSet_str_cf_1 = "Ck5ld0RhdGFTZXR/AAAAAQAAAAEwCQQAAKsAAAAIYm9va21hcmsTAAAAAAEwCgAAAAABMREAAAAAATIRAAAAAAEzEQAAAAABNBEAAAAAATURAAAAAAE2EQAAAAABNxEAAAAAATgRAAAAAAE5EQAAAAACMTARAAAAAAIxNBEAAAAAAjE1EQAAAAACMTYRAAAAAAIxNxEAAAAAAjE5DgAAAAACMjERAAAAAAIyMhEAAAAAAjI0EQAAAAACMjYIAAAAAAIyNxEAAAAAAjI4EQAAAAACMjkRAAAAAAIzMBEAAAAAAjMxEQAAAAACMzMRAAAAAAIzNREAAAAAAjM5CAAAAAACNDURAAAAAAI0NggAAAAAAjQ3EQAAAAACNTMPAAAAAAI1NA8AAAAAAjgwCAAAAAACODICAAAAAAI4NBEAAAAAAjg1EQAAAAACODYRAAAAAAI4OBEAAAAAAjg5EwAAAAACOTARAAAAAAI5MREAAAAAAjkyEQAAAAADMTAyEQAAAAADMTAzEQAAAAADMTA3EQAAAAADMTA4EQAAAAADMTA5AgAAAAADMTEwEQAAAAADMTE2AgAAAAADMTE5EQAAAAADMTI0DgAAAAADMTMyCAAAAAADMTQwFAAAAAADMTUwAgAAAAADMTYwAgAAAAADMTcwEQAAAAADMjg4EQAAAAADODQwEQAAAAAENTA0OREAAAAABDU3MDARAAAAAAQ1NzAxEQAAAAAENTc5MBEAAAAABDc2MDARAAAAAAQ3NjAxEQAAAAAENzYwMgIAAAAABDgwMDASAAAAAAQ4MDAxEgAAAAAEODAwMhIAAAAABDgwMDMSAAAAAAUxMjQwMBEAAAAABTEyNDAxEQAAAAAFMTI0MDIRAAAAAAUxMjQwMxEAAAAABTEyNDA1EQAAAAAFMTI0MDYRAAAAAAUxMjQwOREAAAAABTEyNDEwAgAAAAAFMTI0MTERAAAAAAUxMjQxMggAAAAABTEyNDEzCAAAAAAFMTI0MTQRAAAAAAUxMjQzMggAAAAABTEyNDgwEQAAAAAFMTI0ODERAAAAAAUxMjQ5MAgAAAAABTEyNDk0EQAAAAACNTUPAAAAAAI1NhEAAAAAAjU3EQAAAAADMTExEQAAAAAFMTI0MjURAAAAAAUxMjQyNg8AAAAABTEyNDkxEQAAAAACMzgCAAAAAAI1OA4AAAAAAjU5DgAAAAACNjAOAAAAAAI2MQ4AAAAAAjYyDgAAAAACNjQOAAAAAAI2NQ4AAAAAAjY2DgAAAAACNjcOAAAAAAI2OQ4AAAAAAjcwDgAAAAACNzEOAAAAAAI3Mg4AAAAAAjc0DgAAAAACNzUOAAAAAAI3Ng4AAAAAAjc3DgAAAAACNzgOAAAAAAI3OQ4AAAAAAjk3DgAAAAACOTgOAAAAAAI5OQ4AAAAAAzEwMA4AAAAAAzEwNA4AAAAAAzEwNQ4AAAAAAzExMw4AAAAAAzExNA4AAAAAAzExNw4AAAAAAzExOA4AAAAAAzEyMA4AAAAAAzEyMQ4AAAAAAzEyMg4AAAAAAzEyMw4AAAAAAzEyNQ4AAAAAAzEyNg4AAAAAAzEzMAgAAAAAAzEzMQgAAAAABDcxNzcIAAAAAAQ3MTc4CAAAAAAENzE3OQgAAAAABDcxODAIAAAAAAQ3MTgxCAAAAAAENzE4MggAAAAABDcxODMIAAAAAAQ3MTg0CAAAAAAENzE4NQgAAAAABDcxODYIAAAAAAQ3MTg3CAAAAAAENzE4OAgAAAAABDcxODkIAAAAAAQ3MTkwCAAAAAAENzE5MQgAAAAABDcxOTIIAAAAAAQ3MTkzCAAAAAAENzE5NAgAAAAABDcxOTUIAAAAAAQ3MTk2CAAAAAAENzE5NwgAAAAABDcxOTgIAAAAAAUxMjQwNBEAAAAABTEyNDI3DgAAAAAFMTI0MjgOAAAAAAUxMjQyOQ4AAAAABTEyNDMwDgAAAAAFMTI0MzEOAAAAABtTb2NpYWxMaXN0ZW5pbmdTZXR1cFZpc2libGUCAAAAABZTb2NpYWxMaXN0ZW5pbmdWaXNpYmxlAgAAAAAYT3BlbkFwcHJvdmFsRW50cmllc0V4aXN0AgAAAAAaQ2FuQ2FuY2VsQXBwcm92YWxGb3JSZWNvcmQCAAAAAA5Qb3dlckJJVmlzaWJsZQIAAAAADVJlc3luY1Zpc2libGUCAAAAABlDYW5SZXF1ZXN0QXBwcm92YWxGb3JGbG93AgAAAAAYQ2FuQ2FuY2VsQXBwcm92YWxGb3JGbG93AgAAAAAQQ29udHJvbDMyX0Zvcm1hdBEAAAAAEENvbnRyb2wzNF9Gb3JtYXQRAAAAAAEAAAACFQAAABcAAAACewU2ADIAMAAwADAAAAAAAAJu6QgAAAAAAAIFNjIwMDACH9CX0JDQniAi0KHQv9C+0YDRgtC80LDRgdGC0LXRgCICH9CX0JDQniAi0KHQn9Ce0KDQotCc0JDQodCi0JXQoCICAAIi0YPQuy4g0JHQvtGC0LDQvdC40YfQtdGB0LrQsNGPLCA0NAIAAgzQnNC+0YHQutCy0LACAAIAAgACAAIAAgACAAIAAAAAAAAAAAAAAAAAAAAAAgc2MC0xMDEwAgACAAIAAAAAAgTQndCfAgACBNCS0JUCEtCh0KIu0Jgg0KTQoNCQ0KXQogIAAgU2MjAwMAIAAgAAAAACAAIDAAAAAgACgCvjUDst1wgBAAAAAgAAQwDdLNcIAgAAAAIAAAAAAgACAAIAAgACDNCR0JjQl9Cd0JXQoQACAAIGMTAzMDU0AgACAAIAAgACAAIAAg7Qn9Ce0JrQo9Cf0JrQkAIAAgACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAgEAAAAAAgACAAIAAgACAAIAAgzQnNCe0KHQmtCS0JACCtCR0JXQm9Cr0JkCAAIAAgACAAJZjbo/4WEPQISpaIdh4YfYAgAAAAAAAAAAAAAAAAAAAAACL87I70jmXk6sfXy+RoMLVQIAAAAAAAAAAAAAAAAAAAAAAgACAAIAAgACAAIAAgACAAIAAgAAAAACAAAAAAIAAgAAAAACAAIAAgAAAAACCdCf0J7Qmi0wMgAAAAAAAAACAAIAAAAAAAAAAAAAAAAAAAAAAjQMWwQAAAAAAAAAAAAAAQACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACNAxbBAAAAAAAAAAAAAABAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAIAAAAAAgAAAAACAAAAAAIAAAAAAgAAAAACAAAAAAIAAAAAAgAAAAACAAAAAAIAAAAAAgAAAAACAAAAAAIAAAAAAgAAAAACAAAAAAIAAAAAAgAAAAACAAAAAAIAAAAAAgAAAAACAAAAAAIAAAAAAgAAAAACAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAIAAgACAAIBAgACAAIAAggjLCMjMC4wMAIIIywjIzAuMDA=";
                byte[] DataSet_cf_1 = Convert.FromBase64String(DataSet_str_cf_1);

                NavDataSet NavDataSet_1 = new NavDataSet { DataSetName = "NewDataSet" };

                var datasetdata_1 = NavDataSet_1.GetType().GetProperty("DataSet", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public).GetValue(NavDataSet_1);
                datasetdata_1.GetType().GetProperty("Data", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public).SetValue(datasetdata_1, DataSet_cf_1);
                NavDataSet_1.GetType().GetProperty("DataSet", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public).SetValue(NavDataSet_1, datasetdata_1);

                ncfa_3_mf.DataSet = NavDataSet_1;
                //************************************

                service.CloseForm(
                    ref ncfa_3_mf,
                    ref ncfa_3_sf,
                    force: false);
            }

            a9("CloseForm");

            //==============================================
            //  ValidateField
            NavRecordState iam_s_2 = nofa_3_mf.State;
            NavDataSet iam_nds_2 = nofa_3_mf.DataSet;

            NavRecordState iam_s_3 = nofa_3_sf[0].State;
            NavDataSet iam_nds_3 = nofa_3_sf[0].DataSet;

            NavRecordState iam_s_4 = nofa_3_sf[1].State;
            NavDataSet iam_nds_4 = nofa_3_sf[1].DataSet;




            //************************************
            //       DATA FIELD CORRELATION
            string DataSet_str_vf_1 = "B2RhdGFTZXR/AAAAAQAAAA9QdXJjaGFzZSBIZWFkZXIJBAAAswAAAAEwCgAAAAAIYm9va21hcmsTAAAAAAExCAAAAAABMhEAAAAAATMRAAAAAAE0EQAAAAABNREAAAAAATYRAAAAAAE3EQAAAAABOBEAAAAAATkRAAAAAAIxMBEAAAAAAjExEQAAAAACMTIRAAAAAAIxMxEAAAAAAjE0EQAAAAACMTURAAAAAAIxNhEAAAAAAjE3EQAAAAACMTgRAAAAAAIxOQ8AAAAAAjIwDwAAAAACMjEPAAAAAAIyMhEAAAAAAjIzEQAAAAACMjQPAAAAAAIyNQ4AAAAAAjI2DwAAAAACMjcRAAAAAAIyOBEAAAAAAjI5EQAAAAACMzARAAAAAAIzMREAAAAAAjMyEQAAAAACMzMOAAAAAAIzNQIAAAAAAjM3EQAAAAACNDERAAAAAAI0MxEAAAAAAjQ1EQAAAAACNDYCAAAAAAI0NwgAAAAAAjUxEQAAAAACNTIIAAAAAAI1MxEAAAAAAjU1EQAAAAACNTYCAAAAAAI1NwIAAAAAAjU4AgAAAAACNTkCAAAAAAI2MA4AAAAAAjYxDgAAAAACNjIRAAAAAAI2MxEAAAAAAjY0EQAAAAACNjURAAAAAAI2NhEAAAAAAjY3EQAAAAACNjgRAAAAAAI2OREAAAAAAjcwEQAAAAACNzIRAAAAAAI3MxEAAAAAAjc0EQAAAAACNzYRAAAAAAI3NxEAAAAAAjc4EQAAAAACNzkRAAAAAAI4MBEAAAAAAjgxEQAAAAACODIRAAAAAAI4MxEAAAAAAjg0EQAAAAACODURAAAAAAI4NhEAAAAAAjg3EQAAAAACODgRAAAAAAI4OREAAAAAAjkwEQAAAAACOTERAAAAAAI5MhEAAAAAAjkzEQAAAAACOTQIAAAAAAI5NREAAAAAAjk3EQAAAAACOTgCAAAAAAI5OQ8AAAAAAzEwMREAAAAAAzEwMhEAAAAAAzEwNBEAAAAAAzEwNxEAAAAAAzEwOBEAAAAAAzEwOREAAAAAAzExNBEAAAAAAzExNQIAAAAAAzExNhEAAAAAAzExOBEAAAAAAzExOQ4AAAAAAzEyMAgAAAAAAzEyMQgAAAAAAzEyMg4AAAAAAzEyMwIAAAAAAzEyNAgAAAAAAzEyNREAAAAAAzEyNhEAAAAAAzEyOQgAAAAAAzEzMBEAAAAAAzEzMREAAAAAAzEzMhEAAAAAAzEzMxEAAAAAAzEzNA4AAAAAAzEzNREAAAAAAzEzNgIAAAAAAzEzNw8AAAAAAzEzOBEAAAAAAzEzOREAAAAAAzE0Mg8AAAAAAzE0MxEAAAAAAzE0NA4AAAAAAzE1MREAAAAAAzE2MAgAAAAAAzE2MRIAAAAAAzE2NQgAAAAAAzE3MBEAAAAAAzE3MREAAAAAAzMwMA4AAAAAAzMwMQ4AAAAAAzQ4MAgAAAAABDEzMDUOAAAAAAQ1MDQzCAAAAAAENTA0OAgAAAAABDUwNTARAAAAAAQ1MDUyEQAAAAAENTA1MxEAAAAABDU3MDARAAAAAAQ1NzUxAgAAAAAENTc1MgIAAAAABDU3NTMIAAAAAAQ1NzkwDwAAAAAENTc5MQ8AAAAABDU3OTIRAAAAAAQ1NzkzEQAAAAAENTgwMBEAAAAABDU4MDERAAAAAAQ1ODAyEQAAAAAENTgwMwIAAAAABDU4MDQRAAAAAAQ4MDAwEgAAAAAEOTAwMBEAAAAABDkwMDEIAAAAAAUxMjQwMAIAAAAABTEyNDAxEQAAAAAFMTI0MDIRAAAAAAUxMjQwMwgAAAAABTEyNDA0AgAAAAAFMTI0MzcIAAAAAAUxMjQzOAgAAAAABTEyNDQwAgAAAAAFMTI0NDEIAAAAAAUxMjQ0MhEAAAAABTEyNDQzCAAAAAAFMTI0NDQRAAAAAAUxMjQ0NREAAAAABTEyNDQ2CAAAAAAFMTI0NDcRAAAAAAUxMjQ3MBEAAAAABTEyNDcxDwAAAAAFMTI0NzIPAAAAAAUxMjQ3Mw8AAAAABTEyNDc0EQAAAAAFMTI0ODAOAAAAAAUxMjQ4NREAAAAABTEyNDg2AgAAAAAFMTI0OTARAAAAAAUxMjQ5MREAAAAABTEyNDk4AgAAAAAFMTI0OTkPAAAAAAQ1NzU0EQAAAAAENTc5NhEAAAAAAgAAAAKpmg0AAAAAAAIrAAAAJgAAAACLAgAAAAJ7/x8EHgQQBBIELQAyADEALQAwADAAMAAzADQAAAAAAAICAAAAAgACEdCf0J7QkNCSLTIxLTAwMDM0AgACAAIAAgACAAIAAgACAAIAAhpDUk9OVVMg0KDQvtGB0YHQuNGPINCX0JDQngIAAgvQoNC40L3QsywgNQIAAgzQnNC+0YHQutCy0LACAAIAQABTjcHYCAIAAAACAEAAU43B2AgCAAAAAgBAAFONwdgIAgAAAAIZSW52b2ljZSDQn9Ce0JDQki0yMS0wMDAzNAIAAgAAAAAAAAAAAgAAAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAgAAAAIAAgACAAIAAgACAAIAAAAAAAAAAAAAAAAAAAAAAgACAAIAAgACAAIAAgAAAAACAAIAAAAAAgACAAIAAgACAAIAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAIR0J/QntCQ0JItMjEtMDAwMzQCEdCf0J7QkNCSLTIxLTAwMDM0AgACAAIAAgACEdCf0J7QkNCSLTIxLTAwMDM0AgACAAIAAgACAAIAAgACAAIFNjIwMDACAAIAAgACAAIAAgACAAIAAgACAAIAAgYxMDMwNTQCAAICUlUCAAAAAAIAAgACAAIAQABTjcHYCAIAAAACAAIAAgACCdCf0J7Qmi0yMAIJ0J/QntCaLTIwAgnQn9Ce0JotMTUCAAIAAgACAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAACAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgACAAAAAAIAAgACAAAAAAIAAgACAAIAAgAAAAAAAAAAAAAAAAAAAAACAAIBAgAAAAAAAAAAAgAAAAIAAgACAAAAAAAAAAACAAAAAgACAAAAAAAAAAAAAAAAAAAAAAIAAgAAAAACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAgACAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAACAQAAAAIAAgACAAIAAgACAAIAAAAAAgAAAAAAAAAAAgAAAAIAAAAAAAAAAAIAAAACAAIAAgACAAIAAgACAAKs0IGOx9pzSZIoLF1gkGW/AgACAAAAAAIBAgACAAIAAAAAAgACAAAAAAIAAAAAAgACAAAAAAIAAgAAAAACAAIAAgAAAAACAAIAAgAAAAAAAAAAAgAAAAIAAAAAAAAAAAIAAAACAAAAAAAAAAACAAAAAgACAAAAAAAAAAAAAAAAAAAAAAIAAgACAAIAAgACAAAAAAAAAAACAAAAAAACqZoNAAAAAAACKwAAACYAAAAAiwIAAAACe/8fBB4EEAQSBC0AMgAxAC0AMAAwADAAMwA0AAAAAAACAgAAAAIAAhHQn9Ce0JDQki0yMS0wMDAzNAIAAgACAAIAAgACAAIAAgACAAIaQ1JPTlVTINCg0L7RgdGB0LjRjyDQl9CQ0J4CAAIL0KDQuNC90LMsIDUCAAIM0JzQvtGB0LrQstCwAgACAEAAU43B2AgCAAAAAgBAAFONwdgIAgAAAAIAQABTjcHYCAIAAAACGUludm9pY2Ug0J/QntCQ0JItMjEtMDAwMzQCAAIAAAAAAAAAAAIAAAACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAIAAAACAAIAAgACAAIAAgACAAAAAAAAAAAAAAAAAAAAAAIAAgACAAIAAgACAAIAAAAAAgACAAAAAAIAAgACAAIAAgACAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAACEdCf0J7QkNCSLTIxLTAwMDM0AhHQn9Ce0JDQki0yMS0wMDAzNAIAAgACAAIAAhHQn9Ce0JDQki0yMS0wMDAzNAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACBjEwMzA1NAIAAgJSVQIAAAAAAgACAAIAAgBAAFONwdgIAgAAAAIAAgACAAIJ0J/QntCaLTIwAgnQn9Ce0JotMjACCdCf0J7Qmi0xNQIAAgACAAIAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAIAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAIAAAAAAgACAAIAAAAAAgACAAIAAgACAAAAAAAAAAAAAAAAAAAAAAIAAgECAAAAAAAAAAACAAAAAgACAAIAAAAAAAAAAAIAAAACAAIAAAAAAAAAAAAAAAAAAAAAAgACAAAAAAIAAAAAAAAAAAAAAAAAAAAAAgAAAAACAAIAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAIAAAAAAgAAAAAAAAAAAAAAAAAAAAACAAAAAAIBAAAAAgACAAIAAgACAAIAAgAAAAACAAAAAAAAAAACAAAAAgAAAAAAAAAAAgAAAAIAAgACAAIAAgACAAIAAqzQgY7H2nNJkigsXWCQZb8CAAIAAAAAAgECAAIAAgAAAAACAAIAAAAAAgAAAAACAAIAAAAAAgACAAAAAAIAAgACAAAAAAIAAgACAAAAAAAAAAACAAAAAgAAAAAAAAAAAgAAAAIAAAAAAAAAAAIAAAACAAIAAAAAAAAAAAAAAAAAAAAAAgACAAIAAgACAAIAAAAAAAAAAAIAAAAAAA==";
            byte[] DataSet_vf_1 = Convert.FromBase64String(DataSet_str_vf_1);

            NavDataSet NavDataSet_2 = new NavDataSet { DataSetName = "NewDataSet" };

            var datasetdata_2 = NavDataSet_2.GetType().GetProperty("DataSet", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public).GetValue(NavDataSet_2);
            datasetdata_2.GetType().GetProperty("Data", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public).SetValue(datasetdata_2, DataSet_vf_1);
            NavDataSet_2.GetType().GetProperty("DataSet", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public).SetValue(NavDataSet_2, datasetdata_2);

            iam_nds_2 = NavDataSet_2;

            //************************************

            service.ValidateField(state: ref iam_s_2, recDataSet: iam_nds_2, 1210014); 
            
            a9("ValidateField");

            //==============================================
            //  MODIFY RECORD
            service.ModifyRecord(state: ref iam_s_2, recDataSet: iam_nds_2);    
            
            a9("ModifyRecord");


            //==============================================
            //  GetPage

            //==============================================
            //  GetPage

            //==============================================
            //  lnvokeApplicationMethod
            NavVisualizationHelper.Initialize(service);

            //==============================================
            //  lnvokeApplicationMethod
            NavVisualizationHelper.Initialize(service);

            //==============================================
            //  lnvokeApplicationMethod
            NavVisualizationHelper.Initialize(service);


            //==============================================
            //  GetPage

            //==============================================
            //  ValidateField

            //==============================================
            //  INSERT RECORD

            //==============================================
            //  GetTableMetadata

            //==============================================
            //  GetMetadataForPageAndAllItsDependencies

            //==============================================
            //  OpenForm

            //==============================================
            //  GetPage

            //==============================================
            //  GetPage

            //==============================================
            //  CloseForm

            //==============================================
            //  Evaluate

            //==============================================
            //  ValidateField

            //==============================================
            //  Evaluate

            //==============================================
            //  ValidateField

            //==============================================
            //  MODIFY RECORD

            //==============================================
            //  CloseForm

            //==============================================
            //  CloseForm

            //==============================================
            //  OpenCompany

            //==============================================
            //  CloseConnection


            Console.WriteLine("13");

        }

        static void a9(string b) {
            Console.WriteLine(b);
        }

        static byte[] returnDataByte(NavDataSet DataSet)
        {
            var DataSetRef = DataSet.GetType().GetProperty("DataSet", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public);
            var recdataset = DataSetRef.GetValue(DataSet);
            byte[] databyte = (byte[])recdataset.GetType().GetProperty("Data").GetValue(recdataset);
            return databyte;
        }


        static DataSetResponse GetPage(INavService INavService_1, int TableId, Guid ServerFormHandle, int PageSize, byte[] startingbookmark, int FormId, StartingPage StartFromPage, int[] calcfields)
        {
            PageRequestDefinition pageRequestDefinition_1 = new PageRequestDefinition(); //("Serialization_5.xml");
            pageRequestDefinition_1.PageSize = PageSize;
            pageRequestDefinition_1.ReadDirection = ReadDirection.Next;
            pageRequestDefinition_1.StartFromPage = StartingPage.Specific;
            NavRecordState pageRequestDefinition_1_state = new NavRecordState(); //("Serialization_6.xml");
            pageRequestDefinition_1_state.TableId = TableId;
            pageRequestDefinition_1_state.FormId = FormId;
            pageRequestDefinition_1_state.ServerFormHandle = ServerFormHandle;
            pageRequestDefinition_1.StartingBookmark = startingbookmark;



            pageRequestDefinition_1.CalcFields = calcfields;

            DataSetResponse DataSetResponse_1 = INavService_1.GetPage(pageRequestDefinition_1, pageRequestDefinition_1_state);

            return DataSetResponse_1;
        }
        static CodeUnitResponse InvokeApplicationMethod(INavService INavService_1, Guid ServerFromHandle, int objectId, int tableId, int formId, RenamingMode RenamingMode, string MethodName,
    byte[] ApplicationMethodRequestDataSetByte, ApplicationCodeType codeType)
        {
            ApplicationMethodRequest applicationMethodRequest = new ApplicationMethodRequest(); //("Serialization_38.xml")
            applicationMethodRequest.ObjectId = objectId;
            applicationMethodRequest.MethodName = MethodName;
            applicationMethodRequest.ApplicationCodeType = codeType;
            applicationMethodRequest.Args = new object[1] { true };
            //     applicationMethodRequest.ExtensionData = new System.Runtime.Serialization.ExtensionDataObject { };

            applicationMethodRequest.DataSetState = new NavRecordState
            {
                TableId = tableId,
                FormId = formId,
                RenamingMode = RenamingMode,
                ServerFormHandle = ServerFromHandle,
                ClientRecordDraft = true,
                CurrentSortingFieldIds = new int[2] { 1, 3 },
            };

            Microsoft.Dynamics.Nav.Types.Data.NavDataSet dataset = new Microsoft.Dynamics.Nav.Types.Data.NavDataSet { DataSetName = "dataSet" };

            NavRecordState applicationMethodRequest_state = new NavRecordState { FormId = tableId, TableId = formId, RenamingMode = RenamingMode, ServerFormHandle = ServerFromHandle };//("Serialization_39.xml");
            var datasetdata = dataset.GetType().GetProperty("DataSet", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public).GetValue(dataset);
            datasetdata.GetType().GetProperty("Data", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public).SetValue(datasetdata, ApplicationMethodRequestDataSetByte);
            dataset.GetType().GetProperty("DataSet", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public).SetValue(dataset, datasetdata);

            applicationMethodRequest.DataSet = dataset;

            CodeUnitResponse CodeUnitResponse = INavService_1.InvokeApplicationMethod(applicationMethodRequest, applicationMethodRequest_state); //1033


            //  applicationMethodRequest.DataSet = applicationdatasetbyte;
            return CodeUnitResponse;
        }

    }
}
